### ISSUE TITLE
No documentation link in expected locations

### ISSUE THREAD

**Issue by lordmauve** [pyparsing/pyparsing#109]
There is no documentation site linked from pypi.org - indeed the project page is blank - or the README of the GitHub repo.

I eventually found [HowToUsePyparsing.rst](https://github.com/pyparsing/pyparsing/blob/master/docs/HowToUsePyparsing.rst) from a closed GitHub issue. Whatever the best documentation resource is, it ought to be linked from

- [ ] The PyPI project page
- [x] The GitHub README

**Comment by ptmcg** [comment]
Your timing is perfect, I was just about to push out version 2.4.2, I'll add these links to the README before doing so.

**Comment by lordmauve** [comment]
The GitHub README now looks great!

The PyPI project page doesn't have a description though; it is showing *The author of this package has not provided a project description*.

By the way, "Project Links" on the left hand of PyPI can contain arbitrary links, including a link to documentation. I believe it is `project_urls` in `setup.py`. From https://setuptools.readthedocs.io/en/latest/setuptools.html:

`project_urls`  
An arbitrary map of URL names to hyperlinks, allowing more extensible documentation of where various resources can be found than the simple url and download_url options provide.

**Comment by ptmcg** [comment]
Would you mind submitting a PR with the necessary changes to setup.py?

**Comment by lordmauve** [comment]
Sure, I'll give it a go if I can find the time.

**Comment by ptmcg** [comment]
Pypi now has a long description with 2.4.3 released today, including doc links
