### ISSUE TITLE
A line width should be established.

### ISSUE THREAD

**Issue by cngkaygusuz** [pyparsing/pyparsing#116]
The PEP8 wiki page clearly indicates the 78-character limit is not going to be adhered. I think 78 is too low, taking the modern development equipment into consideration, nevertheless, a standard should be established, for the sake of being explicit and not leaving an ambiguity.

Instead of 78 characters, I propose to use 120 characters, since it is:
* what most modern python projects use,
* the default setting in Jetbrain's Python IDE (Pycharm),
* the number which _pyparsing_ seem to naturally use as a breaking point. Very few lines go beyond 120 characters.

**Comment by ptmcg** [comment]
Sounds good to me. I'll update the PEP-8 page on the wiki to be more specific on this point.

**Comment by ptmcg** [comment]
Also added an item in CONTRIBUTING instructions.
