### ISSUE TITLE
Nestings got optimized away?

### ISSUE THREAD

**Issue by egberts** [pyparsing/pyparsing#118]
By any chance, does pyparsing perform any optimization with regard to multiple nestings of ParserElements (perhaps via Forward mechanism)?

Perhaps, like:

   { { { deeply_nested_content } } }

into

   { deeply_nested_content }

?

I've posted a standalone Python 3.7 executable exerciser showing where I think the bug occurs at.

https://github.com/egberts/pyparsing/issues/1

**Comment by ptmcg** [comment]
Added some comments on your repo. Looking into this further.

**Comment by egberts** [comment]
Closed as fixed
