### ISSUE TITLE
Discrepancy in datatype returned from a rule's action

### ISSUE THREAD

**Issue by aanastasiou** [pyparsing/pyparsing#124]
This is a bit of a subtle one:

I have a parser that amongst other things, parses a matrix in a text file. At a higher level, the application is not really interested in the values of the matrix but the "object" that emerges from the matrix. For this purpose, I wrote a rule action that turns the matrix values into that "object" and serve it ready for consumption to the application.

And here is where the discrepancy emerged.

`pyparsing` returns "raw" results in a nested list form or, if the rules have been suitably named and `Group`ed, it returns a proper `dict`-like structure.

In my case, the raw `list`-like form contains the object I am creating in its expected form, but the `dict`-like object contains a particular view of the object. Therefore, when I am trying to access the "named" attribute, I receive a different data-type...which is a bit confusing.

Here is a minimal example with just enough detail to reproduce this behaviour:

```
import networkx
import numpy
import pyparsing

def mat_to_net(s, l, t):
    """Convert matrix to network."""
    s = []
    for an_entry in t:
        s.append(list(map(lambda x:int(x), an_entry)))
    mat = numpy.array(s)
    return networkx.from_numpy_array(mat, create_using = networkx.DiGraph)    

def get_parser():
    """Construct the parser.

    Parses something like:
    '010\n100\n110'
    """
    row = pyparsing.Regex(r"[0-1][0-1][0-1]")
    mat = pyparsing.OneOrMore(row)("G").setParseAction(mat_to_net)
    return mat

if __name__ == "__main__":
    data = "000\n000\n110"
    p = get_parser()
    q = p.parseString(data)
```

Now, if you look at `q`, you might get something like this:

```
([<networkx.classes.digraph.DiGraph object at 0x7f5532789be0>], {'G': [AtlasView({})]})
```

The first part is exactly what would be expected as an output: You enter some text and you get back the object you want (a `DiGraph`). But when you look across to the named attribute, you get an entirely different data type (the `AtlasView` is related to a `DiGraph` but it is not what is expected there). 

Not only this is a different data type but the value is different. Basically the `AtlasView` points to an "empty" network.

But, even if we were to take a step backwards here and return the matrix itself (so, exchange `return networkx.from_numpy_array(mat, create_using = networkx.DiGraph)` for `return mat`), we would notice this output:

```
([array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 0]])], {'G': [array([0, 0, 0])]})
``` 
Where, the array in the `list`-like object is as expected, but in the named rule only the first row of this array has survived.

It seems that this might be caused by something like `return something[0]` (emphasis on **[0]**) somewhere within `pyparsing` because if you substitute `return mat` for `return [mat]` (in the example above now), the returned results are as expected. For example:

```
([<networkx.classes.digraph.DiGraph object at 0x7f5533563390>], {'G':[([<networkx.classes.digraph.DiGraph object at 0x7f5533563390>], {})]})
```
Which is fine, except for having to descent within one more list while processing the results. This is not such a big problem in a shallow structure like this one but when you parse more complex data structures, this extra `[0]` that must be added would be a source of confusion.

I did have a look within `pyparsing` but I was not able to locate where this might be hapenning with certainty. Perhaps [line 5256](https://github.com/pyparsing/pyparsing/blob/master/pyparsing.py#L5256) (?).

Hope this helps.

**Comment by ptmcg** [comment]
Email thread:

----------------------------
I did get to look at this this morning. The steps which are the culprit are:

- returning a list-like value from a parse action,
- which was called from ParserElement._parseNoCache,
- which was used to construct a new ParseResults,
- and which made assumptions about how to create the ParseResults based on the data type

90+% of the time, these assumptions work fine. You can force your own ParseResult construction in your parse action.  Try:

    return pyparsing.ParseResults(networkx.from_numpy_array(mat, create_using = networkx.DiGraph))

I am leery about changing the assumptions part of this to permit you to simply return the networkx object, as it would like have a large impact on the pyparsing parse action pre/post-condition expectations in existing code. But if this gives you some more leads to follow, and some thoughts on how to keep this down to the simple "just return what you need to return" case, I'm open to suggestions.
    
-- Paul

----------------------------
Hello Paul

Thank you very much for your message, helpful and informative as always.

So, to wrap the return value in a pyparsing.ParseResults object would provide the best "safety" and isolation from parser internals as possible (?)

Is this a more general approach or the better way to write this particular scenario?

All the best
Athanasios Anastasiou

----------------------------
I think this is going to be The Way To Do It.

Look at the example parsePythonValue.py, which predates ast.literal_eval as a safe eval for Python values as a string. Returning dicts, tuples, floats, strs, etc. from their respective conversion parse actions are simple, but I have to jump through this hoop to return a list from a parse action:

    return [parsed_tokens_as_a_python_list]

And then add a second parse action `lambda x: x[0]`. Which I came to empirically (which is the less embarrassing way of saying "trial and error"). And what I think is happening here is that the first parse action returns a list inside a list, which pyparsing converts to a nested ParseResults, and then when we slice off the 0'th element, we get that element wrapped in a ParseResults. I think I could have saved myself the trouble and just returned `ParseResults(parsed_tokens_as_a_python_list)`, and omitted the second parse action. (a quick experiment verifies this)

**Comment by klahnakoski** [comment]
Yes, I have also found that converting methods to return `ParseResults` will help reduce the assumptions the other parts of the code make.

**Comment by aanastasiou** [comment]
@ptmcg Thank you very much, this settles it then :) . All the best.
