### ISSUE TITLE
API documentation not available

### ISSUE THREAD

**Issue by grebinger** [pyparsing/pyparsing#13]
The API documentation on the pyparsing homepage seems to be empty. Is there any other way to access it?

**Comment by michael-christen** [comment]
I've been using the web archive in the meantime: https://web.archive.org/web/20180105215257/https://pyparsing.wikispaces.com/

**Comment by ptmcg** [comment]
For now, please reference the online module, class, and method docs at https://pythonhosted.org/pyparsing/pyparsing-module.html  - I've also added this link and some very minor updates to the HowToUsePyparsing.rst file.

**Comment by michael-christen** [comment]
Thanks @ptmcg

**Comment by lordmauve** [comment]
https://pythonhosted.org/pyparsing/pyparsing-module.html is for 2.2.0. Also frames are broken because pythonhosted.org is serving `X-Frame-Options: deny` headers. So https://pythonhosted.org/pyparsing/ is broken.
