### ISSUE TITLE
Missing doc for setParseAction

### ISSUE THREAD

**Issue by JohnCC330** [pyparsing/pyparsing#148]
In the `EpyDoc`-generated docs, info for `setParseAction` is missing (even though `traceParseAction` is present).

**Comment by ptmcg** [comment]
Please send a link for which Epydoc-generated docs you mean. The ones on pythonhosted include this: https://pythonhosted.org/pyparsing/pyparsing.ParserElement-class.html#setParseAction

**Comment by JohnCC330** [comment]
Hi @ptmcg 
That site (the one you mentioned) came up several times in my search, but in frames mode. All 3 frames were completely empty, so I skipped it (just tried, following your link, to frames mode, and it went empty again) (Firefox 69.0). 

The version I used is only slightly older Oct 06 20:32:30 2016 vs Mar 05 20:19:55 2017. My version is archived on my computer, so I don't know its origin. Probably it was on [Wikispaces](https://pyparsing.wikispaces.com/) - but the page doesn't exist anymore.

**Comment by ptmcg** [comment]
Yes, the pyparsing page at wikispaces is no more. There is a [github repo](https://github.com/pyparsing/wikispaces_archive) where you can browse the archived discussion pages from there, converted to markdown.

@crowsonkb is maintaining their own copy of up-to-date epydoc-generated docs [here](https://pyparsing-doc.neocities.org/), and it includes doc for [setParseAction](https://pyparsing-doc.neocities.org/pyparsing.ParserElement-class.html#setParseAction).

I'm pretty sure all the current online docs for pyparsing include this method, so I'm closing this issue.
