### ISSUE TITLE
Unable to parse basic subscript!

### ISSUE THREAD

**Issue by enjoysmath** [pyparsing/pyparsing#153]
```
from pyparsing import *

var_alpha_regex =  \
   r'[a-zA-Z]|' + \
   r'\\alpha|\\beta|\\gamma|\\delta|\\epsilon|' + \
   r'\\zeta|\\eta|\\theta|\\vartheta|\\iota|' + \
   r'\\kappa|\\lambda|\\mu|\\nu|\\xi|\\pi|' + \
   r'\\rho|\\varrho|\\sigma|\\tau|\\upsilon|' + \
   r'\\phi|\\varphi|\\chi|\\psi|\\omega' + \
   r'\\Gamma|\\Delta|\\Theta|\\Xi|\\Pi|\\Sigma' + \
   r'\\Upsilon|\\Phi|\\Psi|\\Omega|.'  # Yes an "any char" at end
any_chr = Regex('.')
var_alpha = Regex(var_alpha_regex)
expr = Forward()
subscript = '_' + (('{' + expr + '}') ^ any_chr)
supscript = '^' + (('{' + expr + '}') ^ any_chr)
script = (subscript + Optional(supscript)) ^ (supscript + Optional(subscript))
variable = var_alpha + Optional(script)
expr = variable ^ any_chr

if __name__ == '__main__':
   while True:
      s = input("s=")
      var = variable.parseString(s)
      print(var)
```

Copy / paste that code into a python editor and run.  Type in:
a_{1}

The parse result is [a, _, {] !!

Please help me find out what's not working.

**Comment by enjoysmath** [comment]
Found it actually just now as I saw the last line
It requires:
expr <<= ... 
to work
not 
expr = ...

**Comment by ptmcg** [comment]
Glad you got this worked out for yourself, well done. Check out `variable.runTests` to define a list of known test strings you would like to run repeatedly. I also posted [a blog post](https://thingspython.wordpress.com/2018/12/22/adventures-in-unicode-parsing-superscript-exponent) on parsing actual superscripts, subscript character parsing should be similar.
