### ISSUE TITLE
Support arbitrary sequences, not just strings

### ISSUE THREAD

**Issue by SoniEx2** [pyparsing/pyparsing#154]
On most parsers, you'd have separate tokenizer and parser. However, with PEGs, this style is generally unsupported. I find that it makes parsing a lot easier, with cleaner and more maintainable code. As such, could we be able to operate on sequences/lists in addition to strings? Thanks.

**Comment by ptmcg** [comment]
I'm glad PEG parsing is making your development and maintenance life easier.

Your idea of applying PEG parsing concept to other types of sequences besides strings has cropped up in the past, though I don't recall seeing any actual projects using them other for string parsing. But the basic idea could definitely be applied to sequences such as lines in a log (each line is itself a sequence element, and PEG expressions could look for "start" line, one or more non-"end" lines, and an "end" line, and then package that as a Log Group - I think I *have* seen this project, though I don't recall where).

As extensible as pyparsing is, I think that stretching it to handle non-string sequences is beyond its (my?) coding limits. A separate project that starts out with this premise (and maybe factors in a few lessons-learned from pyparsing and other Python PEG projects) would be more promising. You could then try it out with the log example, maybe an event stream (detecting flapping events on a network, for instance). But I suspect that if you then took that package and said "well, strings are sequences too" and used it for garden-variety parsing, I think you'd find that the extra overhead in the flexibility of this new package would make it even slower (and I would guess *much* slower, unless some C or at least Cython work was brought to bear) than pyparsing.

**Comment by SoniEx2** [comment]
I think separating the concerns of "input tokenization" and "token parsing" would solve some of the common issues ppl make with pyparsing because then you'd be thinking of individual tokens and not a mix of tokens and raw input. This also allows deprecating the whitespace thing.

Just my 2 cents.

**Comment by cdonovick** [comment]
@SoniEx2 
I am currently performing tokenization then rewriting my token stream to a string (e.g. `"token_type$id"`) which I then feed to pyparsing.  I agree that having arbitrary sequences  would be nice but if you already have a tokenizer it shouldn't be to hard to serialize.

**Comment by ptmcg** [comment]
If you are looking for more traditional parsing methods, then you should look at using PLY or spark. Whitespace skipping is a fundamental concept for pyparsing, as is the combination of tokenizing and parsing.

**Comment by SoniEx2** [comment]
I'm just asking for the ability to change what counts as "whitespace" and so on, but on a deeper level than just characters - instead going for full objects. I guess lark has that option but it's also not PEGs so ugh.
