### ISSUE TITLE
Register ParseResults as Sequence

### ISSUE THREAD

**Issue by SoniEx2** [pyparsing/pyparsing#156]
Currently ParseResults is only a MutableMapping. It would be nicer if it was also a Sequence, altho I'm not sure if there's anything that would prevent this from working.

**Comment by ptmcg** [comment]
It seems that I can even register it as a MutableSequence, since it implements all the necessary methods.

I can include this in the next 2.4.3 and 3.0.0 releases

**Comment by ptmcg** [comment]
Releasing the 2.4.x branch was more complicated than expected, so this addition got left out. It will be part of 3.0.0 though.

I'm curious though - when you say "it would be nicer if it was also a Sequence", what specific usages are you thinking of, that this would enable that is not possible now?

**Comment by klahnakoski** [comment]
If there is ABC registration, I suggest registering ParseResults as a `Sequence`, not a `MutableSequence`:  I would like to see Pyparsing move toward more functional style; tending toward copying ParseResults rather than mutating ParseResults.

**Comment by SoniEx2** [comment]
I refactored my code so as to not need to check whether or not it's a sequence. Maybe it's better this way.

**Comment by ptmcg** [comment]
Released in 3.0.0rc2 (actually much earlier, I'm just getting to cleaning up old business!)
