### ISSUE TITLE
Hypothesis integration

### ISSUE THREAD

**Issue by SoniEx2** [pyparsing/pyparsing#165]
The hypothesis module is super useful. I want pyparsing to generate strings that match the peg when I stick the peg in `@hypothesis.given`, which is meant for generating pseudorandom inputs for testing.

see also https://hypothesis.readthedocs.io/en/latest/extras.html#hypothesis-lark

**Comment by ptmcg** [comment]
Can you elaborate? How would this look in practice? What exactly would it do with `hypotheis.given`?

**Comment by SoniEx2** [comment]
It would do its best to generate a string that matches the grammar.

**Comment by ptmcg** [comment]
I'd be happy to work with you on an extension to hypothesis similar to the lark extension. I don't see this as being a part of pyparsing itself though, just as the hypothesis-lark extension does not seem to be part of lark.
