### ISSUE TITLE
`ParserElement.setDebugActions` is undocumented

### ISSUE THREAD

**Issue by mgrandi** [pyparsing/pyparsing#166]
I was going to create an issue where calling `<ParserElement>.setDebug(True)` was logging to stdout rather than using the `logging` module, but then I noticed that there is a function to override what pyparsing calls when it wants to debug: the `setDebugActions` method

its documented here: 

https://github.com/pyparsing/pyparsing/blob/0b398062710dc00b952636bcf7b7933f74f125da/pyparsing/core.py#L1429-L1435 

but not in the documentation: 

https://github.com/pyparsing/pyparsing/blob/0b398062710dc00b952636bcf7b7933f74f125da/docs/HowToUsePyparsing.rst

**Comment by ptmcg** [comment]
There *is* a docstring for `setDebugActions`, but it is pretty skimpy. And this can be a pretty useful tool for doing performance testing on your parser.

The GH Wiki has a page that links to the 'readthedocs' page, with more docs on pyparsing.

**Comment by mgrandi** [comment]
it seems that the documentation on read the docs is just plain outdated, i've noticed several bugs that have been fixed in the source code, maybe the task that generates it and uploads it to read the docs is broken?

**Comment by paulmcg-iio** [comment]
Yes, somehow the webhook for RTD got disabled, should be fully updated now.

**Comment by ptmcg** [comment]
Released in 3.0.0rc2
