### ISSUE TITLE
Group collection

### ISSUE THREAD

**Issue by egberts** [pyparsing/pyparsing#167]
I've got this '`all_zones`' Group() down pat ... a bit.
## Ordered Lines, Expected Result ##
I have the following test_string:
```
zone XXX;
zone ZZZ;
options YYY;
```
And and I see that that Group() collection is working well, like in my desired `asDict()` result below:
```
result = { 
    'options': {'name: 'YYY'},
    'all_zones': [
        { 'zone': {'name': 'XXX'}},
        { 'zone': {'name': 'ZZZ'}}
    ]
}
```
## Reordered Lines, different and missing result ##
I tripped myself purposely up a bit with a bit of line reordering of the test_string:
```
zone XXX;
options YYY;
zone ZZZ;
```
And the `asDict()` result becomes different (and missing a test line)...
```
result = { 
    'options': {'name': 'YYY'},
    'all_zones': [
        { 'zone': {'name': 'ZZZ'}}
    ]
}
```
As you can see, the parser rules that I have set up only collects the last one of the 'zone' Group instead of 'all' of the zone group items and stored it under 'all_zones' group.

The question I have is, "Is it possible to keep collecting 'zone' Group items after it leaves the 'all_zones' parser block?

**Comment by egberts** [comment]
Is it one of those push-pop stack mechanism that one needs to introduce to '`all_zones`' block?

**Comment by ptmcg** [comment]
Not sure why you self-closed this - I think a combination of Each ('&' operator) and 'listAllMatches' may take care of things for you:


    import pyparsing as pp
    ppc = pp.pyparsing_common

    ZONE, OPTIONS = map(pp.CaselessKeyword, "zone options".split())
    SEMI = pp.Suppress(";")
    value = ppc.identifier | ppc.number

    zone_expr = ZONE + ppc.identifier("name") + SEMI
    options_expr = OPTIONS + value("name") + SEMI

    # use trailing '*' for 'listAllMatches' behavior, collects all matching
    # expressions into a single entry
    zones_and_options = (
        pp.ZeroOrMore(pp.Group(zone_expr)("all_zones*"))
        & pp.ZeroOrMore(pp.Group(options_expr)("all_options*"))
        )

    tests = [
        """
        zone XXX;
        zone ZZZ;
        options YYY;
        """,
        """
        zone XXX;
        options YYY;
        zone ZZZ;
        """,
        ]

    zones_and_options.runTests(tests)

prints:

```


    zone XXX;
    zone ZZZ;
    options YYY;
    
[['zone', 'XXX'], ['zone', 'ZZZ'], ['options', 'YYY']]
- all_options: [['options', 'YYY']]
  [0]:
    ['options', 'YYY']
    - name: 'YYY'
- all_zones: [['zone', 'XXX'], ['zone', 'ZZZ']]
  [0]:
    ['zone', 'XXX']
    - name: 'XXX'
  [1]:
    ['zone', 'ZZZ']
    - name: 'ZZZ'


    zone XXX;
    options YYY;
    zone ZZZ;
    
[['zone', 'XXX'], ['options', 'YYY'], ['zone', 'ZZZ']]
- all_options: [['options', 'YYY']]
  [0]:
    ['options', 'YYY']
    - name: 'YYY'
- all_zones: [['zone', 'XXX'], ['zone', 'ZZZ']]
  [0]:
    ['zone', 'XXX']
    - name: 'XXX'
  [1]:
    ['zone', 'ZZZ']
    - name: 'ZZZ'

```
