### ISSUE TITLE
Pyparsing fails to parse optional subscript, but always returns first substring of parse

### ISSUE THREAD

**Issue by enjoysmath** [pyparsing/pyparsing#169]
Here's the minimal running example:

```
from pyparsing import Regex, Suppress, Optional
from pyparsing import pyparsing_common as com

alphabet = Regex(
   r"[a-zA-Z]|\\alpha|\\beta|\\gamma")

def subscript(expr):
   return Suppress("_{") + expr + Suppress("}")

def superscript(expr):
   return Suppress("^{") + expr + Suppress("}")

def script_usual(subexpr, supexpr):
   return subscript(subexpr) + superscript(supexpr)

def script_reverse(subexpr, supexpr):
   grammar = superscript(supexpr) + subscript(subexpr)
   grammar.addParseAction(lambda toks: list(reversed(toks)))
   return grammar

def script(subexpr, supexpr=None):
   if supexpr is None:
      supexpr = subexpr.copy()
   return script_usual(subexpr, supexpr) | script_reverse(subexpr, supexpr)

integer_or_letter = alphabet | com.signed_integer


class Object:
   grammar = alphabet + Optional(script(integer_or_letter))
   
   
if __name__ == '__main__':
   while True:
      s = input("s=")
      #r = alphabet.parseString(s)
      r = Object.grammar.parseString(s)
      print(r)
```

This shows that it's not doing what you'd expect:

![image](https://user-images.githubusercontent.com/1606391/69746877-1b0e1e80-10fa-11ea-8f68-8c7625715261.png)

**Comment by ptmcg** [comment]
It might not be doing what you expect, but I think it is doing exactly what you asked. What is the purpose of `script_usual` and `script_reversed`? If I print out the grammar as you have defined it (after calling `streamline` to reduce redundant groupings), I get:

    Object.grammar.streamline()
    print(Object.grammar)
    
    """
    {Re:('[a-zA-Z]|\\\\alpha|\\\\beta|\\\\gamma') 
     [{{Suppress:("_{") {Re:('[a-zA-Z]|\\\\alpha|\\\\beta|\\\\gamma') | signed integer} Suppress:("}") 
        Suppress:("^{") {Re:('[a-zA-Z]|\\\\alpha|\\\\beta|\\\\gamma') | signed integer} Suppress:("}")} 
     | {Suppress:("^{") {Re:('[a-zA-Z]|\\\\alpha|\\\\beta|\\\\gamma') | signed integer} Suppress:("}") 
        Suppress:("_{") {Re:('[a-zA-Z]|\\\\alpha|\\\\beta|\\\\gamma') | signed integer} Suppress:("}")}}
        ]
    }
    """

That is, your expression must contnain *both* a superscript and a subscript, in either order for this to be a match. I converted to using runTests to get some nicer messages:

    Object.grammar.runTests("""\
        # original test, just a single subscript
        a_{1}
        
        # a subscript and a superscript, necessary to match parser
        a_{1}^{0}
        """)

Gives

```
# original test, just a single subscript
a_{1}
 ^
FAIL: Expected end of text, found '_'  (at char 1), (line:1, col:2)
# a subscript and a superscript, necessary to match parser
a_{1}^{0}
['a', 1, 0]
```

I think you might want to explicitly spell out what you want this grammar to be, before composing it by using method calls.

**Comment by ptmcg** [comment]
If your desired parser is to parse an optional subscript and/or optional superscript, in either order, then this can be done using a pyparsing Each, created with the '&'' operator:

    superscript_expr = superscript(integer_or_letter)
    subscript_expr = subscript(integer_or_letter)
    grammar2 = alphabet + (Optional(superscript_expr) & Optional(subscript_expr))
    
    tests = """\
        # original test, just a single subscript
        a_{1}
        
        # just a single superscript
        a^{1}
        
        # no super or subscript
        a
        
        # a subscript and a superscript
        a_{1}^{0}    

        # a superscript and a subscript
        a^{1}_{0}
        
        # BAD - two superscripts
        a^{1}^{2}
    """

    grammar2.runTests(tests)

Prints:

    # original test, just a single subscript
    a_{1}
    ['a', 1]
    # just a single superscript
    a^{1}
    ['a', 1]
    # no super or subscript
    a
    ['a']
    # a subscript and a superscript
    a_{1}^{0}
    ['a', 1, 0]
    # a superscript and a subscript
    a^{1}_{0}
    ['a', 1, 0]
    # BAD - two superscripts
    a^{1}^{2}
         ^
    FAIL: Expected end of text, found '^'  (at char 5), (line:1, col:6)

This parses things, but we have lost the critical information about which is the sub and which is the super. We can add this info back using results names:

    grammar3 = alphabet + (Optional(superscript_expr("super")) & Optional(subscript_expr)("sub"))
    grammar3.runTests(tests)

prints:

```
# original test, just a single subscript
a_{1}
['a', 1]
- sub: [1]
# just a single superscript
a^{1}
['a', 1]
- super: [1]
# no super or subscript
a
['a']
# a subscript and a superscript
a_{1}^{0}
['a', 1, 0]
- sub: [1]
- super: [0]
# a superscript and a subscript
a^{1}_{0}
['a', 1, 0]
- sub: [0]
- super: [1]
# BAD - two superscripts
a^{1}^{2}
     ^
FAIL: Expected end of text, found '^'  (at char 5), (line:1, col:6)
>Exit code: 0

```

**Comment by ptmcg** [comment]
Any further questions on this? Otherwise, I will close it out.
