### ISSUE TITLE
Reimplement indentedBlock as ParseElementEnhance subclass

### ISSUE THREAD

**Issue by ptmcg** [pyparsing/pyparsing#170]
Current `indentedBlock` method suffers from several design flaws.
1. Bug introduced by "fix" adding fail action to support use of scanString
2. indentStack does not initialize properly when starting block within larger parser
3. Single global indentStack shared by all indentedBlocks (may or may not be correct behavior)

Reimplement as recursive `IndentedBlock(ParseElementEnhance)` taking a single expression argument, and allowing nested sub-blocks.

**Comment by TMiguelT** [comment]
Oh no, how did I break it with my fix? 😬

**Comment by TMiguelT** [comment]
Ah, just found #87

**Comment by ptmcg** [comment]
First pass at this is in 3.0.0b1 release
