### ISSUE TITLE
Interested in joining dev team

### ISSUE THREAD

**Issue by mattcarmody** [pyparsing/pyparsing#176]
I posted on reddit, I'd like to help with test coverage

**Comment by klahnakoski** [comment]
@mattcarmody   Good day!  I have done a small amount of contribution here.  I did a quick scan of uncovered lines and there are opportunities for more test coverage, although they are in debug modes, catching errors, and weird languages.

* You may consider submitting a pull request that adds a parsing test; one that will cover some net new lines.
* Not all the `examples` are in the test suite: If one provides more coverage, then add it to `test_examples.py`
* If you are feeling adventurous, you may want to connect pyparsing to a [fuzzer]((https://developer.mozilla.org/en-US/docs/Glossary/Fuzzing) and auto-generate some pathological cases.  I know Mozilla has some fuzzers, but I never used one myself.

**Comment by mattcarmody** [comment]
Hi @klahnakoski , thanks for reaching out! @ptmcg  sent me some guidance last night as well, I'm going to start by looking at adding coverage for error catching. Thanks for sharing the fuzzing article, I'd never heard of that before and will look into it a bit.

**Comment by ptmcg** [comment]
Added to the dev team - welcome!
