### ISSUE TITLE
newbie question: how to capture phrases of all caps words

### ISSUE THREAD

**Issue by doolingdavid** [pyparsing/pyparsing#182]
I am trying to use pyparsing to capture all phrase from a text that look like 
ASDF ADSF DFD 
Naively, below does not work, and am wondering how to modify it so that the grammar below should FAIL on this example:
kw = Word("ABCDEFGHIJKLMNOPQRSTUVWXYZ*",min=2)
test = "SDFFGDSFFG4545adasd wretwretWERTRWET"
result = OneOrMore(kw).parseString(test)
print(result)
['SDFFGDSFFG']

**Comment by ptmcg** [comment]
Pyparsing parsers, similar to regex, will return success if they match the given input string up until they run of parser definitions. Your code matched the leading `"SDFFGDSFFG"`, which matches `OneOrMore(kw)`, so success! If you want to match *only* if the entire input string matches (like taking `'$'` onto the end of a regex), then call `parseString` with the added argument `parseAll=True`.

**Comment by doolingdavid** [comment]
Thank you Paul!   below are two code snippets that work now as I need them to.
kapital_word = Word(alphas.upper(), alphas.upper() +'*')
WS = WordStart()
WE = WordEnd()
total = WS + OneOrMore(kapital_word) + WE
test = "SDFFGDSFFG4545adasd wretwretWERTRWET"
check = """MATERIAL and AD*D DIAT*OM\n\n INPUT"""
#result = OneOrMore(kapital_word).searchString(check)
result = total.searchString(check)
print(result)
>>> [['MATERIAL'], ['AD*D', 'DIAT*OM', 'INPUT']]

kapital_word = Word(alphas.upper(), alphas.upper() +'*')
WS = WordStart()
WE = WordEnd()
total = WS + OneOrMore(kapital_word) + WE
test = "SDFFGDSFFG4545adasd wretwretWERTRWET"
check = """MATERIAL and AD*D DIAT*OM\n\n INPUT"""
#result = OneOrMore(kapital_word).searchString(check)
result = total.searchString(test)
print(result)
>>> []

excited to delve in more and become fluent in pyparsing!
