### ISSUE TITLE
testOneOrMoreStop is broken

### ISSUE THREAD

**Issue by klahnakoski** [pyparsing/pyparsing#188]
https://github.com/pyparsing/pyparsing/blob/dc1ca6846691df2c2f36136fe749d790e9af6f37/tests/test_unit.py#L4303

I do not know how this passes, but the test is wrong:

        test = "BEGIN aaa bbb ccc END"
        BEGIN, END = map(Keyword, "BEGIN,END".split(","))
        body_word = Word(alphas).setName("word")
        for ender in (END, "END", CaselessKeyword("END")):
            expr = BEGIN + OneOrMore(body_word, stopOn=ender) + END
            self.assertEqual(
                expr, test, "Did not successfully stop on ending expression %r" % ender
            )

The assert is comparing the **parser**, not the parse **results**.  I suggest something like

            expr = BEGIN + OneOrMore(body_word, stopOn=ender) + END
            result - expr.parseString()
            self.assertEqual(
                result, test.split(), "Did not successfully stop on ending expression %r" % ender
            )

**Comment by paulmcg-iio** [comment]
Not necessarily broken, but probably obscure. ParserElement implements
`__eq__` such that, if comparing an expression with a string, `parser ==
test_string` can be a shortcut for `parser.matches(test_string)`.  Should
convert these tests to use one of the new pyparsing_test asserts. Also, if
we retain this '==' operator (I've had complaints), it should probably call
`parser.matches(test_string, parseAll=True)`.

**Comment by ptmcg** [comment]
Missed the cut for 3.0.0rc1. Will include in the next release.

**Comment by ptmcg** [comment]
Released in 3.0.0rc2
