### ISSUE TITLE
Reaching the end of string before the indentedBlock has unindented does not reset the stack

### ISSUE THREAD

**Issue by multimeric** [pyparsing/pyparsing#195]
Sorry about all these issues. Just more indentation woes!

As in the title. For example:
```python
from pyparsing import *

stack = [1]
block = 'block:' + indentedBlock(Literal('content'), indentStack=stack)
block.parseString("""
block:
    content
""")
print(stack)
```
```
[1, 5]
```

This is a problem, because if I try to parse the same string again it won't work since it's expecting the indentation to start at 5 now.

I suspect in the situation where we react end-of-string before unindent, it should fail to parse rather than succeeding and then causing future issues.

**Comment by ptmcg** [comment]
This is an oldie - if still relevant, could you retry using the new IndentedBlock class? It keeps its own stack internally.

If not relevant, please close.

**Comment by multimeric** [comment]
Well, I don't understand why, but this does now work. Previously we had:

```python
from pyparsing import *

block = 'block:' + indentedBlock(Literal('content'), indentStack=[1])
for i in range(2):
    print(block.parseString("""
    block:
        content
    """))
```
```
['block:', [['content']]]
pyparsing.exceptions.ParseException: not a subentry, found 'content'  (at char 20), (line:3, col:9)
```

***
Now we have:

```python
from pyparsing import *

block = 'block:' + IndentedBlock('content')
for i in range(2):
    print(block.parseString("""
    block:
        content
    """))
```
```
['block:', ['content']]
['block:', ['content']]
```

***

Don't understand why this now works, but it does! Great stuff.
