### ISSUE TITLE
Import error in IronPython 2.7.7

### ISSUE THREAD

**Issue by eirannejad** [pyparsing/pyparsing#2]
Hey @ptmcg 
This error happens on module import in IronPython 2.7.7 (file paths are simplified to `...\` for brevity)
```
Traceback (most recent call last):
 File "...\script.py", line 4, in 
 File "...\pyparsing.py", line 4734, in 
 File "...\pyparsing.py", line 1261, in setParseAction
 File "...\pyparsing.py", line 1043, in _trim_arity
IndexError: index out of range: -1
```

I revised the line # 1043:1044 to below to avoid the issue:
Before:
``` python
    LINE_DIFF = 6
    # IF ANY CODE CHANGES, EVEN JUST COMMENTS OR BLANK LINES, BETWEEN THE NEXT LINE AND
    # THE CALL TO FUNC INSIDE WRAPPER, LINE_DIFF MUST BE MODIFIED!!!!
    this_line = extract_stack(limit=2)[-1]
    pa_call_line_synth = (this_line[0], this_line[1]+LINE_DIFF)
```

After:
``` python
    LINE_DIFF = 6
    # IF ANY CODE CHANGES, EVEN JUST COMMENTS OR BLANK LINES, BETWEEN THE NEXT LINE AND
    # THE CALL TO FUNC INSIDE WRAPPER, LINE_DIFF MUST BE MODIFIED!!!!
    exstack = extract_stack(limit=2)
    if exstack:
        this_line = extract_stack(limit=2)[-1]
        pa_call_line_synth = (this_line[0], this_line[1]+LINE_DIFF)
    else:
        pa_call_line_synth = ''

```
This temporarily resolves the issue but I hope you can provide a more appropriate fix.
Thank you for `pyparsing`.

**Comment by ptmcg** [comment]
Thanks for reporting this bug - I don't generally test with IronPython, so I would not have seen this. I have some other pyparsing work I need to do in the next few days, so I'll look at this a little deeper then.

**Comment by slide** [comment]
Is there a way we can make it easier to test on IronPython? Obviously, we would love it if we were 100% compatible with C Python, but it's a work in progress. If we could make it easier for you to test with IronPython, maybe we could intercept the issues quicker and understand them.

**Comment by eirannejad** [comment]
Uhm I haven't tried the test case in the repo but I'll run that on IronPython and will run tests. I can submit a PR with any modifications.

**Comment by PeterSorrell** [comment]
I had the same problem with PIP on IronPython 2.7.8 and after a LONG time searching for an answer, your modification to file pyparsing.py fixed it for me - many thanks.
BTW, does "LINE_DIFF = 6" need to be changed, as suggested by the comments?
Cheers.

**Comment by PeterSorrell** [comment]
I have just installed IronPython 2.7.8 on another machine and (obviously) had to do the same modification to pyparsing.py.
When should we expect a legitimate update to this release?
Thanks

**Comment by slide** [comment]
@PeterSorrell Are you using pyparsing directly, or some other package that uses pyparsing?

**Comment by PeterSorrell** [comment]
I am using "pip" within IronPython, e.g.
"ipy -X:Frames -m pip --version"

**Comment by littleq0903** [comment]
The issue IronPython not returning stack info had been fixed in this PR: https://github.com/IronLanguages/ironpython2/pull/489

**Comment by ptmcg** [comment]
Just a little more background on just what the heck pyparsing is doing here - this is part of the magical `_trim_arity` method, which will internally raise Python TypeError exceptions while determining the arity of a parse action. Unfortunately, this normally masks any reall TypeError exceptions that might be raised by the parse action itself, to the consternation of parse action developers trying to debug their code. By looking at the stack for raised TypeErrors, we can see if this is an internal pyparsing exception or one raised in user-provided code.

Can I close this issue as being resolved by the fix in IronPython listed above? For those cases where IP returns an empty stack, pyparsing cannot determine the source of the TypeError exceptions raised when running parse actions. The best I could do in that case would be to add defensive code to prevent the raising of the IndexError.

**Comment by ptmcg** [comment]
Closing issue, since problem is resolved in updated IronPython
