### ISSUE TITLE
Common parsing elements (such as floatNumber) should be importable?

### ISSUE THREAD

**Issue by metaperl** [pyparsing/pyparsing#200]
Should common parsing elements, such as [floatNumber](https://github.com/pyparsing/pyparsing/blob/master/examples/LAparser.py#L105):

```
floatnumber = Combine(
    integer + Optional(point + Optional(number)) + Optional(e + integer)
)
```

be available for importing instead of having to manually code them?

**Comment by ptmcg** [comment]
I received similar requests from many users over the years, and finally in version 2.1.4, I added the pyparsing_common namespace class for a number of common expressions.

```
>>> from pyparsing import pyparsing_common as ppc
>>> print(ppc.integer[...].parseString("1 23 42"))
[1, 23, 42]
>>> print(ppc.number[...].parseString("1 23 42"))
[1, 23, 42]
>>> print(ppc.number[...].parseString("6.02e23"))
[6.02e+23]

```
You can read more at https://pyparsing-docs.readthedocs.io/en/pyparsing_2.4.6/pyparsing.html#pyparsing.pyparsing_common, or `help(pyparsing.pyparsing_common)`
