### ISSUE TITLE
infixNotation, parentheses, performance

### ISSUE THREAD

**Issue by Igreh** [pyparsing/pyparsing#204]
Hi! 
We are faced with high performance degradation issue for strings with multiple nesting levels. Just curious - is it bug or feature? Are there any workarounds?

To reproduce:
Take pyparsing/examples/simpleArith.py and add new tests:
~~~python
    "(a + b)",
    "((a + b))",
    "(((a + b)))",
    "((((a + b))))",
~~~
each new pair of parentheses slow parsing process significantly.
Anyway, thanks for such a great tool!

**Comment by ptmcg** [comment]
Good catch! I added your examples and the parser does indeed slow to a crawl.

The typical solution to this problem for any recursive parser (as in all parsers defined using infixNotation) is to enable packrat parsing.  I'm surprised I haven't added that to this example.

Immediately after importing pyparsing, add this line:

    ParserElement.enablePackrat()

With this change (and bumping up the sys recursion limit to 3000), I can now parse this expression almost instantly:

        "((((((((((((((a + b))))))))))))))",

**Comment by Igreh** [comment]
Works like a charm!
Thanks!
