### ISSUE TITLE
Is it possible to use pyparsing to parse a lua program?

### ISSUE THREAD

**Issue by yldiscover** [pyparsing/pyparsing#212]
Hi,
   I haved written a bnf for lua to parse a lua program, but it seems that the bnf definition will cause infinite  recursion error. when defining "exp" in lua.
   Could somebody tell me how to do it?

**Comment by ptmcg** [comment]
The lua BNF that I found online has a similar issue, defining `exp` using `prefixexp`, but `prefixexp` is defined as optionall beginning with `exp`. This problem, called "left recursion" is not currently supported in pyparsing. There are methods for re-organizing a left-recursive grammar to eliminate the left-recursion, so I would say the answer to your question is "yes, it is very likely possible to use pyparsing to write a lua parser."

I actually got fairly far in converting that BNF to pyparsing, and I think if I can finish that up (after converting the left-recursive portion to a pyparsing-supported form), it will make for a good addition to the pyparsing examples.  Thanks for the suggestion!

**Comment by yldiscover** [comment]
It is a good news to know that it is possible to fully parse lua program, that would be a great job!

**Comment by ptmcg** [comment]
There will be a prototype lua parser in the next alpha release of 3.0.0 - you can see it now on GitHub: https://github.com/pyparsing/pyparsing/blob/master/examples/lua_parser.py

**Comment by ptmcg** [comment]
Released in 3.0.0a2

**Comment by yldiscover** [comment]
Hi,
   Thanks for your work.
   The Lua_parser example can run,but it seems that it needs to be optimized more. For example, it can not handle this lua script,which is modified from the original example:

function test(x)
        local t = {foo=1, bar=2, arg=x}
        n = 0
        if t > 2 then
            n = n + 1
        end
    end

 The lua_parser.py can not parse this script correctly.
 
 By the way, why 3.0.0a2 can not be built with python 2.7?

 Thanks!
  

> 
> 
> There will be a prototype lua parser in the next alpha release of 3.0.0 - you can see it now on GitHub: https://github.com/pyparsing/pyparsing/blob/master/examples/lua_parser.py
