### ISSUE TITLE
parseAll=True ignores trailing spaces even with .leaveWhitespace()

### ISSUE THREAD

**Issue by avm19** [pyparsing/pyparsing#221]
I believe it is justified to expect an error in the following code:
``` python
import pyparsing as pp #Tested with the up-to-date version '3.0.0a2'
parser = pp.Literal('\n').leaveWhitespace()
parser.parseString('\n ', parseAll=True)
```
Instead of raising an exception, the result of the above is surprisingly `(['\n'], {})`.

[This ](https://github.com/pyparsing/pyparsing/blob/1181390886f39240a98977348bd5b9030986f98d/pyparsing/core.py#L807-L810) bit of code (which checks for StringEnd `if parseAll`) seems to cause the problem by disregarding the `leaveWhitespace` setting. I am not confident about the purpose of this code and the `Empty() +` trick, therefore, I won't be committing a fix.

**Comment by ptmcg** [comment]
`expr.leaveWhitespace()` indicates that whitespace should not be skipped *before* matching the expression, not after. Here is your parser run using `runTests()` (which uses `parseAll=True` internally) (an alternate equivalent parser is shown using `LineEnd`):

```
print("\nusing Literal('\\n').leaveWhitespace()")
parser = pp.Literal('\n').leaveWhitespace()
#~ parser.parseString('\n ', parseAll=True)
tests = [
    '\n ',
    ' \n',
]
parser.runTests(tests)

print("\nusing LineEnd().leaveWhitespace()")
parser = pp.LineEnd().leaveWhitespace()
parser.runTests(tests)
```
Output:
```
using Literal('\n').leaveWhitespace()


 
['\n']

 

 
^
FAIL: Expected "
", found ' '  (at char 0), (line:1, col:1)

using LineEnd().leaveWhitespace()



['\n']


 
^
FAIL: Expected end of line, found ' '  (at char 0), (line:1, col:1)
```

To get the behavior you want, you need to revisit how this was done before the parseAll option was added: explicitly add `StringEnd` to your grammar. And since you want to fail in the presence of trailing whitespace, then you'll need to add `StringEnd.leaveWhitespace()`:

```
print("\nusing LineEnd().leaveWhitespace() + StringEnd().leaveWhitespace()")
parser = pp.Literal('\n').leaveWhitespace() + pp.StringEnd().leaveWhitespace()
parser.runTests(tests)
```
will fail both tests:
```
using LineEnd().leaveWhitespace() + StringEnd().leaveWhitespace()


 
 
^
FAIL: Expected end of text, found ' '  (at char 1), (line:2, col:1)

 

 
^
FAIL: Expected "
", found ' '  (at char 0), (line:1, col:1)
```

**Comment by avm19** [comment]
Thanks for your response. I see that `ParserElement.parseString()` docstring [says ](https://github.com/pyparsing/pyparsing/blob/17aaf616a752990327ec51f41d2ac4c4a0871215/pyparsing/core.py#L765-L766)precisely:
```
        If the input string is required to match the entire grammar, ``parseAll`` flag must be set to ``True``. This
        is also equivalent to ending the grammar with ``StringEnd()``.
```
Yet it may seem counter-intuitive that `StringEnd()` is skipping whitespaces by default.

**Comment by ptmcg** [comment]
No new activity in this area, so I'll close for now. Please reopen or open a new issue if you have additional questions.
