### ISSUE TITLE
Halfwidth katakana

### ISSUE THREAD

**Issue by JeroenKools** [pyparsing/pyparsing#227]
The pyparsing_unicode.Japanese class currently doesn't include the [halfwidth katakana characters](https://www.unicode.org/charts/PDF/UFF00.pdf). I found that these are in fact being used in actual CJK documents.

Please consider adding the character range (0xff01, 0xffef) to the katakana unicode_set class to address this.

**Comment by ptmcg** [comment]
In that linked document, not all the characters in that range are Katakana - some are Latin/Western, some are Hangul/Korean, others unattributed. But I'm happy to add these characters to their respective language groups.

In the meantime, you can reference them self using `pp.srange("[\uff0f-\uffef]")`.

I'll make this change in the next 3.0.0 alpha release.

**Comment by ptmcg** [comment]
Released in 3.0.0a2
