### ISSUE TITLE
Some question about the Lua_parser example.

### ISSUE THREAD

**Issue by yldiscover** [pyparsing/pyparsing#232]
Hi,
The Lua_parser example can run,but it seems that it needs to be optimized more. For example, it can not handle this lua script,which is modified from the original example:

function test(x)
local t = {foo=1, bar=2, arg=x}
n = 0
if t > 2 then
n = n + 1
end
end

The lua_parser.py can not parse this script correctly.

By the way, why 3.0.0a2 can not be built with python 2.7?

Thanks!

**Comment by ptmcg** [comment]
(answer from separate email)

It’s not about optimization. The lua parser currently in github is incomplete. I’ll post an update shortly that will include parsing for the associative array expression in your `local t` assignment.
 
As for working with Python 2.7, Python 2.7 is no longer a supported Python version. I have maintained Py2 compatibility in pyparsing for many years, but now it is time to move on to Python 3.  You can still run pyparsing 2.4.7 on Py2.7.  But the hundreds of lines of Py2-compatibility code have been removed in pyparsing 3.0.0, so it will only work with Python 3.
 
(I don’t think the lua parser in particular uses any Py3-specific features, nor any 3.0.0a2-specific pyparsing features. So you should be able to take the lua_parser.py file and run it on Py2.7 using pyparsing 2.4.7.)
