### ISSUE TITLE
Inconsistent tokens in parse action

### ISSUE THREAD

**Issue by jgrey4296** [pyparsing/pyparsing#237]
Using PyParsing 2.4.7, I have the following situation:

In a Parse Action, I get a named result:
```
def my_parse_action(toks):
   # [0] to strip away wrapping ParseResults
   result = toks['num'][0]
   assert(isinstance(result, tuple))
   return something
```
If I import that module, the parser works fine.
If I import that module, using `importlib`, the parser works fine.
If I import that module, `<<`'ing the parser into a `Forward`, the parser works fine.
If I import that module in a `unittest` discovered file, the parser works fine.

*However*: If I do some un-simplifiable combination of these... the `toks['num']` in the parse action is *no longer a `ParseResults` itself*. 

The `toks['num']` in question is built by another parser, works fine, and I return an explicit `ParseResults(tuple)` from it.
If I *don't* return a `ParseResults` from that action, instead just returning a tuple... The entire above situation inverts, the `toks['num']` being a ParseResults *only* when the hard to identify conditions occur.

The only thing that resolves the issue is using the base parser on its own, *before* I use the parser which uses the `Forward` that has the base parser assigned to it.
This sounds like some sort of caching issue or lazy loading. Calling `importlib.invalidate_cache` does not resolve the issue.

**Comment by ptmcg** [comment]
Generally, parse actions should return values only if they are really doing a transformation of some kind. If they are just modifying the results in place, then they don't need to return anything.  If the parse action takes a `toks` argument, there is no need to end with `return toks`. Doing so actually caused some bugs in older versions of pyparsing, was addressed in version 2.3 (there are more notes in the CHANGES log about this).

When you say "The toks['num'] in question is built by another parser", I wonder if you may be seeing multiple versions of pyparsing here. Some packages vendor their own version, and don't keep up with newer pyparsing versions. For instance, I think conda is still at 2.2.0.

As an aside, you might try changing your parse action to using `addCondition` instead:

    expr_that_should_emit_tuple.addCondition(lambda toks: isinstance(toks[0], tuple))

`addCondition` takes a predicate function (that just returns True or False), and wraps that in a parse action that will raise a ParseException if False, else be just a passthrough if True.  You could also make this the first of several parse actions:

    expr_that_might_emit_tuple.addParseAction(conditionAsParseAction(lambda toks: isinstance(toks[0], tuple)),
                                              another_parse_action_that_uses_tuple_but_no_longer_needs_to_validate_type)
   
In this case, the second parse action won't even get called unless the first one (converted from a simple predicate to a parse action) succeeds.

**Comment by jgrey4296** [comment]
Found it. I had refactored a `Forward` out of an `or` that I had set the ResultsName of, and so started to name a Forward that was empty at time of naming.
The behaviour and complaints made sense once I found that.
Thanks for the heads up about `addCondition`. 


```
top_forward = pp.Forward() # .setResultsName("top_forward")
top_or = pp.Or([pp.Word("aweg"), top_forward]).setResultsName("top_or")

bottom_word = pp.Word("bloo").setResultsName("bloo")
bottom_word.setParseAction(lambda toks: (toks["bloo"], toks["bloo"]))

top_forward << bottom_word

# Bang or not Bang based on the comment on line 1
top_or.parseString("bloo")
```

**Comment by ptmcg** [comment]
Glad you found it!  Pyparsing3 will have some added `__diag__` options, one of which is intended to catch this problem. I'm still trying to visualize just how these switches will logically get used as part of a parser development workflow using pyparsing, but they will at least be another tool in the toolkit.

**Comment by jgrey4296** [comment]
Is there a reason `Forward` doesn't just error if you try to name it when it's empty?

Also, my issues generally come down to finding the semantics of what modifies versus what copies and changes the copy hard to pin down.

**Comment by ptmcg** [comment]
The hardest one to remember (until you get used to it) is that `setResultsName` makes a copy. This is necessary since a basic, low-level expression like `Word(nums)` or `Word(alphas)` might be used multiple places in a grammar, with different results names - so it has to make a copy of the base expression in each of the different named places. One reason why I prefer the constructor-looking `expr("name")` form over `expr.setResultsName("name")` form.

It is unfortunate that a "set..." method is actually a "copy-and-set..." method, but it is what it is.
