### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by TMiguelT** [pyparsing/pyparsing#238]
Hi @ptmcg, just wondering the preferred way to cite PyParsing. Should I cite your book:
McGuire, P. (2007). Getting started with pyparsing. " O'Reilly Media, Inc."

If yes, I wonder if this info should be somewhere in the readme or the docs?

**Comment by ptmcg** [comment]
For a bibliography, citing the book is okay, but it is not available any longer so it's not really a good reference for people to follow. If you want to cite a live link, you can link to the repo or the readthedocs link https://pyparsing-docs.readthedocs.io/en/latest/index.html

**Comment by TMiguelT** [comment]
Ah yes well the journal in question only actually allows me to cite "published" content so the book is the only option. Your book is mostly acting as a target for citations, it's not because I specifically want to direct people there. You have been cited by some interesting research, for what it's worth: https://scholar.google.com/scholar?cites=2033986313199696846

**Comment by ptmcg** [comment]
I mention my favorite on the home page of the wiki, and just recently learned of the Allstate Insurance research that used pyparsing to extract about a megabyte of data from the PDF of their submitted premium structure to the Maryland state insurance board. Thanks for the link, I'll see what else is out there.

**Comment by TMiguelT** [comment]
Wow, those are incredible, I didn't know about the wiki. Still, you might not have seen some of these academic uses!

Anyway, it sounds like using the book is still reasonable for academic citations, even if it's not really up-to-date. It's quite normal to cite an old publication in academia as the canonical citation for a certain piece of software.
