### ISSUE TITLE
How to get the delimiter of delimitedList?

### ISSUE THREAD

**Issue by yldiscover** [pyparsing/pyparsing#240]
Hi,
  When using delimitedList(x,delim=Word('+-')) to match a pattern,like  a + b - c, where the '+-' is the delimiter.
  But delimitedList only return a b c, not returning the delimiter.
  So, how to get the delimiter of delimitedList?

**Comment by ptmcg** [comment]
If you want the delimiters, don't use `delimitedList`. If the list separators are significant, then they are more than just mere delimiters. To keep the operators, use `x + (operator + x)[...]` where `operator` is probably more correctly defined as `operator = oneOf("+ -")`.  `Word('+-')` will match "++-+---", not just "+" or "-". You *could* do `Word('+-', exact=1)`, or `Char('+-')`, both of which will only parse a single character.

**Comment by yldiscover** [comment]
Thank you, this is a good solution!
