### ISSUE TITLE
module 'string' has no attribute 'ascii_uppercase'

### ISSUE THREAD

**Issue by pingdink** [pyparsing/pyparsing#242]
![Screen Shot 2020-09-10 at 12 15 39 PM](https://user-images.githubusercontent.com/9258889/92779599-6cbd2800-f35f-11ea-90a4-5eeff84d125a.png)

**Comment by ptmcg** [comment]
https://docs.python.org/3/library/string.html#string.ascii_uppercase

Do you have a file in your PYTHONPATH named string.py that may be getting imported instead of the one in the stdlib?

**Comment by pingdink** [comment]
thank you

**Comment by ptmcg** [comment]
No problem, I think everybody does this at least once while learning Python.

You had me a little panicked, glad it was something easy!

Good luck with pyparsing!
