### ISSUE TITLE
Unrelated dblQuotedString has influence on the match location

### ISSUE THREAD

**Issue by FrankGoyens** [pyparsing/pyparsing#244]
I have the following python program:

    from pyparsing import *

    #grammar START
    string_list_item = dblQuotedString | Word(printables.replace(')', ''))
    cmake_list_content = OneOrMore(string_list_item)

    variable_name = Word(alphas+"_", alphanums+"_")

    set_keyword = CaselessLiteral("set")

    set_normal_variable_stmt = set_keyword + "(" \
        + variable_name \
            + cmake_list_content + ")" 
    #grammar END

    cmake_source = "set(TabsPls_Sources Main.cpp)"

    string_list_item.setDebug()

    set_normal_variable_stmt.parseString(cmake_source)

This gives the following output for 'Main.cpp':

    Match {string enclosed in double quotes | W:(0123...)} at loc 19(1,20)
    Matched {string enclosed in double quotes | W:(0123...)} -> ['Main.cpp']

But when I remove the dblQuotedString from the first line:

    Match W:(0123...) at loc 20(1,21)
    Matched W:(0123...) -> ['Main.cpp']

Why does that happen? There aren't any double quoted strings in the input so why does the match location change?

**Comment by ptmcg** [comment]
The issue has to do not with `dblQuotedString`, but with `MatchFirst` and its variation of skipping whitespace. If you were to replace `dblQuotedString` with a `NoMatch()`, you would get the same behavior. Or increase the number of spaces before "Main.cpp" and you'll see a bigger discrepancy.

Looks like a bug, thanks for providing a short simple example to reproduce it.

**Comment by FrankGoyens** [comment]
No problem, thanks for the feedback @ptmcg. 

If anyone else runs into this, as a workaround I explicitly define `White`:

    #snip
    cmake_list_content = OneOrMore(string_list_item + White()) + Optional(string_list_item)
    #snip
    set_normal_variable_stmt = set_keyword + "(" \
        + variable_name + White() \
            + cmake_list_content + ")" 
    #grammar END

It's a workaround so mileage may vary.

**Comment by ptmcg** [comment]
Sorry I took so long to get around to this. While debugging, I added some more verbose debug output and I liked how it looked so I left it in. You can see an example in the updated CHANGES file.

**Comment by FrankGoyens** [comment]
No problem!
The locations are consistent now. The original code for which I made the simplified example still works after removing my workaround, which is nice. The new debug output looks good to me as well.

**Comment by ptmcg** [comment]
Released in 3.0.0b1
