### ISSUE TITLE
select_parser.py: column not recognized in function

### ISSUE THREAD

**Issue by legrandlegrand** [pyparsing/pyparsing#245]
Hello,

```
select nvl(a,5) from t
['SELECT', [['nvl', ['a'], 5]], 'FROM', ['t']]
- columns: [['nvl', ['a'], 5]]
  [0]:
    ['nvl', ['a'], 5]
    - col: 'nvl'
- from: [['t']]
  [0]:
    ['t']
    - table: [['t']]
      [0]:
        ['t']

```
gives     **col: 'nvl'**
but:

```
select 1 from T where nvl(a,5)=2
['SELECT', [[1]], 'FROM', ['t'], 'WHERE', ['nvl', ['a'], 5, '=', 2]]
- columns: [[1]]
  [0]:
    [1]
    - col: 1
- from: [['t']]
  [0]:
    ['t']
    - table: [['t']]
      [0]:
        ['t']
- where_expr: ['nvl', ['a'], 5, '=', 2]
  [0]:
    nvl
  [1]:
    ['a']
    - col: ['a']
  [2]:
    5
  [3]:
    =
  [4]:
    2
```

gives **col: ['a']** that seems correct

**Comment by legrandlegrand** [comment]
I dived into the code and started to understand things

first:
label "col" is used for two distinct purposes:
- for column identifier
- for projected expression in select
so I renamed the later into "proj_expr"

second:
to be able to continue to display the function details I add a Group for
    function_name.setName("function_name")
    + LPAR
    + Optional(STAR | Optional(DISTINCT) + delimitedList(expr))
    + RPAR

this gives me:

select nvl(a,5) from t
['SELECT', [[['nvl', ['a'], 5]]], 'FROM', ['t']]
- columns: [[['nvl', ['a'], 5]]]
  [0]:
    [['nvl', ['a'], 5]]
    - proj_expr: ['nvl', ['a'], 5]
      [0]:
        nvl
      [1]:
        ['a']
        - col: ['a']
      [2]:
        5
- from: [['t']]
  [0]:
    ['t']
    - table: [['t']]
      [0]:
        ['t']

and I'm happy ;o)
thanks for this great tool !

**Comment by ptmcg** [comment]
I'll look at this, and can make the corresponding changes in the example. Glad you were able to work it ou!
