### ISSUE TITLE
Rename the Restructured files

### ISSUE THREAD

**Issue by viraptor** [pyparsing/pyparsing#25]
Could you rename `https://github.com/pyparsing/pyparsing/blob/master/HowToUsePyparsing.txt` to `.rst`? That way it will render on github and can be read a bit easier.

**Comment by ptmcg** [comment]
I have renamed the file, but the content is pretty dated. The sample code in the module, class, and method docstrings are much more current. You can also view this help at the online site https://pythonhosted.org/pyparsing/pyparsing-module.html .  Probably best if I at least drop in that link that how-to file.

**Comment by viraptor** [comment]
Great, thanks!

**Comment by ptmcg** [comment]
Done with this for now, thanks for the suggestions
