### ISSUE TITLE
Missing a way to extract a value of a regex group

### ISSUE THREAD

**Issue by Hi-Angel** [pyparsing/pyparsing#252]
While pyparsing has an impressive library of helper classes, but for one-time parsing tasks *([e.g. code-refactoring](https://softwarerecs.stackexchange.com/q/77072/21701#python-module-to-search-for-multiline-pattern-in-text))* it is often more convenient to code large parser chunks in regexes, as they're terser and a common knowledge. I admit, they may not be readable. But myself, for example, never had to write a parser to maintain it later — I usually write a throw-away one to refactor a codebase, and never look back at it.

So it would be very useful if there was a way to extract a match and a location from a `Regex` group. As far as I read documentation and autocompletions from a `ParseResults` object, there does not seem to be a way to do it.

## Steps to reproduce

```
 λ cat test2.py
#!/usr/bin/python

from pyparsing import Regex, Word, alphanums

text = '''
string1 = "foo"
string2 = "bar"
'''

StringRegex = Regex('"(.*)"')
StringRegex.setParseAction(lambda locn,tokens: (locn,tokens))
r = Word(alphanums) + '=' + StringRegex
print(list(r.scanString(text)))
 λ python test2.py
[((['string1', '=', (11, (['"foo"'], {}))], {}), 1, 16), ((['string2', '=', (27, (['"bar"'], {}))], {}), 17, 32)]
```

### Expected

Either the output has locations of the `foo` and `bar` groups, i.e. excluding double-quotes, or there is a way to extract their positions for the corresponding `ParseResults` objects.

### Actual

The output only has locations for `"bar"` and `"for"` including double-quotes, and there's no way to extract content/position of the group from the corresponding `ParseResults` objects.

**Comment by Hi-Angel** [comment]
> I admit, they may not be readable. But myself, for example, never had to write a parser to maintain it later

On a semi-relevant note: actually, I just figured, in pyparsing case it might be easier to maintain a `Regex` compared to token-classes, like `Word`, `Char`, etc. The reason is: if I have a `token1 + token2 + token3`, each of them will take `0`, `1`, `2` positions in `scanString` output. Then, if I add a `tokenX` in the beginning, positions of all tokens will change by one, forcing the developer to search all places in code that referred those positions.

Such problem doesn't exist with pure regexes, because you explicitly group patterns you're interested in, and adding yet another token won't change indices of those groups.

**Comment by ptmcg** [comment]
Very true. This is why a recommend using results names for your expressions.

    token1("first_name") + token2("middle_name") + token3("last_name")

The parsed tokens can then be referenced by name instead of by position.

**Comment by Hi-Angel** [comment]
Thank you! To future readers, named tokens are mentioned in `1.1.2   Usage notes` paragraph. Basically, one creates a token like `w = Word(alphanums)('myid')` and then uses them on `scanString` results at third depth-level, as in `ret[0][0]['myid']`

**Comment by ptmcg** [comment]
Named groups in Regex expressions are also preserved as results names. 
```
>>> date = Regex(r'(?P<year>\d{4})-(?P<month>\d\d?)-(?P<day>\d\d?)')
>>> print(repr(date.parseString("2021-04-01")))
```
prints
```
(['2021-04-01'], {'year': ['2021'], 'month': ['04'], 'day': ['01']})
```
