### ISSUE TITLE
Missing ParseResults state from prints

### ISSUE THREAD

**Issue by Hi-Angel** [pyparsing/pyparsing#254]
It may arguably not be a bug, but I thought it's worth at least reporting, because for new people it leads to lots confusion and frustration. The problem is as follows: given a `ParseResults` object, if you try to print it, you will only get the text it matched, enclosed in singular quotes and square brackets. Because of those square brackets it doesn't look like pure match results, instead it looks as if the object has no other state besides the text matched. As in, no `locn_start/end`, no object ID if it was named, etc. The number of square brackets btw may multiply depending on configuration, so it certainly looks like the whole state the object has.

## Steps to reproduce

```python
 λ cat test2.py
from pyparsing import Regex, ParserElement

ParserElement.setDefaultWhitespaceChars('')
empty_init = Regex('\n\s+def __init__\(self\):\n\s+pass\s*\n')

text = '''
class MyClass:
    def __init__(self):
        pass
'''

def parse(text):
    r = empty_init('empty_init')
    return [match for match in r.scanString(text)]

if __name__ == "__main__":
    matches = parse(text)
    for m in reversed(matches):
        print(f"m[0] is: {m[0]}\n")
        print(f"Apparently m[0]['empty_init'] doesn't exist… Oh wait, let's try it: \n{m[0]['empty_init']}")
 λ python test2.py
m[0] is: ['\n    def __init__(self):\n        pass\n']

Apparently m[0]['empty_init'] doesn't exist… Oh wait, let's try it:

    def __init__(self):
        pass
```

### Expected

First print has the state *(the `'empty_init''` name)* that we access in the second one

### Actual

First print doesn't have the state that we access in the second one

## Known workarounds

1. call `print(obj.dump())`
2. debug patterns inside python interactive shell *(result of evaulation of an object there shows all state)*

**Comment by Hi-Angel** [comment]
FWIW, this is especially a problem when you're trying to figure out where could I get `locn_start` for example. In my other code when I print `m[0]['empty_init']` I get no `locn_start`, as if location is missing, however if I blindly do `m[0]['empty_init']['locn_start']` it succeeds.

**Comment by ptmcg** [comment]
I simplified the `str()` output for `ParseResults` because I got so many requests from those who thought that the output was a tuple containing a list and a dict. So the `str()` output now just shows the results as a list. To see the full content, you can use `.dump()` as shown in your post, or use the `repr()` output. In f-strings, this is easily done by adding `!r`:
```
        print(f"m[0] is: {m[0]!r}\n")
```
which will print:
```
m[0] is: (['\n    def __init__(self):\n        pass\n'], {'empty_init': ['\n    def __init__(self):\n        pass\n']})

Apparently m[0]['empty_init'] doesn't exist Oh wait, let's try it: 

    def __init__(self):
        pass
```

**Comment by Hi-Angel** [comment]
Amazing, thank you!
