### ISSUE TITLE
 infixNotation() might be made better 

### ISSUE THREAD

**Issue by klahnakoski** [pyparsing/pyparsing#26]
I am going through the match attempts for my parser moz-sql-parser while parsing

    select * from task where build.product is not null and build.product!='firefox'

The parser does a lot of trackback as it tries to match the WHERE clause; much more than it should. Please change infixNotation() to take advantage of the fact that clusters of infix binary operators always begin with an operand, alternate operator and operand, and end with an operand:

    [build.product] is [not null] and [build.product] != ['firefox']

(you may notice my grammar did not include not as a unary operator to infixNotation())

By matching this alternating pattern the matching process can go much faster. Precedence is handled with some post processing to organize this into a tree. Of course, the difficultly will be splitting up a single infixNotation() call, infected with unary and trinary operators, into a hierarchy of infixNotation() calls containing only binary operators.

Thank you

**Comment by ptmcg** [comment]
I don't think you need a modified version of `infixNotation`. If all you want to do is parse the where expression into a structure of comparisons and AND's and OR's and deal with precedence of operations yourself, then you just need a simple expression using `ZeroOrMore`:

```
- comparison_expr = pp.Group(ident
-                            + ((IS + NULL).setParseAction(' '.join)
-                               | (IS + NOT + NULL).setParseAction(' '.join)
-                               | comparison_oper + rvalue))
- 
- where_expr = (WHERE + comparison_expr 
-                     + pp.ZeroOrMore((AND | OR) + comparison_expr))
- ```

With this test code:
```
tests = """\
     where build.product is not null
     where build.product!='firefox'
     where build.product is not null and build.product!='firefox'
""".splitlines()

where_expr.runTests(tests)
```
I get this output:

```
     where build.product is not null
['where', ['build.product', 'is not null']]
[0]:
  where
[1]:
  ['build.product', 'is not null']

     where build.product!='firefox'
['where', ['build.product', '!=', "'firefox'"]]
[0]:
  where
[1]:
  ['build.product', '!=', "'firefox'"]

     where build.product is not null and build.product!='firefox'
['where', ['build.product', 'is not null'], 'and', ['build.product', '!=', "'firefox'"]]
[0]:
  where
[1]:
  ['build.product', 'is not null']
[2]:
  and
[3]:
  ['build.product', '!=', "'firefox'"]

```

**Comment by klahnakoski** [comment]
Thank you!  I *think* you just showed me how `infixNotation` could use `ZeroOrMore` to be faster.  Maybe I will write it, and submit a PR.  But, do not hold your breath.  😄

**Comment by ptmcg** [comment]
I'll let you take this from here - open a new ticket or PR if you have other questions or suggestions.
