### ISSUE TITLE
examples/sql2dot.py typo in STUDENT table name

### ISSUE THREAD

**Issue by legrandlegrand** [pyparsing/pyparsing#261]
![STUDENT](https://user-images.githubusercontent.com/10522659/103696910-6eaa9700-4f9f-11eb-8fb1-e01eea30606d.png)

comes from line 11:
`create table student
(
`
changing student into students gives
![STUDENTS](https://user-images.githubusercontent.com/10522659/103697591-6a32ae00-4fa0-11eb-9af0-855dfe9f83fe.png)

**Comment by ptmcg** [comment]
Dead on, thanks!

**Comment by ptmcg** [comment]
Pushed out in 3.0.0b3.
