### ISSUE TITLE
QuotedString's escQuote parameter does not work unless it is a double char

### ISSUE THREAD

**Issue by MrHen** [pyparsing/pyparsing#263]
Using pyparsing-2.4.7:

```python
>>> from pyparsing import QuotedString
>>> quoted = QuotedString(quoteChar="\"", escChar=None, escQuote="\\\"")
>>> quoted.parseString('"abc"')
(['abc'], {})
>>> quoted.parseString('"abc \"def\""')
(['abc '], {})
```

I am expecting the second example to return the entire string. A slightly easier case to read:

```
>>> quoted = QuotedString(quoteChar="y", escChar=None, escQuote="xy")
>>> quoted.parseString('yaaay')
(['aaa'], {})
quoted.parseString('yaaaxyaaay')
>>> quoted.parseString('yaaaxyaaay')
(['aaax'], {})
```

Compare both of the above with the use of a double:

```
>>> quoted = QuotedString(quoteChar="y", escChar=None, escQuote="yy")
>>> quoted.parseString('yaaay')
(['aaa'], {})
quoted.parseString('yaaayyaaay')
>>> quoted.parseString('yaaayyaaay')
(['aaayaaa'], {})
```

----

Looking at the [code](https://github.com/pyparsing/pyparsing/blob/f10fcf8c98ea07a63f8286288ce82f773e7e152e/pyparsing/core.py#L2636), the reason appears to be regex fun:

```
>>> quoted = QuotedString(quoteChar="y", escChar=None, escQuote="xy")
>>> quoted.pattern
'y(?:[^y\\n\\r]|(?:xy))*y'
```

This regex will not match `yaaaxyaaay`: https://regexr.com/5km7f

**Comment by ptmcg** [comment]
Thanks for the example and the link, it looks like if I put the escapes first in the re, your test case works:

    y(?:(?:xy)|[^y\\n\\r])*y

Now I just need to wrangle this back into pyparsing's regex creation code.

**Comment by ptmcg** [comment]
Wow, that *was* a bit of regex cleanup, but well worth it!

Fixed in the next release.

**Comment by ptmcg** [comment]
Pushed out in 3.0.0rc1.
