### ISSUE TITLE
Railroad diagram import error

### ISSUE THREAD

**Issue by ralienpp** [pyparsing/pyparsing#264]
I am attempting to leverage the railroad diagram generation functionality in order to better understand the chaos I've created and debug my parser :-)

Following the example of the documentation, I get an import error at the very beginning. Here is an excerpt from an interactive session that illustrates the problem with `pyparsing 2.4.7`:

```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
>>> from pyparsing.diagram import to_railroad, railroad_to_html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyparsing.diagram'; 'pyparsing' is not a package
>>> 
```

What is the correct way to import it?

**Comment by ptmcg** [comment]
You'll need to install the 3.0 version of pyparsing to get the railroad diagramming feature. If you create a separate virtualenv, you can pip install it from GitHub using: `python -m pip install -e "git+https://github.com/pyparsing/pyparsing.git@pyparsing_3.0.0b2#egg=pyparsing"
`
This latest release (requires Python 3.6 or later) includes a simplified method to create a railroad diagram:

    my_expr.create_diagram("diag.html")

(Sorry, this method is not well documented, I'll put out a b3 release that makes it cleaner/clearer.)

I'll be very interested to hear about your experience with these diagrams!

**Comment by ralienpp** [comment]
Thank you for the hint - this did the trick. My experience with using `pyparsing` diargams so far:

## Motivation
- To have a **debugging aid** that guides me through the development of my DSL. My intention was to rebuild the diagram every time I alter the grammar, and observe how it grows from "nothing" into my final product. Because I am new to `pyparsing` I am not yet fully aware of the implications of everything that I'm doing, or to be more accurate - I think I know what I'm doing, but I am not confident that I have full awareness of potential side effects. So my guess was that I could leverage the diagram - noticing any unusual arrows would instantly tell me that something is odd, forcing me to reconsider my last action.
- To produce **documentation**, a cheatsheet for my [non-techie] colleagues who will be using the DSL, but also for my future self.

## Results
So far the impressions are very positive. The default aesthetics are nice, in my opinion, and I already got some value out of the result - seeing so many "unnamed" labels indicates that I haven't annotated everything.

However, I think that the raw output is not suitable for use as documentation to be shared with "unsuspecting civilians", because it contains some `pyparsing`-specific metadata that an end-user won't need. This brings me to the following recommendations:
1. Add a parameter that allows me to remove the "suppress" annotation. I need it when I debug my `pyparsing` logic itself, but the end-user who writes in my DSL doesn't need to know it:
![image](https://user-images.githubusercontent.com/295338/105815438-2e916f80-5fb3-11eb-85a0-46a6e0992adc.png)
2. Make it possible to remove the quotes from certain characters, like in the screenshot above, you see `'='`, and the end-user might think they have to type `'='`, whereas in fact they only need to type `=`.
3. Add a bit of chromatic differentiation for "hardcoded constants" and "variable data". In the illustration above, the `=` is always there and you must type it "as is", whereas the other two elements are up to you, so I'd render them in a different colour, for example - yellow (or a different shade of green). This way, the end-user knows where they can get creative, and where they must follow the instructions; it is a simple heuristic like "green = write what I see, yellow = think".

Currently this differentiation is done by adding quotes (see point#2), but a non-expert user might think that the quotes are supposed to be there too.


## Other observations
A part of my output looks like this (note the duplication of `target`):
![image](https://user-images.githubusercontent.com/295338/105816918-33efb980-5fb5-11eb-9509-b792c423cd2d.png)

This was a surprise, because the code actually looks like this:
```
# an identifier of a node name, e.g. `n1`
NODE = Word(alphanums)

goto = Literal('goto').setResultsName('verb') + Optional(NODE.setName('source') + ARROW) \
         + NODE.setName('target') + Optional(BASE) \
         + Optional(Group(delimitedList(node_action))).setResultsName('actions')
```


I thought that `pyparsing` would follow some sort of a "copy-on-write" logic, but the chart tells me otherwise, the `NODE` object is the same, so if I want the labels to be "source" and "target" I actually need to create two different items. This is the kind of a "gotcha" I referred to, when I wrote that I have no full awareness of everything that I am doing.

**Comment by ralienpp** [comment]
This is what I created by "massaging" the output into a form that is suitable for documentation. The result is much more compact and it will look nice on a laminated A5 sheet, maybe even A6:
![image](https://user-images.githubusercontent.com/295338/105835951-d6fffd80-5fcc-11eb-8e01-bb01d80c87d4.png)


The method I followed to get to this:
- first I looked at the code and noticed the `vertical` parameter, but after tinkering for a while it didn't give me what I wanted
- so I then used `pyparsing` to export individual "sub-grammars", as opposed to the whole thing at once (the very wide diagram shown in my previous message)
- manually move them into a single file, then place them one under another and edit the arrows
- remove the "suppress" annotation
- change the colours
- simplifying some of the logic
- manually editing the labels, remove the quotation marks

So, what `pyparsing` gave me was good input material that I should further polish. Here are some additional observations I made during the process:

1. Simplified notation for comma-delimited lists, they are semantically the same (unless I overlook something), but the lower form is less cluttered:
![image](https://user-images.githubusercontent.com/295338/105836671-cf8d2400-5fcd-11eb-857f-0220f7a0208b.png)

2. I cheated a bit in the `init` part of the diagram, writing `X` and `Y` instead of including a sub-diagram for floating point notation. The domain knowledge the end-user possesses makes it obvious what x/y stands for. Perhaps `pyparsing` could add another method, such as `setLabel("bla")` that one could call to override what is written inside the graphical element. For example, in the green part of "base" on top, I would rather write "number > 1" instead of "W: (1-9)" or "number". This happened automagically with "node action" to its right because I did `setName('node action')`, but the same trick didn't work with the notation of the "base" element.


I hope you find my feedback useful. My requirements are probably a bit different from the initial plan behind this feature, as it is not oriented at programmers, but rather non-experts who are trained to use a DSL. Pyparsing has greatly simplified my task and the diagrams are a nice cherry on top; it took only a little extra effort to manually bring them to shape I wanted.

**Comment by ptmcg** [comment]
Thanks for the detailed notes!!! I'll look at them this weekend.

(Glad to hear pyparsing helped you in your DSL endeavors. Let me know if you make your project public, I'll add you to the "Who's Using Pyparsing" list.)

**Comment by multimeric** [comment]
Hi @ralienpp. I wrote this feature so it was interesting for me to have a read of your notes.

> Add a parameter that allows me to remove the "suppress" annotation. I need it when I debug my pyparsing logic itself, but the end-user who writes in my DSL doesn't need to know it:

Agreed. While I want it to still be a possibility, users certainly don't need to know about `suppress`.

> Make it possible to remove the quotes from certain characters, like in the screenshot above, you see '=', and the end-user might think they have to type '=', whereas in fact they only need to type =.
> Add a bit of chromatic differentiation for "hardcoded constants" and "variable data".

What I did here is actually directly copying the `str` behaviour of Paul's internal classes. However, I'm liking your colour-based method, and the justification behind it enough that I think we should diverge from this behaviour, remove the quotes, and use (customisable) colours instead. 

> Some rules can be very intimidating to a non-expert user of the DSL

Agreed, this is an issue I noted before. But the question is what API to use to set this option. I guess we could just have a boolean parameter like `show_leaves = True` which, when set to `False` will not show the underlying token string at all, but will just replace it with the token's name instead.

> By default pyparsing produces a linear flow, so I get a very wide diagram. However, it would look much better if I could arrange these things vertically

There is actually already an option for this, it just doesn't show up in the documentation (@ptmcg can we add the `diagram` module to the Sphinx API docs?). Have a play with it and let me know what you think: https://github.com/pyparsing/pyparsing/blob/master/pyparsing/diagram/__init__.py#L103-L113

> A part of my output looks like this (note the duplication of target):

Hmm I think this might be a bug.

**Comment by ptmcg** [comment]
I added `vertical` to the `create_diagram` docstring in the latest release.

**Comment by multimeric** [comment]
Great, thanks! It's here, right? https://pyparsing-docs.readthedocs.io/en/latest/pyparsing.html#pyparsing.ParserElement.create_diagram

**Comment by ptmcg** [comment]
Yes, that's the one.

**Comment by ptmcg** [comment]
@ralienpp  just wanted to let you know that your issue has gotten a lot of attention these past couple of days, as I ready pyparsing for the 3.0.0c1 release candidate. I'm working with @multimeric to get things better aligned. 

The dashed line grouping notation is almost exclusively used for results names now. (No more Supress annotation, for instance.) The exceptions are for FollowedBy and NotAny, both of which are forms of lookahead, which railroad-diagrams doesn't seem to have a notation for. Also, these forms rarely get results names, so there should be little confusion.

The parser writer has much more control over how things get diagrammed based on where they put setName() calls - if something is setName()'ed, it will get its own separate diagram. If that is not desirable, remove the setName() call, or use setName(None) for those pyparsing constructs that automatically create names (such as delimitedList or countedArray).

I briefly looked into coloring specific nodes, but did not see any straightforward way to do this. Something we can look at for a future point release.

And lastly, thanks so much for trying out this new behavior, and this early release of pypparsing! The forecast looks good for FINALLY pushing out a pyparsing 3.0.0 release this month or early next.

**Comment by ptmcg** [comment]
Pushed out in 3.0.0rc1.
