### ISSUE TITLE
Is it possible to set custom error message for parsing element?

### ISSUE THREAD

**Issue by pokidovea** [pyparsing/pyparsing#266]
Now I have to show to my users inconvenient technical message such as `Expected W: (123...)`
Is there a way to apply custom error message for separate parsing element or group?

**Comment by ptmcg** [comment]
Use `setName` to give your expression a nicer-looking name here:

    word = Word(alphas).setName("alphabetic word")
    print(word.parseString("12345"))

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "C:\Python38\lib\site-packages\pyparsing.py", line 1955, in parseString
    raise exc
  File "C:\Python38\lib\site-packages\pyparsing.py", line 3250, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected alphabetic word, found '1'  (at char 0), (line:1, col:1)

```

Note that this is different from `setResultsName`, which tags the results parsed by that expression. Instead, `setName` sets a name on the expression itself.

I don't have a way to change the message format itself. But you *can* catch the ParseException in your own code, and then display whatever message you like.

**Comment by ptmcg** [comment]
Any further questions on this? If not, please close it out.
