### ISSUE TITLE
Provide a way to disable packrat caching

### ISSUE THREAD

**Issue by arekfu** [pyparsing/pyparsing#267]
I would like to have a `ParserElement.disablePackrat()` method to disable packrat caching. Different packages importing pyparsing within the same application may have different opinions about the usefulness of packrat caching. Currently, if any one of them calls `enablePackrat()`, all the other packages are stuck with it, with large performance losses in some cases.

The ideal solution would be to make it possible to choose whether to use packrat caching on a parser-by-parser basis, and not globally for the whole `pyparsing` package, but I understand that this may take a lot of refactoring.

**Comment by ptmcg** [comment]
Sadly, yes, this would be a big refactoring project.

You *can* pass an argument to `enablePackrat` to set the size of the cache (the default is 128), `None` to set an unbounded cache, or `0` to set effectively *no* cache. This might work for you.

**Comment by arekfu** [comment]
Thanks for looking into this. Looking at the code though it seems that setting `cache_size_limit=0` is not quite the same as having never called `enablePackrat()` in the first place. Maybe we could special-case `cache_size_limit=0` to set `self._parse` back to `self._parseNoCache`?

**Comment by maxfischer2781** [comment]
Since packrat does not play well with recursion (see #287), I've also pondered adding an off-switch for both. Would it be too much feature creep if I put such a switch in the recursion PR?

**Comment by ptmcg** [comment]
Not at all, it seems very closely related.

**Comment by ptmcg** [comment]
With the addition of left recursion support, there is now the new method `ParserElement.disable_memoization()`, released in 3.0.0b3
