### ISSUE TITLE
recursion depth issues

### ISSUE THREAD

**Issue by tim-mitchell** [pyparsing/pyparsing#27]
Hi

A customer reported a traceback to us with a maximum recursion depth exceeded error originating from pyparsing.  
The customer had entered an SQL where clause not dissimilar to the one in the attached script (that reproduces the issue).  
I am working around this by using sys.setrecursionlimit() which is unpleasant.
```python
with high_recursion_limit():
    tokens, start, end = where_clause.scanString(s).next()
```

"Don't write stupid queries" is a tempting answer - but it does not make the software more reliable.

[pyparsing_recursion.txt](https://github.com/pyparsing/pyparsing/files/2373409/pyparsing_recursion.txt)

**Comment by ptmcg** [comment]
The examples provided with pyparsing are there for educational purposes, not part of the core package. If they are used in production applications, it falls to the user to maintain them as needed for their particular instance.

That being said, there is a very simple fix to this problem - change this line in simpleSQL.py:

    whereExpression << whereCondition + ZeroOrMore( ( and_ | or_ ) + whereExpression ) 

to:

    whereExpression << whereCondition + ZeroOrMore( ( and_ | or_ ) + whereCondition ) 

I'll apply this change in the next release, but if you have made this code part of your application, you will need to manage it for yourself. There is no guarantee that any given example will be maintained from release to release, kept backward-compatible, updated for Python versions/features, etc.

**Comment by tim-mitchell** [comment]
@ptmcg Thanks for the prompt reply.
Have fixed my code. 🥇 
(which, 10 years ago,  was based largely on your example because that feature was my first exposure to grammer parsers)

**Comment by ptmcg** [comment]
I'm glad that worked for you, and that you are still able to read your code after 10 years!
