### ISSUE TITLE
It should be possible to build pyparsing without setuptools installed

### ISSUE THREAD

**Issue by jachymb** [pyparsing/pyparsing#270]
python setuptools attempt to import pyparsing. Therefore it should be possible to build pyparsing with setuptools uninstalled. Perhaps try something like this:

    try:
        from setuptools import setup
    except ImportError:
        from distutils.core import setup

**Comment by ptmcg** [comment]
This was how pyparsing formerly did this import, but was removed in this change b0310f8d52f8cb25ce3990e8130e1ed0250f20c1, see comments there.
