### ISSUE TITLE
How to mark EOF?

### ISSUE THREAD

**Issue by heckad** [pyparsing/pyparsing#273]
I want to check that module ends with EOF.
Grammer example
```
module = module_stmt* EOF
```
How to do this?

**Comment by ptmcg** [comment]
The pyparsing class StringEnd() can be used to detect EOF:
```
module = module_stmt[...] + StringEnd()
```

You can also use the `parseAll` argument to `parseString` (which internally uses a StringEnd just like the above):
```
module = module_stmt[...]
module_parts = module.parseString(module_source, parseAll=True)
```

**Comment by heckad** [comment]
@ptmcg, thank you very much!
