### ISSUE TITLE
Correction in ReadME.md

### ISSUE THREAD

**Issue by AkhileshThite** [pyparsing/pyparsing#275]
Need space before word "world" in the array right?
         👇🏻                               👇🏻
`Hello, World! -> ['Hello', ',', 'World', '!']`

I would like to contribute to pyparsing.

**Comment by ptmcg** [comment]
Thanks for writing. Have you tried the code in the example?  Here is what I get when I run it:
```
>>> from pyparsing import Word, alphas
>>> greet = Word(alphas) + "," + Word(alphas) + "!"
>>> hello = "Hello, World!"
>>> print(hello, "->", greet.parseString(hello))
Hello, World! -> ['Hello', ',', 'World', '!']
```

No extra spaces.

One of pyparsing's features (which is different from regular expressions) is that it will implicitly skip whitespace. So the expression `greet` is actually processed as if it were written:
```
>>> opt_ws = Optional(White()).suppress()
>>> greet = Word(alphas) + opt_ws + "," + opt_ws + Word(alphas) + opt_ws + "!"
```

Please work through some of the examples to get more familiar with how the module works, and Welcome to Pyparsing!

**Comment by AkhileshThite** [comment]
Okay got it! Thanks for the explanation :)
