### ISSUE TITLE
Parsing or ignoring parts of a string with unbalanced nested parentheses

### ISSUE THREAD

**Issue by Midnighter** [pyparsing/pyparsing#277]
I have a string of a specific format:

> #12,34# name (lorem (ipsum) <23>

I care mostly about parsing the first part `"#12,34# name"` and the last part `"<23>"` which I already have patterns for. The rest of the text which is inside the parentheses can have unbalanced nested parentheses inside. I would be happy to just capture the whole content of that. A greedy regex like `\(.+\)` would do the trick but I know that pyparsing does not backtrack. Is there another way that I can achieve this?

**Comment by ptmcg** [comment]
I think SkipTo would be the pyparsing equivalent for you. In recent versions of pyparsing, you can use a Python ellipsis (`...`) in place of SkipTo, which makes things look a little cleaner.

```
import pyparsing as pp

integer = pp.pyparsing_common.integer
numeric_tags = pp.Group("#" + pp.delimitedList(integer)("tags") + "#")
name_tag = pp.Word(pp.alphas, pp.printables)
terminating_tag = pp.Group("<" + integer("tag") + ">")

expr = numeric_tags("leading") + name_tag("name") + ... + terminating_tag("terminating")

sample = "#12,34# name (lorem (ipsum) <23>"

print(expr.parseString(sample).dump())
```

Prints
```
[['#', 12, 34, '#'], 'name', '(lorem (ipsum) ', ['<', 23, '>']]
- _skipped: ['(lorem (ipsum) ']
- leading: ['#', 12, 34, '#']
  - tags: [12, 34]
- name: 'name'
- terminating: ['<', 23, '>']
  - tag: 23
```

The skipped text is saved with the results name `_skipped`.

**Comment by Midnighter** [comment]
This is gold. Thank you so much!

**Comment by lenormf** [comment]
Trying to get something similar to work, to no avail:

```python3
import pyparsing as pp

expr = pp.Literal("`") + ... + pp.Literal("`")

sample = "`foo bar`123`"

print(expr.parseString(sample, parseAll=True).dump())
```

In my bigger parser, some words are guaranteed not to contain any whitespace, and the only requirement is that they are bound with a backtick. But backticks in the word itself are allowed, and PyParsing doesn't greedily skip over them to the end of the word.

I've also tried with a `Regex` element, no luck.

Ideas?

**Comment by ptmcg** [comment]
RE's do greedy matching, would this Regex work for you?

    Regex(r"`\S+`")

**Comment by lenormf** [comment]
That works, thanks a lot! I don't remember what regex I tried or why it didn't work beforehand… Sorry for the noise.
