### ISSUE TITLE
How to sperate sub-grammars in railraod diagrams [pyparsing-3.0.0.b2]

### ISSUE THREAD

**Issue by RavenKiller** [pyparsing/pyparsing#278]
I want to draw railroad diagram like this:
![street_address_rr_diag](https://user-images.githubusercontent.com/383875/90326561-57ff9700-df4f-11ea-850d-ffe8ff1a52f3.jpg)
But I got a result that put all grammars into one railroad with their names as labels:
![Snipaste_2021-04-28_14-42-33](https://user-images.githubusercontent.com/41775391/116358244-03c3eb00-a830-11eb-891b-b9b4aee0b398.png)

The program I run is:
```python
import pyparsing as pp
from pyparsing.diagram import to_railroad, railroad_to_html
from pathlib import Path

# define a simple grammar for parsing street addresses such as "123 Main Street"
# number word...
number = pp.Word(pp.nums).setName("number")
name = pp.Word(pp.alphas).setName("word")[1, ...]

parser = number("house_number") + name("street")
parser.setName("street address")

# construct railroad track diagram for this parser and save as HTML
rr = to_railroad(parser)
Path('parser_rr_diag.html').write_text(railroad_to_html(rr))
```

**Comment by multimeric** [comment]
Thanks for moving the issue here.

Unfortunately I've had a look back at my code, and the logic I use for extracting subdiagrams is to only extract if:

* The element has any children
* We have seen the node twice in the tree

Otherwise, I wanted to keep the nodes within the current subtree to avoid too much subdivision.

If this isn't sufficient for you, it should be possible to add some parameters that configure this behaviour. For example, any named element gets extracted. Is that the behaviour that you want?

**Comment by danielbom** [comment]
@multimeric Has any parameter or option been added to be able to separate the nodes?

**Comment by multimeric** [comment]
No, not yet

**Comment by ptmcg** [comment]
@danielbom I've worked with @multimeric this past weekend on this. The algorithm has been changed to break out expressions as separate diagrams if they have been given a name using `setName()`. This way you can create a diagram that looks very much like your starting BNF, provided you add the `setName()` calls where needed. This is going to go out in pyparsing 3.0.0c1 this week.

Here is your street address diagram. The annotations with results names can be turned on/off.
![street_address_diagram](https://user-images.githubusercontent.com/383875/132241730-d6957143-fae5-43b1-9731-48ba5728ad66.jpg)

**Comment by ptmcg** [comment]
Pushed out in 3.0.0rc1. Install it into a testing virtualenv using this command:

    pip install pyparsing==3.0.0rc1
