### ISSUE TITLE
Add a Caseless version of CloseMatch

### ISSUE THREAD

**Issue by MoralCode** [pyparsing/pyparsing#279]
I notice that theres classes for `CaselessLiteral` and a `CloseMatch` but there doesnt seem to be a class combining the two for situations where you want a `CaselessLiteral` but also want to be tolerant of a certain number of incorrect characters (i.e. to catch typos) as is the behavior with `CloseMatch`. Whis would have the behavior of a less-stringent `CloseMatch` that will only consider a character to be nonmatching if it is a different character, rather than just a differently-cased version of the same character.

After poking around the code, it would seem to me that this could essentially be some light refeatoring to move the string comparison from [here](https://github.com/pyparsing/pyparsing/blob/b5b1fdd1c0a3dfffbbad206e885d59e6015015a8/pyparsing/core.py#L2154) to a new function within `CloseMatch` and then create a subclass of `CloseMatch` that changes the comparison function to use `src.lower() != mat.lower()) as the comparison instead.

Would this be something that would be useful to submit a pull request for? or would this be better to create in a separate package/module?

**Comment by ptmcg** [comment]
Sounds like you could just do a PR - but I don't think this really merits a new class, just a `caseless` option on the `CloseMatch` class itself.

If you do submit a PR, it would be a big help if you also add tests to test_unit.py, and a blurb to the CHANGES file. (In fact, I encourage you to write the tests first, and then write the code that will pass them.)

**Comment by MoralCode** [comment]
Thanks! Should I just add my note to CHANGES underneath the `Version 3.0.0c1 - April, 2021` heading? or should I make a new heading

**Comment by ptmcg** [comment]
Use the 3.0.0c1 section, since that version is not yet released (I need to update the date, but I can take care of that).
