### ISSUE TITLE
[Feature request] Add new flags to `delimitedList` helper.

### ISSUE THREAD

**Issue by heckad** [pyparsing/pyparsing#284]
1) Allow last delimiter flag with type bool(default false). If true then should parse `delimitedList(arg) + Optional(Suppress(','))`.
2) Allow empty. Equeal to `Optional(delimitedList(arg), [])`

**Comment by ptmcg** [comment]
For point 1, I had a similar idea recently, and I thought I had already added it in, as something like `allowTrailing=True`. Yes, I think this is a very good idea, for parsing syntaxes that allow the extra trailing comma (like Python).

For point 2, I'm less convinced that another flag to learn is better than using Optional. And if Optional, it shouldn't have a default of '[]', but just, well, nothing. If it needs to be a list, then it would be wrapped in a Group, and the Group would take care of making it a list.

So look for your first suggestion in the next pyparsing release. Thanks for writing, and welcome to pyparsing!

**Comment by heckad** [comment]
1) Please do this as [kw args only](https://www.python.org/dev/peps/pep-3102/).

2) This is needs for a function call. If parse something like `foo()` then call args will be empty list `[]`.

Thank you! 

PS Can I create the pull request?

**Comment by ptmcg** [comment]
Again, I don't think you want 2 to default to []. If your function args are Grouped, then the Group will create an empty list for you. If they aren't Grouped, then you'll just get nothing, in place of any.

But go ahead and do the PR for the first item, `allowTrailing`. (My apologies for the camelcase names, but that is how just about all the other kwargs are done in this version - even PEP 8 values consistency in this regard.)

Keyword-args only is fine for new args, so okay for this new kwarg, but breaks for old args. I like the keyword-args only form, but I'll probably only add it throughout when I break all the APIs by making them PEP 8 snake case names.

**Comment by ptmcg** [comment]
allow_trailing_delim flag added in 3.0.0b3
