### ISSUE TITLE
Question about combine/optional

### ISSUE THREAD

**Issue by doomedraven** [pyparsing/pyparsing#289]
Hello, i was trying to spot the answer in issues/google but no way

this works on version `2.3.0`, but doesn't work since `2.3.1`

string example, `c` can be optional so i need to make it optional
```
# ${S} = ('HKLM:Y5aSoftwareY5a'  -CrepLAcE 'Y5a','\')
```

```
_replace_command = pp.Combine(pp.Optional(pp.CaselessLiteral("c")) + pp.CaselessKeyword("replace"))
```

it works on > `2.3.0` only if i set only like this
```
_replace_command = pp.CaselessKeyword("creplace")
```

any idea why? 

thanks in advance

**Comment by ptmcg** [comment]
The Keyword classes check the neighboring characters for keyword characters, to ensure that you are only matching the desired string and not an embedded one.  `Literal("if")` will match the "if" in "ifdef", but `Keyword("if")` will not.  Also, `Literal("ex") + Keyword("it")` will match "ex it", but not "exit".

`CaselessKeyword("replace")` _shouldn't_ match the "replace" in "creplace", as it is immediately preceded by a valid keyword character. You will probably need to write this as `CaselessKeyword("creplace") | CaselessKeyword("replace")`.

**Comment by doomedraven** [comment]
thank you a lot for the explanation, have a good day
