### ISSUE TITLE
Add type annotations to pyparsing

### ISSUE THREAD

**Issue by ptmcg** [pyparsing/pyparsing#290]
Add type annotations to pyparsing function signatures.

(May be problematic, since pyparsing is pretty tolerant of multiple types, such as auto-promoting str to Literal, accepting multiple parse action forms, etc.)

Still worth looking at though, since it is such a help in modern IDEs.

**Comment by maxfischer2781** [comment]
The main challenge is probably figuring out what the valid types are for each call. Annotations themselves should be doable.

I assume you don't want the third-party `typing_extensions` module for backports, so runtime type annotations would be restricted to [Python3.6 typing](https://docs.python.org/3.6/library/typing.html) (or 3.5 – not much difference there). That mostly means no ``typing.Literal`` or ``typing.Protocol`` (both 3.8); not sure whether these would be needed.  
The major decision is whether annotations should go right in the code, or be in separate ``.pyi`` files. ``.pyi`` files have the entire ``typing`` feature set and no runtime cost, code annotations are easier when working with the code.

--------------------------

Even though PyParsing is rather tolerant about what it accepts, at a glance I haven't found a case that would be more complicated than adding a ``Union`` for all the variants. For example, worst case is something like ``ParseAction = Union[Callable[[], Any], Callable[[ParseResults], Any], Callable[[int, ParseResults], Any], Callable[[str, int, ParseResults], Any]]`` – not exactly pretty, but doable.

**Comment by ptmcg** [comment]
Work largely done, to be released in 3.0.0

**Comment by ptmcg** [comment]
Pushed out in 3.0.0rc1.
