### ISSUE TITLE
A tab breaks locn_start indexation

### ISSUE THREAD

**Issue by Hi-Angel** [pyparsing/pyparsing#293]
# Steps to reproduce *(in terms of terminal commands)*

In code below it's important to note that the line that says `some text` should be indented with a tab. Otherwise it's not reproducible.

```
$ cat ./parse.py
#!/usr/bin/python

from pyparsing import Regex, locatedExpr # type: ignore

regex_to_find \
    = locatedExpr(Regex(r'some text'))('line1') \
    + locatedExpr(Regex(r''))('line2') # no-op match to work around disappearning regexps naming

def parse(text):
    r = locatedExpr(regex_to_find)('regex_to_find')
    return [match for match in r.scanString(text)]

def str_insert(string: str, substring: str, at: int) -> str:
    return string[:at] + substring + string[at:]

def process_matches(matches, text: str) -> str:
    print('Replacing…\n')
    for m in reversed(matches): # overwrite it starting from the bottom
        # prepend new text
        i_start = m[0]['regex_to_find'][f'line1']['locn_start']
        text = str_insert(text, 'foobar ', i_start)
    return text

text_to_process = \
"""	some text
"""

if __name__ == "__main__":
    matches = parse(text_to_process)
    print(f'Got matches: {matches}')
    if not matches:
        raise Exception("No matches")
    new_text = process_matches(matches, text_to_process)
    print(new_text)
$ ./parse.py
/home/constantine/Projects/baum/bds/./parse.py:9: SyntaxWarning: null string passed to Regex; use Empty() instead
  + locatedExpr(Regex(r''))('line2') # no-op match to work around disappearning regexps naming
Got matches: [(([([8, ([8, 'some text', 17], {'locn_start': [8], 'value': ['some text'], 'locn_end': [17]}), ([17, '', 17], {'locn_start': [17], 'value': [''], 'locn_end': [17]}), 17], {'locn_start': [8], 'line1': [([8, 'some text', 17], {'locn_start': [8], 'value': ['some text'], 'locn_end': [17]})], 'line2': [([17, '', 17], {'locn_start': [17], 'value': [''], 'locn_end': [17]})], 'value': [([([8, 'some text', 17], {'locn_start': [8], 'value': ['some text'], 'locn_end': [17]}), ([17, '', 17], {'locn_start': [17], 'value': [''], 'locn_end': [17]})], {})], 'locn_end': [17]})], {'regex_to_find': [([8, ([8, 'some text', 17], {'locn_start': [8], 'value': ['some text'], 'locn_end': [17]}), ([17, '', 17], {'locn_start': [17], 'value': [''], 'locn_end': [17]}), 17], {'locn_start': [8], 'line1': [([8, 'some text', 17], {'locn_start': [8], 'value': ['some text'], 'locn_end': [17]})], 'line2': [([17, '', 17], {'locn_start': [17], 'value': [''], 'locn_end': [17]})], 'value': [([([8, 'some text', 17], {'locn_start': [8], 'value': ['some text'], 'locn_end': [17]}), ([17, '', 17], {'locn_start': [17], 'value': [''], 'locn_end': [17]})], {})], 'locn_end': [17]})]}), 8, 17)]
Replacing…

        some tefoobar xt

```

## Expected

The last entry is `foobar some text`

## Actual

The last entry is `some tefoobar xt`.

This is because `locn_start` is `8` as can be seen in the output that prints matches. It should be instead `1`

# Additional information

pyparsing version: 2.4.7

**Comment by Hi-Angel** [comment]
**upd**: simplified code a bit

**Comment by Hi-Angel** [comment]
Hmm, I found a workaround: documentation says, quoting:

> parseWithTabs() - function to override default behavior of converting tabs to spaces before parsing the input string; rarely used, except when specifying whitespace-significant grammars using the White class.

Modifying function `parse()` in the testcase to add a line `r.parseWithTabs()` fixes the problem.

So, the bug comes down to the fact that `r.parseWithTabs()` for some reason is not called by default. I mean, the behavior that can be observed in the report is clearly wrong, a tab should not be counted as 8 spaces. 

IOW, the call to `r.parseWithTabs()` should be opt-out rather than opt-in.

**Comment by ptmcg** [comment]
That's not really a workaround, that is the solution. Since v1.0, parseString has defaulted to expanding tabs to spaces, in order to handle parsing of data that is formatted in columns using tabs. This is a design decision that, after all this time, right or wrong, I can't really go back on.

I'm still looking at #294 - in pyparsing 3.0 I'm introducing the Located class to replace locatedExpr, and one of the reasons is to support embedded results names as you have them. But Located isn't doing the correct thing, so you have sent me a good test case for this new code.

**Comment by Hi-Angel** [comment]
> This is a design decision that, after all this time, right or wrong, I can't really go back on.

I see, makes sense to me. You can close this report if you don't think there's anything actionalble.

**Comment by Hi-Angel** [comment]
> I'm still looking at #294 - in pyparsing 3.0 I'm introducing the Located class to replace locatedExpr, and one of the reasons is to support embedded results names as you have them. But Located isn't doing the correct thing, so you have sent me a good test case for this new code.

Thanks!
