### ISSUE TITLE
Numbers of the form .NNN  not parsed correctly

### ISSUE THREAD

**Issue by edwilliams16** [pyparsing/pyparsing#296]
Replace
`  fnumber = Regex(r"[+-]?\d+(?:\.\d*)?(?:[eE][+-]?\d+)?")`
in 
[https://github.com/pyparsing/pyparsing/blob/master/examples/fourFn.py](url)
with
`fnumber = Regex(r'[-+]?(?:(?:\d*\.\d+)|(?:\d+\.?))(?:[Ee][+-]?\d+)?'`

to include this case.

**Comment by ptmcg** [comment]
Thanks for the submission, and Welcome to Pyparsing!

I'm probably going to leave this as it is - one of my early programming languages was Pascal, and in Pascal, the leading "0" was required for a float between 1 and -1. So I tend to have that bias when I parse them in my own parsers.

The examples are there as a starting point for people to explore and customize. Just as you did to add support for a floating point number with no leading digit before the decimal. (There are a couple, like delta_time and statemachine, that I do plan to spin out into separate pip-installable packages, but most are just for tutorial purpose.)

**Comment by edwilliams16** [comment]
Fair enough - thanks.
