### ISSUE TITLE
Current stable release documentation

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [pyparsing/pyparsing#297]
I followed the link to the online docs at <https://pyparsing-docs.readthedocs.io/> and went to <https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#hello-world>. Unfortunately the first example in the code is not working for me using version `2.4.7`. That's probably because of a breaking change in `3.0.x`. However, I am unable to find the docs for `2.4.7`. Where can I find the current latest stable version docs?

**Comment by ptmcg** [comment]
At readthedocs, there is  a version selector in the lower right corner. The 2.4.7 link goes here: https://pyparsing-docs.readthedocs.io/en/pyparsing_2.4.7/  Do these work for you?

**Comment by ZelphirKaltstahl** [comment]
Ah I see! The script that shows that select box was not allowed to run and there was no indication of the select box being missing on the page, so it was invisible to me, that something was missing. I was already wondering, why this readthedocs page does not have a version selector.

Thanks, I will try that.
