### ISSUE TITLE
Use Markdown in readme

### ISSUE THREAD

**Issue by linonetwo** [pyparsing/pyparsing#3]
The current readme is not suitable for a GitHub repo, consider turning to markdown?

**Comment by ptmcg** [comment]
Thanks, am in the process of migrating code from SF over to GitHub, and this is on the todo list.

**Comment by hugovk** [comment]
This can be closed, it has been done in https://github.com/pyparsing/pyparsing/commit/8da759898768311ad3a67a1963d6132f138469a1 👍
