### ISSUE TITLE
Failed to parse a regex with begin/end ^$

### ISSUE THREAD

**Issue by numerys** [pyparsing/pyparsing#300]
I tried to use a regex (dd.mm.yyyy with leap year support) like

`^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[13-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$`

which is from [here](https://stackoverflow.com/a/15504877). It invokes multiple ^ and $.

When I do a

    rx = re.compile('^...$')  
    re.match(rx, input)

it went through, but when I do a

    px = pyparsing.Regex('^...$')  
    r = px.parseString(input)

it fails, no matter what input I generate.

How can I use ^$ within the regex mentioned above?

**Comment by ptmcg** [comment]
This just worked for me, but I had to put an 'r' in front of the pattern to define a _raw string literal_, so that Python would interpret the '\'s correctly:

    pp.Regex(r"^...$").parseString("29.02.2004")

My actual code:

    >>> ddmmyy = re.compile(r"^...$")
    >>> pp.Regex(ddmmyy).parseString("29.02.2004")
    (['29.02.2004'], {})

**Comment by numerys** [comment]
Thanks for your repsonse. It helped me to understand pyparsing a lot. But still, when I use such regex-token with e.g. a literal-token I get an error. I made a short python3 example:

    import re
    import pyparsing

    header = "\"Valuta date\"" # check by parser (2)
    body = "28.02.2022"        # check by regex (1) and parser (3)
    doc = header + body        # check by parser (4)
    print(doc)

    # creating parser and regex
    p_header = pyparsing.Literal(header) # (2)
    x_body = re.compile(r"^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[13-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$") # (1)
    p_body = pyparsing.Regex(x_body) # (3)
    p_doc = p_header + p_body # (4)                 # <<---- What happens here?

    # try the regex (1)
    try:
        if re.match(x_body, body) is None:
            raise Exception("no match in regex")
        print("success regex")
    except Exception as e:
        print(e)

    # try the parser (2, 3, 4)
    try:
        parse0 = p_header.parseString(header) # works
        parse1 = p_body.parseString(body)     # works also
        parse2 = p_doc.parseString(doc)       # nope
        print("success parser")
    except pyparsing.ParseException as e:
        print(e)

Why does this this concatenated parser `p_doc` does not match?

**Comment by ptmcg** [comment]
The problem is your '^' and '$' anchors. They match when a ddmmyyyy is parsed in isolation, but when part of a larger string it fails. '^' indicates "beginning of a line", but 28 does not start at the beginning of a line.

Change to this:

    x_body = re.compile(r"^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[13-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$".replace("^", "").replace("$", "") # (1)

    # also, this line will make your exceptions a little less ugly
    p_body = pyparsing.Regex(x_body).setName("dd.mm.yyyy") # (3)

**Comment by ptmcg** [comment]
Also - THANKS for submitting an easy-to-reproduce example of your program and pyparsing problem. I was able to copy into my editor and quickly see what was going wrong.  Well done!

And Welcome to Pyparsing!

**Comment by numerys** [comment]
I tried it but now (when removing ^$) I get dates parsed which are not existent.

E.g. 29.02.2022 does not exist but with changes to the regex it will be accepted.

    import re
    import pyparsing

    header = "\"Valuta date\"" # check by parser (2)
    body = "29.02.2022"        # check by regex (1) and parser (3)
    doc = header + body        # check by parser (4)
    print(doc)

    # creating parser and regex
    p_header = pyparsing.Literal(header) # (2)
    x_body = re.compile(r"^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[13-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$".replace("^", "").replace("$", "")) # (1)
    p_body = pyparsing.Regex(x_body).setName("date") # (3)
    p_doc = p_header + p_body # (4)

    # try the regex (1)
    try:
        if re.match(x_body, body) is None:
            raise Exception("no match in regex")
        print("success regex")
    except Exception as e:
        print(e)

    # try the parser (2, 3, 4)
    try:
        parse0 = p_header.parseString(header) # works
        parse1 = p_body.parseString(body)     # works also
        parse2 = p_doc.parseString(doc)       # works now but accepts undefined dates
        print("success parser")
    except pyparsing.ParseException as e:
        print(e)

**Comment by numerys** [comment]
[This](https://stackoverflow.com/a/25823776) regex got not much attention but it looks good at the first view. Maybe its quality is above the most prefered [regex](https://stackoverflow.com/a/15504877). I removed `^$` and until now I did not find an error.

    import re
    import pyparsing

    header = "\"Valuta date\"" # check by parser (2)
    body = "28.02.2022"        # check by regex (1) and parser (3)
    doc = header + body        # check by parser (4)
    print(doc)

    # creating parser and regex
    p_header = pyparsing.Literal(header) # (2)
    x_body = re.compile(r"(?=\d{2}([-.,\/])\d{2}\1\d{4})(?:0[1-9]|1\d|[2][0-8]|29(?!.02.(?!(?!(?:[02468][1-35-79]|[13579][0-13-57-9])00)\d{2}(?:[02468][048]|[13579][26])))|30(?!.02)|31(?=.(?:0[13578]|10|12))).(?:0[1-9]|1[012]).\d{4}") # (1)
    # x_body = re.compile(r"^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[13-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$".replace("^", "").replace("$", "")) # (1)
    p_body = pyparsing.Regex(x_body).setName("date") # (3)
    p_doc = p_header + p_body # (4)

    # try the regex (1)
    try:
        if re.match(x_body, body) is None:
            raise Exception("no match in regex")
        print("success regex")
    except Exception as e:
        print(e)

    # try the parser (2, 3, 4)
    try:
        parse0 = p_header.parseString(header) # works
        parse1 = p_body.parseString(body)     # works also
        parse2 = p_doc.parseString(doc)       # nope
        print("success parser")
    except pyparsing.ParseException as e:
        print(e)

**Comment by numerys** [comment]
Could not find an error, so I closed the issue. Thanks for helping.
