### ISSUE TITLE
How to parse "end of string"

### ISSUE THREAD

**Issue by numerys** [pyparsing/pyparsing#301]
I do a parsing like

    grammar = pyparsing.OneOrMore(some_A | some_B)
    result = grammar.parseString(some_input_string)

which is good if my input is like

    some_A
    some_B
    some_A
    ...

but if the input is

    some_A
    some_X
    some_B
    ...

The parsing still succeeds but will finish after/before some_A/some_X.

I would like to have a parsing-exception-error with a command similar like

    grammar = pyparsing.OneOrMore(some_A | some_B) + pyparsing.EndOfInput()

Is this possible? I tried ```LineEnd()```but still, the parser just stops but does not throw an error.

**Comment by ptmcg** [comment]
When calling `parseString()`, add the `parseAll=True` parameter.

Other info on parseString(): https://pyparsing-docs.readthedocs.io/en/pyparsing_2.4.7/pyparsing.html?highlight=parseString#pyparsing.ParserElement.parseString

**Comment by numerys** [comment]
Thanks
