### ISSUE TITLE
Find pyparsing.Empty() in grammar.parseString()

### ISSUE THREAD

**Issue by numerys** [pyparsing/pyparsing#303]
When I do a long grammar like

    g = A0 - B0 + pyparsing.Empty() + D0 \
      + A1 + B1 + C1                + D1

and fetch the result like

    r  = g.parseString(input, parseAll=True)

I would like to iterate through the result like

    start = 2
    end = 8
    step = 4
    for i in range(start, end, step):
        print r[i]

and get the output (with first line empty)

    # empty
    c1_result

Is such possible?

Btw. is it possible to define ```end``` with something like

    end = len(g) # == 8

?

**Comment by numerys** [comment]
It would be possible create a constant for such circumstances like

    g = A0 - B0 + pyparsing.Empty() + D0 \
      + A1 + B1 + C1                + D1

    IDX = [ 6 ]

and loop over ```IDX```. But what if I have is better described through

    g0 = A0 - B0 + pyparsing.Empty() + D0 \
       + A1 + B1 + C1                + D1
    g1 = A0 + B0                + C0                + D0 \
       + A1 + pyparsing.Empty() + pyparsing.Empty() + D1
    g = g0 | g1

Now if I iterate through ```r``` with

    r  = g.parseString(input, parseAll=True)
    for i in IDX:
        print(r[i])

I can't use a simple index like the ```IDX``` above as Idk what the user will pass in. IDX will be different at each user input.

**Comment by ptmcg** [comment]
Based on these examples, I would recommend *not* using numeric indexing to get a specific parsed element, but use results names instead:

    g0 = (A0("a0") - B0("b0") + pyparsing.Empty() + D0("d0")
          + A1("a1") + B1("b1") + C1("c1") + D1("d1"))
    g1 = (A0("a0") + B0("b0") + C0("c0") + D0("d0")
          + A1("a1") + pyparsing.Empty() + pyparsing.Empty() + D1("d1"))

Then when you parse the input, you can access the results by name instead of by index:

    print(r.c1)

regardless of where it actually falls in the results.

(Is there a reason you are using Empty instead of just marking these elements as Optional?)

**Comment by numerys** [comment]
My idea for using Empty was to have g0 and g1 the same length or better: "the same number of sub-grammar".

My hope was to have a ```r``` with a length which fullfils ```OneOrMore * g0_size_of_sub_grammars == OneOrMore * g1_size_of_sub_grammars```.

**Comment by ptmcg** [comment]
You can "force" an Empty to return a parsed value by wrapping it in a Group, or making it emit a non-None value, like this:

    missing = Empty().addParseAction(lambda: "")
    g0 = (A0 + B0 + missing + D0
          A1 + missing + missing + D1)

**Comment by numerys** [comment]
Ahh, yes, thank you.
