### ISSUE TITLE
Concatenate grammar based on values from an array

### ISSUE THREAD

**Issue by numerys** [pyparsing/pyparsing#304]
I have an long array like

    my_string = [ "s0_key", "s0_val", "s1_key", "s1_val", ..., "s498_key", "s498_val"  ]

with key/value pairs. The values (like s0_val) are not used in this example but are here for a better understanding.

The pre-last entry / the last key is a special one, it represents an empty input:

    grammar = pp.Empty().addParseAction(lambda: my_string[len(my_string)-2]) # s498_key

All other keys represent non-empty inputs which I would like to add to ```grammar```:

    for i in range(0, len(my_string)-2, 2):
        grammar = grammar | pp.Literal(my_string[i])

Such grammar in short should result in

    grammar = pp.Empty()... | pp.Literal("s0_key") | pp.Literal("s1_key") | ... | pp.Literal("s497_key")

But it is not working with this naive approach. The loop creates something (maybe a weird ```((()|)|)```?) but not a concatenated grammar.

How could I concatenate a grammar with help of an array?

**Comment by ptmcg** [comment]
I would create a list of the keys, which you could get using `my_string[0::2]`, and then call pyparsing's `oneOf` helper method.

    grammar = pp.oneOf(my_string[0::2])

It might help to just read through the howToUsePyparsing.rst doc (https://github.com/pyparsing/pyparsing/blob/master/docs/HowToUsePyparsing.rst), for more insights about some of the helper methods that are included with pyparsing.

**Comment by numerys** [comment]
Yes, thanks for the link. Did not know about it.
