### ISSUE TITLE
snake_case/camelCase issue in examples/railroad_diagram_demo.py... and more

### ISSUE THREAD

**Issue by JohnCC330** [pyparsing/pyparsing#306]
Though in the documentation `setName` and `set_name` should be compatible, the mentioned example fails to compile because of the `set_name` 's in the demo. (I'm running `3.0.0rc2` at the moment)

Once edited out (also `counted_array` and `infix_notation` fail for the same reason), I get this:
```
  File "test_railroad.py", line 36, in <module>
    grammar.create_diagram("railroad_diagram_demo.html",
  File "/root/src/pyparsing/pyparsing/core.py", line 1808, in create_diagram
    railroad = to_railroad(expr, vertical=vertical, diagram_kwargs=kwargs)
  File "/root/src/pyparsing/pyparsing/diagram/__init__.py", line 116, in to_railroad
    _to_diagram_element(element, lookup=lookup, parent=None, vertical=vertical)
  File "/root/src/pyparsing/pyparsing/diagram/__init__.py", line 386, in _to_diagram_element
    item = _to_diagram_element(
  File "/root/src/pyparsing/pyparsing/diagram/__init__.py", line 386, in _to_diagram_element
    item = _to_diagram_element(
  File "/root/src/pyparsing/pyparsing/diagram/__init__.py", line 386, in _to_diagram_element
    item = _to_diagram_element(
  [Previous line repeated 3 more times]
  File "/root/src/pyparsing/pyparsing/diagram/__init__.py", line 307, in _to_diagram_element
    return _to_diagram_element(
  File "/root/src/pyparsing/pyparsing/diagram/__init__.py", line 386, in _to_diagram_element
    item = _to_diagram_element(
  File "/root/src/pyparsing/pyparsing/diagram/__init__.py", line 302, in _to_diagram_element
    if not exprs[0].customName:
IndexError: list index out of range
```
when running the demo

```
#!/usr/bin/env python3
import pyparsing as pp

ppc = pp.pyparsing_common

# fmt: off
word = pp.Word(pp.alphas).setName("word")
integer = pp.Word(pp.nums).setName("integer")
plus_minus = pp.Char("+-").setName("add_sub")
mult_div = pp.Char("*/").setName("mult_div")
street_address = pp.Group(integer("house_number")
                          + word[1, ...]("street_name")
                          ).setName("street_address")
time = pp.Regex(r"\d\d:\d\d")

grammar = (pp.Group(integer[1, ...])
           + (ppc.ipv4_address
              & word("header_word")
              & pp.Optional(time)
              ).setName("header with various elements")("header")
           + street_address("address")
           + pp.Group(pp.countedArray(word))
           + pp.Group(integer * 8)("data")
           + pp.Group(pp.Word("abc") + pp.Word("def")*3)
           + pp.infixNotation(integer,
                               [
                                   (plus_minus().setName("pos_neg"), 1, pp.opAssoc.RIGHT),
                                   (mult_div, 2, pp.opAssoc.LEFT),
                                   (plus_minus, 2, pp.opAssoc.LEFT),
                               ]).setName("simple_arithmetic")
           + ...
           + pp.Group(ppc.ipv4_address)("ip_address")
           ).setName("grammar")


grammar.create_diagram("railroad_diagram_demo.html",
            vertical = 6,
            show_results_names = True)

```

**Comment by ptmcg** [comment]
Thanks for testing out rc2. Looking at your traceback, it looks like you are still running the 3.0.0b2 version, though. Might be from the shebang line added at the top.

Even so, the indicated line could raise an unwanted exception if this were an empty element (created using And([]) or Forward()). So thanks for testing the new code!

**Comment by JohnCC330** [comment]
> Thanks for testing out rc2. Looking at your traceback, it looks like you are still running the 3.0.0b2 version, though. Might be from the shebang line added at the top.

Hello Paul,
As usual, you identified the weak spot at once. For some reason I really had the `b2` version instead of the `rc2'. Today I repeated the steps from before, but all was correct. Go figure.

The result was less than encouraging though. Using a test parser, I get very strange-looking diagrams, with titles like 'Combine' and 'Group'. I suspect I need to `.set_name` those rules to get the right names.
Also, the original Tab Atkins functions allowed to generate standalone SVG files which are useful to illustrate syntax in documents, not only webpages. I have yet to figure this out...

Thanks!
John

**Comment by ptmcg** [comment]
Yes, the diagrams code is likely to evolve with usage. Combine and Group are not supposed to manifest through. If the changes are minimal, they might go into 3.0.0, otherwise 3.0.1.

**Comment by JohnCC330** [comment]
`.set_name` solved the names in the diagrams, which are now looking quite nice. Sequences are shown vertically (instead of horizontally), which isn't very readable... Say

```        vector = pp.Group(
                    pp.Literal("<").suppress() + sfloat +
                    pp.Literal(",").suppress() + sfloat +
                    pp.Literal(",").suppress() + sfloat +
                    pp.Literal(">").suppress()).set_name('vector')
```
translates into 

![Screenshot_2021-10-04_14-49-26](https://user-images.githubusercontent.com/3728987/135899517-9dc7bd8d-8293-4745-9611-bb29c1ace9c1.png)

Anyway, great progress, and thanks to those involved!

**Comment by ptmcg** [comment]
create_diagram takes a `vertical` parameter, that allows to customize this. The default is 3, meaning any expression 3 terms or longer will be vertical. Try changing to vertical=10.
