### ISSUE TITLE
Using set_parse_action() causes element to change to a list

### ISSUE THREAD

**Issue by dpatel20** [pyparsing/pyparsing#309]
I am parsing a file (sample attached) using the attached script and ending up with a dictionary which all works fine. 
[testparser.zip](https://github.com/pyparsing/pyparsing/files/7321501/testparser.zip)

As part of this, I am using `set_parse_action()` to take one of the elements (`param`)and make a nested dictionary.

It works but instead of my `sects` being a list of nested dictionaries, it is a nested list of nested dictionaries.

So, I expected `sects` to be like:

```python
[
  {
      # sect1
  },
  {
      # sect2
  }
]
```

But instead I get a list of lists:

```python
[
  [
    {
      "type": "typeA",
      "name": "HelloWorld",
      "output_log": "c:\\test\\out.log",
      "user0": {
        "name": "Jane",
        "city": "New York"
      }
    }
  ],
  [
    {
      "name": "GoodbyeAll",
      "type": "typeB",
      "user1": {
        "name": "John",
        "city": "London"
      }
    }
  ]
]

```

If I remove the `set_parse_action()` then I get a list of dictionaries.

I am not sure if this is a bug or my code (most likely my code!) hence why I'm raising it as an issue here.

**Comment by dpatel20** [comment]
Apologies, with all my experimenting I uploaded the wrong .py file. The `set_parse_action()` was in the wrong place which meant I lost the key:value pairs that are outside the `sects`.

New file attached with the `set_parse_action()` in the correct place
[testparser1.zip](https://github.com/pyparsing/pyparsing/files/7322758/testparser1.zip)

**Comment by ptmcg** [comment]
And you should be able to just pass your Path var directly to `parseFile`.
