### ISSUE TITLE
Some `matplotlib` mathtext yields a `ParseFatalException`

### ISSUE THREAD

**Issue by heltluke** [pyparsing/pyparsing#318]
Minimal example
```python
import matplotlib.pyplot as plt

plt.plot(range(5), '.')
plt.title(r"$x \cdot y$")
plt.show()
```
presently fails with `ParseFatalException: Unknown symbol: \cdot, found '\' (at char 2), (line:1, col:3)`.

Looking at the `matplotlib` docs, this seems to be somehow related to their use of `pyparsing` https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/_mathtext.py#L15.

**Comment by ptmcg** [comment]
Is this resolved now?

**Comment by anntzer** [comment]
We are trying to decide on the right fix on Matplotlib's side, perhaps you can comment on https://github.com/matplotlib/matplotlib/pull/21606?

**Comment by ptmcg** [comment]
Any further requirements on pyparsing here?

**Comment by anntzer** [comment]
I think everything is good on Matplotlib's side now.

**Comment by ptmcg** [comment]
Thanks, closing
