### ISSUE TITLE
3.0.0 not backward compatible to 2.4.7

### ISSUE THREAD

**Issue by kochelmonster** [pyparsing/pyparsing#321]
Please try out the attached test file. It runs in 2.4.7 but causes errors in 3.0.0

[pyparse_error.py.gz](https://github.com/pyparsing/pyparsing/files/7429019/pyparse_error.py.gz)

**Comment by ptmcg** [comment]
I believe I have this fixed in 3.0.4, which will go out later today or this evening.

**Comment by ptmcg** [comment]
@kochelmonster I have reproduced your issue in 3.0.3, I think I have it fixed in 3.0.4, which will go out this evening or tomorrow.

**Comment by kochelmonster** [comment]
It works again, thank you.
Nevertheless I found a small incompatibility to 2.4.7:
the `location`-Attribute of `ParseResults` can be set in 2.4.7 but not in 3.0.4.

**Comment by ptmcg** [comment]
Great!

Yes, the attribute-setting for `ParseResults `was changed as a side-effect of converting it to use` __slots__` for memory and performance improvement. The statement as you have it is not supported now, and really never should have been. To do this now, use indexed access to assign the value.

    results["location"] = "Kalamazoo, MI, USA"

Here is the note in the CHANGES doc from the 3.0.4 release.

> - Documented API-changing side-effect of converting `ParseResults` to use `__slots__`
>   to pre-define instance attributes. This means that code written like this (which
>   was allowed in pyparsing 2.4.7):
> 
>   ```python
>     result = Word(alphas).parseString("abc")
>     result.xyz = 100
>   ```
> 
>   now raises this Python exception:
> 
>   ```python
>     AttributeError: 'ParseResults' object has no attribute 'xyz'
>   ```
> 
>   To add new attribute values to ParseResults object in 3.0.0 and later, you must
>   assign them using indexed notation:
> 
>   ```python
>     result["xyz"] = 100
>   ```
> 
>   You will still be able to access this new value as an attribute or as an
>   indexed item.
