### ISSUE TITLE
3.0.5 fails with extra requirements

### ISSUE THREAD

**Issue by frascuchon** [pyparsing/pyparsing#329]
Last release makes requirements with extra deps fails.

Next code works well for 3.0.4 and fails with 3.0.5

```python
import packaging.requirements
packaging.requirements.Requirement("jinja2; extra == 'diagrams'")
```

**Comment by benelgiac** [comment]
I cannot share my code but my builds are experiencing a regression too with 3.0.5 when dealing with requirements

```
<lambda>
    lambda s, l, t: Marker(s[t._original_start : t._original_end])
TypeError: slice indices must be integers or None or have an __index__ method
```
and I'm just using a setup.py with `install_requires` section.

**Comment by ptmcg** [comment]
Pyparsing 3.0.6 should address this issue, in a manner compatible with the current release of packaging.

**Comment by layday** [comment]
Thanks @ptmcg, much appreciated.
