### ISSUE TITLE
lookahead with tokens returned

### ISSUE THREAD

**Issue by geuben** [pyparsing/pyparsing#33]
Hi,

I'm trying to move some code from using parsley (https://github.com/pyga/parsley) to pyparsing.

It was going so well but I think I've run into a wall. 

The code I am moving uses this expression from parsley:

> `~~expr`: Positive lookahead. Fails if the next item in the input does not match expr. Consumes no input.

Which I was hoping to replace with `FollowedBy`, however `FollowedBy` always returns a null token list, I need the results from the `FollowedBy` returned so I can utilise them further downstream.

Any ideas how I would go about this?

**Comment by paulmcg-iio** [comment]
There is not at this time, but I am in the middle of incorporating the opposite of `FollowedBy`, `PrecededBy`, to implement lookbehind, and I have included the ability to capture the content of the preceded value if a results name is defined, and I can look at adding this to `FollowedBy` also.

**Comment by ptmcg** [comment]
There is no way with the current version of pyparsing. I am implementing a PrecededBy class that is the inverse of FollowedBy, which will include the ability to attach results names to the expression used for PrecededBy. If the caller attaches a results name, then the content parsed by PrecededBy will not be included in the result's list interface, but will be accessible by name from the result's dict interface. Should not be difficult to replicate that logic into FollowedBy as well. Look for it in a future pyparsing release.

**Comment by geuben** [comment]
Thanks.
