### ISSUE TITLE
No limits on ZeroOrMore/OneOrMore?

### ISSUE THREAD

**Issue by elespike** [pyparsing/pyparsing#330]
Hello,

Is there a way to limit the maximum number of matches when using `ZeroOrMore`, `OneOrMore`, or `delimited_list`?

Otherwise, parsers can easily be vulnerable to resource consumption:
```pycon
>>> from pyparsing import delimited_list
>>> d = delimited_list('A')
>>> x = d.parse_string('A,' * 1000000000000000000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
```

I'm aware of the `[x, y]` construct, but not sure if I could modify an existing parser expression (like the return value from `delimited_list`) to add those limits.

**Comment by elespike** [comment]
🤦‍♂️ good catch lol
I did see the script hanging with lower numbers, but thought the MemoryError was more visible for an example 😅 didn't consider it wasn't related!

Thanks for looking into it, glad it helped surface some bugs. =)

What about limiting the size of a `delimited_list`? Will `[x, y]` work with its returned expression?

**Comment by ptmcg** [comment]
No, you need to limit the work during parsing, not after the fact. You can usually step through the results from a large parse using scan_string, since it returns a generator. But within the grammar, repeaters like `ZeroOrMore`, `OneOrMore`, and `delimitedList` just keep going as long as their underlying expression keeps matching the input.

You could try implementing a custom version of `OneOrMore` that keeps a count of the matches, and then stops at some limit, or raises an exception when the limit is reached, or discards any more matches after reaching the limit (i.e., keep parsing, but don't blow up memory by adding any more matches to the parsed results).

What value of `y` were you thinking of? If `y > sys.recursionlimit/4` and using `[..., y]` , you'll get the `RecursionError`.

**Comment by elespike** [comment]
🤔 I see, makes sense to limit with `scan_string` and that's actually what I happen to be using. I'll go that route.

For my purposes, a `y` of 99 would be more than enough. My initial idea was to implement a clone of `delimited_list` that used `[0, 99]` instead of `ZeroOrMore`. I got really close, but for some reason I couldn't get `set_results_name` to work with my implementation. 🤷 but I don't want to go that route anyway.

Then I thought maybe I'd submit a patch for an added kwarg for `delimited_list`. After this discussion, doesn't sound like that's the way to go. 😆 

I should be able to handle it with the generator 👍 thanks for your help!

**Comment by elespike** [comment]
Hm... don't think it'll work. =/

```pycon
>>> for tokens, start, end in d.scan_string('B' * 100 + 'A,' * 100 + 'C' * 100):
#                                                   ^^^ what if I want to stop at 90 As?
...     print(tokens)
...     break
...
['A', 'A', 'A'... # 100 of them
```

The `delimited_list` will grab all of the list each time it finds one, so `tokens` can be arbitrarily large for a given iteration.

**Comment by ptmcg** [comment]
Here is the updated delimited_list method that will accept a max argument to limit the number of matches. That's all it does, it doesn't do any further processing or expression skipping or exception raising (though you may get other exceptions if you use parse_all=True, for example).

```
def delimited_list(
    expr: Union[str, ParserElement],
    delim: Union[str, ParserElement] = ",",
    combine: bool = False,
    max: OptionalType[int] = None,
    *,
    allow_trailing_delim: bool = False,
) -> ParserElement:
    """Helper to define a delimited list of expressions - the delimiter
    defaults to ','. By default, the list elements and delimiters can
    have intervening whitespace, and comments, but this can be
    overridden by passing ``combine=True`` in the constructor. If
    ``combine`` is set to ``True``, the matching tokens are
    returned as a single token string, with the delimiters included;
    otherwise, the matching tokens are returned as a list of tokens,
    with the delimiters suppressed.

    If ``allow_trailing_delim`` is set to True, then the list may end with
    a delimiter.

    Example::

        delimited_list(Word(alphas)).parse_string("aa,bb,cc") # -> ['aa', 'bb', 'cc']
        delimited_list(Word(hexnums), delim=':', combine=True).parse_string("AA:BB:CC:DD:EE") # -> ['AA:BB:CC:DD:EE']
    """
    if isinstance(expr, str_type):
        expr = ParserElement._literalStringClass(expr)

    dlName = "{expr} [{delim} {expr}]...{end}".format(
        expr=str(expr.streamline()),
        delim=str(delim),
        end=" [{}]".format(str(delim)) if allow_trailing_delim else "",
    )

    if not combine:
        delim = Suppress(delim)

    if max is None:
        delimited_list_expr = expr + ZeroOrMore(delim + expr)
    else:
        delimited_list_expr = expr + (delim + expr)[..., max]

    if allow_trailing_delim:
        delimited_list_expr += Opt(delim)

    if combine:
        return Combine(delimited_list_expr).set_name(dlName)
    else:
        return delimited_list_expr.set_name(dlName)


```

**Comment by elespike** [comment]
Would you consider officially adding `max` to `delimited_list`? I'm happy to submit a PR.

**Comment by ptmcg** [comment]
Sure, submit a PR. I am trying to slow down the release frenzy, so I probably won’t do any new releases or merges until this coming weekend (unless there is another really bad regression).

 

-- Paul

**Comment by elespike** [comment]
No problem. Thanks again! =)
