### ISSUE TITLE
Incompatible with packaging 21.2

### ISSUE THREAD

**Issue by grewelle** [pyparsing/pyparsing#337]
pyparsing versions >3 are incompatible with packaging in google cloud platform.  pyparsing 2.4.7 works, but most recent releases, including 3.0.6 do not work

**Comment by ptmcg** [comment]
Can you post your error message?

**Comment by ptmcg** [comment]
Running the packaging 21.2 test suite with pyparsing 3.0.6 fails in one test where the string contents of an exception changed, but otherwise all tests pass.

Please post the error you are seeing.

Thanks!

**Comment by grewelle** [comment]
packaging 21.2 has requirement pyparsing<3,>=2.0.2, but you'll have pyparsing 3.0.6 which is incompatible.

**Comment by ptmcg** [comment]
That is an issue with packaging's requirements. Pyparsing 3.0.6 has modifications that will permit the packaging team to change their requirements in 21.3, if they so choose.

**Comment by ptmcg** [comment]
Closing this issue, as pyparsing's changes are ready to support packaging if they choose to modify their requirements to permit use of 3.0.6. But fixing this error message requires a change in packaging's requirements.
