### ISSUE TITLE
Regression in v3.0.2 onward

### ISSUE THREAD

**Issue by rossbar** [pyparsing/pyparsing#338]
This very well be related to #323, but I haven't had time to take a closer look as NetworkX is experiencing problems via its dependency on pydot, see e.g. pydot/pydot#277. There may be multiple problems because the original issue reported is apparently resolved by pyparsing 3.0.3, but the NetworkX test suite experiences failures (via pydot) with all patch versions of pyparsing >=3.0.2. We can fix the problem by pinning to pyparsing versions <=3.0.1, but since the problem is via a dependency I haven't had a chance to chase down what exactly is happening.

**Comment by ptmcg** [comment]
I just ran `networkx `tests using the latest 3.0.6 `pyparsing`, and am not getting errors. Could you post your error output?

**Comment by rossbar** [comment]
> I've recommended a fix for the pydot project to address changes in pyparsing's whitespace skipping.

Excellent, thanks for tracking this down @ptmcg . I'll go ahead and close this issue given your thorough explanation in the linked issues. Thanks again!
