### ISSUE TITLE
Switch to GH actions

### ISSUE THREAD

**Issue by levonet** [pyparsing/pyparsing#340]
Travis is going away for open-source projects, so CI will have to be migrated to GitHub actions.
If you agree, I'm ready to help.

**Comment by ptmcg** [comment]
I welcome any help in this area, thanks! Can you package the changes as a PR, or do I need to do GH config bits?

**Comment by levonet** [comment]
Nothing needs to be done right now. But at the PR stage, you will need to create a GA secret to coverage.
