### ISSUE TITLE
Pyparsing error in 3.0.6

### ISSUE THREAD

**Issue by karthik120** [pyparsing/pyparsing#343]
In python 3.7, i have below logic. Earlier version of pyparsing used operatorPrecedence and the newer version of pyparsing uses infix_notation.

   expr << pp.infix_notation(semi_expression, [
           ("not", 1, pp.opAssoc.RIGHT, self.not_operator),
           ("and", 2, pp.opAssoc.LEFT, self.and_operator),
           ("or", 2, pp.opAssoc.LEFT, self.or_operator)
           ])
    result = expr.parseString(filter_str)
    return result

I can see below traceback

  File "/root/.local/share/virtualenvs/lib/python3.7/site-packages/testfilter.py", line 192, in generate_infilter
    result = parse_filter.parse_filter_str(filter_str)
  File "/root/.local/share/virtualenvs/lib/python3.7/site-packages/testfilter.py", line 168, in parse_filter_str
    result = expr.parseString(filter_str)
  File "/root/.local/share/virtualenvs/lib/python3.7/site-packages/pyparsing/core.py", line 1127, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected 'or' term, found 'serial'  (at char 1), (line:1, col:2)

**Comment by ptmcg** [comment]
Can you provide more info? What is semi_expression and what is filter_str? Otherwise, this is not reproducible.

**Comment by karthik120** [comment]
semi_expression: Forward: Group:({{{{{'(' {WordStart W:(0-9A-Z_a-z)}} ','} {{string enclosed in "'" | string enclosed in '"'} | W:(!-+--~)} [',' Group:({{'type' '='} {"'" | '"'} re | eq | ne | gt | ge | lt | le} {"'" | '"'})]} [',' Group:({{'flag' '='} {"'" | '"'} C | I} {"'" | '"'})]} ')'})


filter_str: ("usr_lbl", "mysp", type="eq", flag="I")

**Comment by ptmcg** [comment]
If I have to reconstruct the Python code that creates that semi_expression, I will not get to look at this any time soon. Can you reproduce the problem with some Python code, and post that code?

**Comment by karthik120** [comment]
Hi, I am leveraging the file available here for the issue

https://github.com/CiscoUcs/ucsmsdk/blob/master/ucsmsdk/ucsfilter.py

Regards,
Karthik

**Comment by ptmcg** [comment]
I've cloned that repo and run the unit tests with no failures. What filter string are you trying to parse?

**Comment by ptmcg** [comment]
Closing for now - reopen if you have follow-up notes.
