### ISSUE TITLE
Few issues with Bigquery view parser example 

### ISSUE THREAD

**Issue by fadimaali** [pyparsing/pyparsing#348]
### Current parser incorrectly handles:
- quoting table names. It accepts string quoting using `"` or `'` for table names. However, BigQuery SQL syntax accepts only back ticks '`'
- table names and column names can be keywords if quoted. 
- date part in extract function call

### Current parser misses support for:
- boolean literals (TRUE and False)
- IN UNNEST
- IF expression
- PIVOT clause 
- QUALIFY clause
- REPLACE in select clause
- EXTERNAL_QUERY

**Comment by ptmcg** [comment]
I've updated this example to match the format and queries in this page: https://cloud.google.com/bigquery/docs/reference/legacy-sql .  This is probably the extent to which I'll support this example.

**Comment by ptmcg** [comment]
Updates released in 3.0.9, closing
