### ISSUE TITLE
`White` couldn't combine with `set_results_name()`

### ISSUE THREAD

**Issue by hfudev** [pyparsing/pyparsing#350]
```python
from pyparsing import White, alphas, Word

parser = White(' \t').set_results_name('indent') + Word(alphas).set_results_name('word')
print(parser.parse_string('    test'))
```
would raise:
```
pyparsing.exceptions.ParseException: Expected <SP><TAB>, found 'test'  (at char 4), (line:1, col:5)
```

but 

```python
from pyparsing import White, alphas, Word

parser = White(' \t') + Word(alphas).set_results_name('word')
print(parser.parse_string('    test'))
```
would return `['    ', 'test']`

**Comment by hfudev** [comment]
version 3.0.6

**Comment by ptmcg** [comment]
Thanks for reporting this - looks like a bug. Though the whitespace-skipping logic around White expressions is not always intuitive.

**Comment by ptmcg** [comment]
I think this latest change addresses this issue - thanks for reporting it (It actually turned up a deeper problem with whitespace-skipping around White expressions, so this was a big help)!

**Comment by hfudev** [comment]
@ptmcg Thanks :)
