### ISSUE TITLE
ERROR:root:module 'pyparsing' has no attribute 'downcaseTokens' in pyparsing 3.0.6

### ISSUE THREAD

**Issue by mattiasr** [pyparsing/pyparsing#354]
Tried to install misp-modules that used to work pre 3.x release, but now i get
```
ERROR:root:module 'pyparsing' has no attribute 'downcaseTokens'
```

More info in misp-module issue @ https://github.com/MISP/misp-modules/issues/543

**Comment by ptmcg** [comment]
Thanks for checking in and for updating to the latest pyparsing. There are several breaking API changes in this major version release.

Please review the whats_new_in_3_0_0.rst doc for this and other API changes. https://github.com/pyparsing/pyparsing/blob/master/docs/whats_new_in_3_0_0.rst#32other-discontinued-features
