### ISSUE TITLE
Please consider using flit build system to ease setuptools bootstrap

### ISSUE THREAD

**Issue by mgorny** [pyparsing/pyparsing#357]
I'm the @Gentoo maintainer for core Python packages. We're currently considering options for bootstrapping setuptools while unvendoring its dependencies in the PEP 517 world. One of the interesting options is to use [flit](https://flit.readthedocs.io/en/latest/) as it has much fewer dependencies than setuptools and we've got its bootstrap trivially covered.

Using flit as pyparsing's build system would make bootstrapping setuptools much easier for us. Flit can also generate a backwards-compatible `setup.py` (or be used alongside `setup.py`, though for this to work for us `pyproject.toml` would have to specify flit_core as the `build-backend`). FWICS it is becoming increasingly popular these days.

Would you be interested in this? If yes, then I can prepare a PR either converting the project to flit entirely, or adding it alongside existing `setup.py`, as you prefer.

**Comment by ptmcg** [comment]
Yes, I've been looking at moving away from the old setup.py to setup.cfg or other.
