### ISSUE TITLE
forgot pdb

### ISSUE THREAD

**Issue by BolshakovNO** [pyparsing/pyparsing#37]
https://github.com/pyparsing/pyparsing/blob/2fe1bb0be12e9c603bc82d3990b9305c248d99e1/pyparsing.py#L1241

**Comment by cngkaygusuz** [comment]
This line is used in a method written for invoking the debugger at a certain moment. Nothing is forgotten.

**Comment by ptmcg** [comment]
BolshakovNO's comment is correct - the original code contains this line, and the intention of setBreak is to decorate a parse action with a pdb.set_trace() to enter the debugger before calling the parse action.

**Comment by ptmcg** [comment]
I'm sorry, I thought your comment was that this line had been omitted somehow. But this line exists in all versions of pyparsing. Are you asking about the import of pdb? It is on the line immediately before, line 1240. Could you please clarify what this issue is?

**Comment by BolshakovNO** [comment]
cngkaygusuz , undertood me clearly.
I just didn't know)
