### ISSUE TITLE
Outputter of internal tree? (Discussion)

### ISSUE THREAD

**Issue by egberts** [pyparsing/pyparsing#370]
As one who has over 8,700 objects in pyparsing, I am currently exploring ways to output out the tree back into its original input file form. 

I know that some people called it parser generator but this there is a bit obtuse to me depending on which computer science domain (parser vs compiler vs text doc) that one can be thinking from. 

Nonetheless, in terms of the programming of the outputter of a pyparsing parse tree: what do we have currently to assist us pyparsing enthusiasts in not only taking in a file but also putting it back out into a file?

**Comment by ptmcg** [comment]
If you are parsing the whole file just to make some surgical changes, see if transform_string() might work for you.

Otherwise, you are probably looking at adding AST-type classes as parse actions, which implement some kind of output() method. You will also have to wrangle the whitespace that gets auto-skipped, since the parsed objects would not be aware of intervening spaces and newlines.

**Comment by ptmcg** [comment]
Are you looking for help with transform_string(), or with AST-type classes?

In the pyparsing examples directory, there are several examples of transform_string() (mostly using the old camelCase name transformString()):
- htmlTableParser.py includes a simple call to strip out HTML tags from table cells
- macroExpander.py uses transformString() to recursively convert macros (a la the macros handled by the C preprocessor)

For converting parsed data to your own AST-ish classes, look at how parsed game commands are converted to Command classes in adventureEngine.py.

**Comment by egberts** [comment]
examples given are a perfect template.  eval_arith.py and invRegex.py, are the ones.

**Comment by egberts** [comment]
This is working very well.....  Someone should write a HOWTO on this, along with any hookable out-of-tree range validators

**Comment by ptmcg** [comment]
This SO question and answer also look relevant. https://stackoverflow.com/questions/72012483/convert-simple-expressions-into-jsonlogic-format
