### ISSUE TITLE
Excessive injection of Suppress in infix_notation()

### ISSUE THREAD

**Issue by pprados** [pyparsing/pyparsing#375]
If I want to use `delimited_list()` WITHOUT suppression of lpar and rpar. 

The default value use Suppress("(")
```
def infix_notation(
    base_expr: ParserElement,
    op_list: List[InfixNotationOperatorSpec],
    lpar: Union[str, ParserElement] = Suppress("("),
    rpar: Union[str, ParserElement] = Suppress(")"),
) -> ParserElement:
```
but later in the code, the Suppress() is injected another time.
```
// Line 808
    lpar = Suppress(lpar)
    rpar = Suppress(rpar)
```
I would like to invoke `infix_notation(...,lpar="(", rpar=")")` to remove the suppression, but it's impossible.

I propose to remove the lines [808-809] to fix this bug.

Why I want this?
I want to convert a source code to another source code, but after applying pyparsing. I the middle, I can inject some "macro".

**Comment by ptmcg** [comment]
Good suggestion, we definitely don't want to double suppress lpar and rpar. But I *do* want to auto-promote str's to Suppress, which is pretty common throughout pyparsing's API (where a str is passed in and is auto-promoted to Suppress or Literal).

Can you submit a PR where the lines are written as:

```
if isinstance(lpar, str):
    lpar = Suppress(lpar)
if isinstance(rpar, str):
    rpar = Suppress(rpar)
```

You could then invoke infix_notation as `infix_notation(..., lpar=Literal("("), rpar=Literal(")")`), and the paren characters would be retained, and not suppressed.

**Comment by ptmcg** [comment]
After adding unit tests for this change, it looks odd that the grouping symbols are not grouped with their contents. I've modified the code to add them, plus notes in the HowToUsePyparsing.rst doc.
