### ISSUE TITLE
Is there a way to supress the results of ZeroOrMore only if there are zero matches?

### ISSUE THREAD

**Issue by aljohnston112** [pyparsing/pyparsing#382]
The empty string it returns would affect pretty much every parse_action I need to write. If the string is there more than zero times, then I would like the tokens.

If I do not have zeroOrMore, I get ParseException: Expected W:( $(-*--9A-Z_a-z), found end of text  (at char 18), (line:1, col:19)

Oh, I forgot that Opt is more specific to my case, but it performs the same behavior. 

I tried to create a parse_action that returned None instead of the empty string, but the None gets converted to an empty string.

**Comment by ptmcg** [comment]
Can you distill this down to a small example and post?

**Comment by egberts** [comment]
Can the following help?
```python

your_variable_name.setName('your BNF goes here')
```

**Comment by ptmcg** [comment]
Closing this for now - feel free to reopen with a small reproducible example
