### ISSUE TITLE
It's good to hear you are safe, but you are still missing your head

### ISSUE THREAD

**Issue by Nioub** [pyparsing/pyparsing#388]
https://github.com/pyparsing/pyparsing/blob/f967ba05f24ea74c2c85a87a3423cd3265d4cf10/pyparsing/diagram/template.jinja2#L11
I can't find what this "hear" is, tell me if you know, but I presume this is a typo for "head" 🙉

**Comment by ptmcg** [comment]
@multimeric - could you weigh in on this?

**Comment by multimeric** [comment]
Yeah, must be a typo. Seems like I never added a test for this either so it wasn't caught.

**Comment by ptmcg** [comment]
Released in 3.0.9
