### ISSUE TITLE
Documentation Wiki is incorrect

### ISSUE THREAD

**Issue by joej164** [pyparsing/pyparsing#390]
Trying to learn PyParsing, so reviewing docs.

The main README.md (https://github.com/pyparsing/pyparsing/blob/master/README.rst) refers to the Online Docs and the Github Wiki.

The online docs are here:https://pyparsing-docs.readthedocs.io/en/latest/

But if I go to the wiki page....and specifically click on the Documentation link
https://github.com/pyparsing/pyparsing/wiki/Documentation

The page there hasn't been updated since 2018 and says the online docs are here: https://pyparsing-docs.readthedocs.io/en/latest/index.html

I would have submitted a PR to fix it if I could, but the wiki doesn't seem to support PR's.

Thought I'd mention the docs issue.

**Comment by ptmcg** [comment]
I see the difference in the URLs, but both seem to take you to the same page.

Still, easy enough to fix the wiki, thanks for the catch.

For more pyparsing articles, please visit some of the links listed on this page too: https://github.com/pyparsing/pyparsing/wiki/Docs---Articles---Blog-posts
