### ISSUE TITLE
Recursively enable debug

### ISSUE THREAD

**Issue by multimeric** [pyparsing/pyparsing#399]
I'm sure I remember looking into this earlier, but I can't remember what we ended up settling on.

Basically, when my grammar fails to parse, it's often very hard to tell why this has happened. You can `token.set_debug().parse_string()`, which kind of helps, but it only debugs the top level token.

So I've found that this pattern is kind of neat. It just sets the debug flag for each token, recursively:
```python
def debug(token: ParserElement):
    for token in token.recurse():
        token.set_debug()
        debug(token)
```

So my question is: is there an official way to debug the whole grammar (print out the debug info for every single `ParserElement` that tries to parse anything) in this way? If not, can we formalise it by having a `set_debug(recursive=True)` in the same way we have `leave_whitespace(recursive=True)`? 

I find this functionality to be quite critical to writing a grammar.

**Comment by ptmcg** [comment]
Sounds reasonable - have you tried this with a Forward expression? I'm curious if your debug() function loops forever.

I was just looking at ignore and leave_whitespace, and how they are handled in Forwards - the code looks broken in that it doesn't recurse into the contained expr (to avoid infinitely looping), but this feels like an error.  Those need more study.

I can do proper guarded recursion in Forward in a recursive set_debug(), and then see about what to do about the other recursive methods.

**Comment by multimeric** [comment]
That would be good. I'm not sure I have a solution for `Forward` because I'm not yet using it, but if you can work out an appropriate guard for `set_debug()`, can you not re-use that logic for `recurse()` more generally?

**Comment by ptmcg** [comment]
A related issue with this is that in the past people have had problems trying to sort out the nesting of messages in the debug output. I think there is even a pypi package for post-processing the output to do some form of nesting of the try-match-fail messages. (Hmm, a rich/textualize viewer would be interesting, which could support expand/collapse.)

**Comment by multimeric** [comment]
There are a lot of possible extensions, but imo the immediate issue is providing *all* the information to the user, and work out more targeted strategies later. One such strategy might be to print out the longest parse and why it failed, because I find that's often the most indicative.

**Comment by milahu** [comment]
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

when throwing that `debug` function at [class QmakeParser](https://code.qt.io/cgit/qt/qmake2cmake.git/tree/src/qmake2cmake/qmake_parser.py#n117)
which enables debug in `def add_element`, but only for some tokens

workaround: manually add `.set_debug()` to tokens of interest

**Comment by ptmcg** [comment]
When using this, probably good to also throw in a call to `autoname_elements`, to get decent debug labels.
