### ISSUE TITLE
infix_notation running out of stack

### ISSUE THREAD

**Issue by mishamsk** [pyparsing/pyparsing#403]
Hi,

I am building a grammar for a subset of SQL (or more specifically [SAS PROC SQL sql-expression](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/sqlproc/p020urejdmvi7vn1t9avbvazqapu.htm), which is an extension of ANSI SQL).

I've used infix_notation, however it generates what seems to be a very non-optimal parser. Specifically expressions like this in the infix_notation
`matchExpr = _FB(lastExpr + opExpr + lastExpr) + Group(
                        lastExpr + (opExpr + lastExpr)[1, ...]
                    )`  force parser to recurse and backtrack (due to Forward rules), which grows out of proportion for deep nested expressions. If set_debug is enabled, one can see how it forwards and then backs at least 3 times even for simplest expressions (except for a single term ones). I am not sure why the forwards are needed in the first place.

So even simple string like '`PUT(PUT(Personeelsnummer, z6.),$50.)`' would parse around a second (I am on MacBook Pro M1 Pro with 32gigs). And this string:
```
 WHEN DATEPART(W25LQE8.CMN30_PostDatum) ne DATEPART(W25LQE8.CMN30_AanmaakDatum) AND W25LQE8.CMN30_PostDatum ne .
     THEN   DATEPART(W25LQE8.CMN30_PostDatum)*60*60*24 + 60*60*10*1*1*1*1*1*1*1*1*1*1*1*1*1*1 /*Post eerdere datum dan gescand, dan 10 uur 's-ochtends op postdatum*/
    WHEN WKCAP6.SCAN_DTM_START_DTD ne . THEN WKCAP6.SCAN_DTM_START_DTD /*post op dezelfde dag binnen als gescand, dan eerste scandatum van de dag*/
    ELSE DATEPART(COALESCE(W25LQE8.CMN30_PostDatum, W25LQE8.CMN30_AanmaakDatum))*60*60*24 + 60*60*10 /*Als geen eerste scandatum van de dag, dan 10 uur s-ochtends*/
    END
```
would crash running out of stack with `RecursionError: maximum recursion depth exceeded`. Raising limit to 2000 `sys.setrecursionlimit(2000)` would allow it to parse...in 6 seconds!

So I just rebuilt infix_notation based on the original code and your own example with [numbers](https://github.com/pyparsing/pyparsing/blob/master/examples/fourFn.py) like so:

```
lastExpr = expr_term | (LPAR_SUP + expression + RPAR_SUP)

        # thisExpr = pp.Forward()
        for operDef in _gen_op_list():
            opExpr, arity, rightLeftAssoc, pa = (operDef + (None,))[:4]

            if arity == 3:
                opExpr1, opExpr2 = opExpr
                term_name = "{}{} term".format(opExpr1, opExpr2)
            else:
                term_name = "{} term".format(opExpr)

            if not 1 <= arity <= 3:
                raise ValueError("operator must be unary (1), binary (2), or ternary (3)")

            if rightLeftAssoc not in (pp.OpAssoc.LEFT, pp.OpAssoc.RIGHT):
                raise ValueError("operator must indicate right or left associativity")

            if arity == 1:
                if rightLeftAssoc is pp.OpAssoc.LEFT:
                    matchExpr = lastExpr + opExpr[...]
                elif rightLeftAssoc is pp.OpAssoc.RIGHT:
                    matchExpr = opExpr[...] + lastExpr
            elif arity == 2:
                matchExpr = lastExpr + (opExpr + lastExpr)[...]
            elif arity == 3:
                matchExpr = lastExpr + pp.Opt(opExpr1 + lastExpr + opExpr2 + lastExpr)
            if pa:
                if isinstance(pa, (tuple, list)):
                    matchExpr.set_parse_action(*pa)
                else:
                    matchExpr.set_parse_action(pa)
            thisExpr = matchExpr.setName(term_name)
            lastExpr = thisExpr
        expression <<= lastExpr
```
It _seems_ to be working (haven't thoroughly test it, but quick tests work) and is at least 10 times speedier and is not running out of stack.

Now I wonder if my implementation is not entirely correct and I am missing something?

**Comment by ptmcg** [comment]
a) Have you called `ParserElement.enable_packrat()`? This will make those repeated parses fast because they become cache lookups instead of re-parses.
b) The `_FB(lastExpr + opExpr + lastExpr)` terms are there to avoid calling parse actions at levels that don't actually have any operators. There is a prior issue about this (I checked the history, and it was prior to 2012).
c) Some parsers just require a deeper stack. There is nothing magic about the recursion limit of 1000, as long as there _is_ a limit that prevents memory exhaustion.

**Comment by mishamsk** [comment]
@ptmcg 
a) yep, it is enabled
b) hah, then I guessed it right. However, I think it would be a viable option to just document that parse_actions should expect single base_expr calls. It was a simple fix for me to start ignoring those (basically if `Len(tokens) == 1`: return'
c) yeah, it does make sense. What I am curious (as I am pretty new to this and you are a super expert!) if the modified version is correct or I may be missing some cases I haven't thought about or encountered yet. 

e.g. I removed the forward reference for thisExpr, cause I haven't figured our why with opAssoc.RIGHT it is necessary to reference this rather than last expression;-)

also, if you do think this version also makes sense, happy to create a pull request with additional docs and just making it an alternative option for infix_notation based on new parameter or otherwise

P.S. only started with pyparsing two weeks ago but already a huge fan of yours! Thanks a TON for your great work

**Comment by ptmcg** [comment]
You must have a hellish grammar for your `PUT(PUT(... etc.` example to take a second to parse. Is there a BNF you are working from? You may also have merged too many operators into a single infix_notation. For instance, if you are merging `AND/OR/NOT` operators with `+, -, *, /` operators, you might be better off defining a boolean infix notation separate from the arithmetic one, and only overlap when you need to include arithmetic as part of the boolean operand (as in `3-22*x > 100 AND x < 10`). I'm not totally sure this will speed things up, but it might, and will make your grammar more straightforward.

I've thought about an optimized version of infix_notation for those parsers that don't have parse actions. But there is also an impact on grouping. You don't want to parse "100" and get `[[[100]]]` just because there are 3 levels of operator precedence in your infix_notation expression.

Congrats on tackling and making such progress on so complicated a grammar with only 2 weeks of pyparsing! I just mentioned it briefly above, but I strongly suggest that parser developers write out a BNF (or find an official one if writing a parser for a defined language or SQL dialect or whatever) before diving in to writing code. This really helps in organizing your thinking about what you'll need in your parser, and how the pieces will fit together.

I'll look a little further at your alternative infix_notation implementation and see if anything jumps out at me. You could also use the tests that are written for pyparsing that use infix_notation and see how your version stacks up. If your parser code is in a repo somewhere, add a link to this issue and I might see if there is a place that would bear optimizing. (Also, check out this page of the pyparsing wiki: https://github.com/pyparsing/pyparsing/wiki/Performance-Tips)

**Comment by mishamsk** [comment]
@ptmcg thanks for the tips. I'll try the tests, great idea and also check the links. I haven't had issues with groups since I have "captive" parse_actions (each term becomes a class and operators convert into prefix notation with hierarchal tree).

Unfortunately the repo is private, it is an enterprise project at work. I can privately share the full grammar and parse_actions (classes) if you are curios.

I wish SAS published BNF... but probably in another life. I am out of time now to create one, but when we approach phase 2 - will definitely try!

btw. yeah, I have a lot of operators...here is the enum I use to construct the op_list:
```
class SAS_OPERARTOR(OperatorDefinition, enum.Enum):
    """A list of SAS PROC SQL supported operators

    From here https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/sqlproc/p020urejdmvi7vn1t9avbvazqapu.htm
    """

    PWR = OperatorDefinition(pp.CaselessLiteral("**"), 1, BINARY, pp.opAssoc.LEFT, tuple())
    UNARY_MINUS = OperatorDefinition(pp.CaselessLiteral("-"), 1, UNARY, pp.opAssoc.RIGHT, tuple())
    UNARY_PLUS = OperatorDefinition(pp.CaselessLiteral("+"), 1, UNARY, pp.opAssoc.RIGHT, tuple())
    MUL = OperatorDefinition(pp.CaselessLiteral("*"), 2, BINARY, pp.opAssoc.LEFT, tuple())
    DIV = OperatorDefinition(pp.CaselessLiteral("/"), 2, BINARY, pp.opAssoc.LEFT, tuple())
    ADD = OperatorDefinition(pp.CaselessLiteral("+"), 3, BINARY, pp.opAssoc.LEFT, tuple())
    SUB = OperatorDefinition(pp.CaselessLiteral("-"), 3, BINARY, pp.opAssoc.LEFT, tuple())
    CONCAT = OperatorDefinition(pp.CaselessLiteral("||"), 4, BINARY, pp.opAssoc.LEFT, tuple())
    BETWEEN = OperatorDefinition(
        (pp.CaselessKeyword("BETWEEN"), pp.CaselessKeyword("AND")), 5, TERNARY, pp.opAssoc.LEFT, tuple()
    )
    NOT_BETWEEN = OperatorDefinition(
        (pp.CaselessKeyword("NOT BETWEEN"), pp.CaselessKeyword("AND")), 5, TERNARY, pp.opAssoc.LEFT, tuple()
    )
    CONTAINS = OperatorDefinition(pp.CaselessKeyword("CONTAINS"), 5, BINARY, pp.opAssoc.LEFT, tuple())
    NOT_CONTAINS = OperatorDefinition(pp.CaselessKeyword("NOT CONTAINS"), 5, BINARY, pp.opAssoc.LEFT, tuple())
    # DISTINCT = OperatorDefinition(pp.CaselessKeyword("DISTINCT"), 5, UNARY, pp.opAssoc.RIGHT, tuple())
    EXISTS = OperatorDefinition(pp.CaselessKeyword("EXISTS"), 5, UNARY, pp.opAssoc.RIGHT, tuple())
    NOT_EXISTS = OperatorDefinition(pp.CaselessKeyword("NOT EXISTS"), 5, UNARY, pp.opAssoc.RIGHT, tuple())
    IN = OperatorDefinition(pp.CaselessKeyword("IN"), 5, BINARY, pp.opAssoc.LEFT, tuple())
    NOT_IN = OperatorDefinition(pp.CaselessKeyword("NOT IN"), 5, BINARY, pp.opAssoc.LEFT, tuple())
    # IS_TRUE = OperatorDefinition(pp.CaselessKeyword("IS TRUE"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    # IS_NOT_TRUE = OperatorDefinition(pp.CaselessKeyword("IS NOT TRUE"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    # IS_FALSE = OperatorDefinition(pp.CaselessKeyword("IS FALSE"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    # IS_NOT_FALSE = OperatorDefinition(pp.CaselessKeyword("IS NOT FALSE"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    IS_MISSING = OperatorDefinition(pp.CaselessKeyword("IS MISSING"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    IS_NOT_MISSING = OperatorDefinition(pp.CaselessKeyword("IS NOT MISSING"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    IS_NULL = OperatorDefinition(pp.CaselessKeyword("IS NULL"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    IS_NOT_NULL = OperatorDefinition(pp.CaselessKeyword("IS NOT NULL"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    # IS_UNKNOWN = OperatorDefinition(pp.CaselessKeyword("IS UNKNOWN"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    # IS_NOT_UNKNOWN = OperatorDefinition(pp.CaselessKeyword("IS NOT UNKNOWN"), 5, UNARY, pp.opAssoc.LEFT, tuple())
    # TODO: add terninary LIKE ESCAPE / NOT LIKE ESCAPE - must go higher than LIKE to match
    LIKE = OperatorDefinition(pp.CaselessKeyword("LIKE"), 5, BINARY, pp.opAssoc.LEFT, tuple())
    NOT_LIKE = OperatorDefinition(pp.CaselessKeyword("NOT LIKE"), 5, BINARY, pp.opAssoc.LEFT, tuple())

    EQ = OperatorDefinition(pp.CaselessLiteral("="), 6, BINARY, pp.opAssoc.LEFT, (pp.CaselessKeyword("EQ"),))
    NE = OperatorDefinition(
        pp.CaselessLiteral("!="),
        6,
        BINARY,
        pp.opAssoc.LEFT,
        (pp.CaselessKeyword("NE"), pp.CaselessLiteral("<>"), pp.CaselessLiteral("¬="), pp.CaselessLiteral("^=")),
    )
    GE = OperatorDefinition(pp.CaselessLiteral(">="), 6, BINARY, pp.opAssoc.LEFT, (pp.CaselessKeyword("GE"),))
    LE = OperatorDefinition(pp.CaselessLiteral("<="), 6, BINARY, pp.opAssoc.LEFT, (pp.CaselessKeyword("LE"),))
    LT = OperatorDefinition(pp.CaselessLiteral("<"), 6, BINARY, pp.opAssoc.LEFT, (pp.CaselessKeyword("LT"),))
    GT = OperatorDefinition(pp.CaselessLiteral(">"), 6, BINARY, pp.opAssoc.LEFT, (pp.CaselessKeyword("GT"),))
    # TODO: add: eqt ,gtt ,ltt ,get ,let ,net
    NOT = OperatorDefinition(
        pp.CaselessKeyword("NOT"), 9, UNARY, pp.opAssoc.RIGHT, (pp.CaselessLiteral("¬"), pp.CaselessLiteral("^"))
    )
    AND = OperatorDefinition(pp.CaselessKeyword("AND"), 7, BINARY, pp.opAssoc.LEFT, (pp.CaselessLiteral("&"),))
    OR = OperatorDefinition(pp.CaselessKeyword("OR"), 8, BINARY, pp.opAssoc.LEFT, (pp.CaselessLiteral("|"),))
```

**Comment by ptmcg** [comment]
Don't define keywords that are made of multiple words - this will defeat pyparsing's whitespace skipping.

I think you can do some collapsing of your precedence levels if you merge some of these, such as all the "IS" levels, something like this:

     IS, NOT, TRUE, FALSE, MISSING, UNKNOWN, NULL = map(CaselessKeyword,
            "IS NOT TRUE FALSE MISSING UNKNOWN NULL".split())

     IS_EXPR = IS + Opt(NOT) + (TRUE | FALSE | MISSING | UNKNOWN | NULL)

**Comment by mishamsk** [comment]
@ptmcg thanks! I guess I got a bit lazy rushing these ones in. I’ll need to refactor code that relies on my SAS_OPERATORS enum to make it work, but will definitely do!

I’ll keep you posted on how our testing of my stripped down infix_notation implementation goes…I have a feeling it may not work on some cases as it looks a bit too simple

**Comment by ptmcg** [comment]
Here are notes on defining phrases using multiple expressions instead of a single expression with embedded space: https://github.com/pyparsing/pyparsing/wiki/Common-Pitfalls-When-Writing-Parsers#literalif-not-should-be-literalif--literalnot

**Comment by mishamsk** [comment]
thanks!

**Comment by ptmcg** [comment]
Another place to economize on levels:

```
    UNARY_MINUS = OperatorDefinition(pp.CaselessLiteral("-"), 1, UNARY, pp.opAssoc.RIGHT, tuple())
    UNARY_PLUS = OperatorDefinition(pp.CaselessLiteral("+"), 1, UNARY, pp.opAssoc.RIGHT, tuple())
    MUL = OperatorDefinition(pp.CaselessLiteral("*"), 2, BINARY, pp.opAssoc.LEFT, tuple())
    DIV = OperatorDefinition(pp.CaselessLiteral("/"), 2, BINARY, pp.opAssoc.LEFT, tuple())
    ADD = OperatorDefinition(pp.CaselessLiteral("+"), 3, BINARY, pp.opAssoc.LEFT, tuple())
    SUB = OperatorDefinition(pp.CaselessLiteral("-"), 3, BINARY, pp.opAssoc.LEFT, tuple())
```
 do:

```
    UNARY_PLUS_MINUS = OperatorDefinition(pp.one_of("+ -"), 1, UNARY, pp.opAssoc.RIGHT, tuple())
    MUL_DIV = OperatorDefinition(pp.one_of("* /"), 2, BINARY, pp.opAssoc.LEFT, tuple())
    ADD_SUB = OperatorDefinition(pp.one_of("+ -"), 3, BINARY, pp.opAssoc.LEFT, tuple())
```

Collapse all your NOT-able operators:

```
    CONTAINS = OperatorDefinition(pp.CaselessKeyword("CONTAINS"), 5, BINARY, pp.opAssoc.LEFT, tuple())
    NOT_CONTAINS = OperatorDefinition(pp.CaselessKeyword("NOT CONTAINS"), 5, BINARY, pp.opAssoc.LEFT, tuple())
```

to

```
    NOT, CONTAINS = map(pp.CaselessKeyword("NOT CONTAINS".split())
    CONTAINS_OP = OperatorDefinition(pp.Optional(NOT) + CONTAINS, 5, BINARY, pp.opAssoc.LEFT, tuple())
```

And see if you can merge all your equality comparison operators down to a one or two levels (some operator precedence tables list == and != as higher precedence than >, <, etc.)

```
COMPARE_OP = OperatorDefinition(pp.one_of("= != < > <= >= EQ NE LT GT LE GE etc."), 6, BINARY, pp.opAssoc.LEFT, (pp.CaselessKeyword("GT"),))
```

**Comment by mishamsk** [comment]
@ptmcg I am definitely planning to collapse operators and precedence in that fashion, totally makes sense. The problem I had is that there is quite a lot of downstream code that needs to be adjusted based on this and as I’ve been having demos of the software for the last two weeks, I couldn’t get to “fixing” this.

but, surprisingly, it works reasonably well performance wise even in the current form. it will obviously fail the second we encounter more than one space between one of those compound operators (NOT LIKE etc.), but so far we’ve been doing demo’s on a limited set of code so it worked.

**Comment by ptmcg** [comment]
I think we've covered the major points here, so I'm going to close this issue. Feel free to reopen or open a new issue with follow-up questions.
