### ISSUE TITLE
No error reported when infix encounters duplicate operator

### ISSUE THREAD

**Issue by mueller55** [pyparsing/pyparsing#404]
I am using pyparsing to build a simple formula parser.  The grammar is:

constant = TRUE | FALSE 
ident = ~keyword + Word(alphas, alphanums + "_")
unit = constant | ident
UNARY, BINARY = 1, 2
formula = infixNotation(
    unit,
    [
        (AND, BINARY, opAssoc.LEFT, ast.make_and), 
        (OR, BINARY, opAssoc.LEFT, ast.make_or),
    ]
)

When I try to parse a string in which the operator occurs twice, I get not error message. For instance, 
  formula.parseString('a or or b')
parses without error, but the resulting result contains only 'b'. Note that the action ast.make_or is NOT called.

Is this a bug or an error in my code?

**Comment by ptmcg** [comment]
Are AND and OR included in your definition of keyword?

**Comment by ptmcg** [comment]
After adding AND and OR to the list of keywords, I get the expected error with "a or or b":

``` python
from pyparsing import *


TRUE, FALSE, AND, OR = keywords = list(map(CaselessKeyword, "TRUE FALSE AND OR".split()))
keyword = MatchFirst(keywords)

constant = TRUE | FALSE

ident = ~keyword + Word(alphas, alphanums + "_")
unit = constant | ident
UNARY, BINARY = 1, 2
formula = infixNotation(
    unit,
    [
        (AND, BINARY, opAssoc.LEFT, ), #ast.make_and),
        (OR, BINARY, opAssoc.LEFT, ), #ast.make_or),
    ]
)

formula.runTests("""\
a or b
a or or b
""")

```
prints:
```
a or b
[['a', 'OR', 'b']]
[0]:
  ['a', 'OR', 'b']

a or or b
a or or b
  ^
ParseException: Expected end of text, found 'or'  (at char 2), (line:1, col:3)
FAIL: Expected end of text, found 'or'  (at char 2), (line:1, col:3)
```

**Comment by ptmcg** [comment]
Closing for now - please reopen if this does not address the problem.
