### ISSUE TITLE
pkg_resources._vendor.pyparsing.diagram raised: FileNotFoundError: template.jinja2

### ISSUE THREAD

**Issue by netmonitoring** [pyparsing/pyparsing#419]
PYInstaller version: 5.1
pyparsing version: 3.0.9
setuptools version: 62.6.0
wheel version: 0.37.1
pip version: 22.1.2

Warning occurs creating python executable file:

> WARNING: Failed to collect submodules for 'pkg_resources._vendor.pyparsing.diagram' because importing 'pkg_resources._vendor.pyparsing.diagram' raised: FileNotFoundError: [Errno 2] No such file or directory: 'C:/python/Lib/site-packages/pkg_resources/_vendor/pyparsing/diagram/template.jinja2'

Is it critical? Does this issue is known? How to fix it?

**Comment by ptmcg** [comment]
That file was removed in pyparsing 3.0.9. There should be no references to that file using the latest pyparsing.

**Comment by netmonitoring** [comment]
> That file was removed in pyparsing 3.0.9. There should be no references to that file using the latest pyparsing.

But it is... all modules are downloaded using pip.

**Comment by ptmcg** [comment]
If you are not using any of the new features in pyparsing 3.0.9, then you can use 3.0.8 until setuptools/pkg_resources catches up with their vendored version.

**Comment by netmonitoring** [comment]
Either rollback to older version or manually change necessary places in the source code. However this is not good, when official 
 latest python version contains such problems.

**Comment by ptmcg** [comment]
Please try updating to the latest version of setuptools - they have had several releases since you opened this ticket, hopefully they have addressed your issue.

**Comment by jpp08022002** [comment]
I have the same issue, this should be fixed, because it's a very important problem. Now I can't load a submodule

**Comment by ptmcg** [comment]
@jpp08022002  and @netmonitoring  - please add more details on the issue I opened on your behalf on the pypa/setuptools project: https://github.com/pypa/setuptools/issues/3451

**Comment by ptmcg** [comment]
Resolved in setuptools update
