### ISSUE TITLE
Slight documentation change to oneOf

### ISSUE THREAD

**Issue by vaughnkoch** [pyparsing/pyparsing#42]
The documentation for oneOf is correct, but it's easy to get tripped up by the following code:

```
from pyparsing import *

# Fails
expr = oneOf('count', 'sum')

# Works
expr = oneOf(['count', 'sum'])

def parse_expression(_input):
  results = expr.parseString(_input)
  print(results.dump())


parse_expression('sum')
```

That's just because oneOf takes a list object and not several parameters. It might be helpful to include a short note that you can't call it like I tried to above.

Great library, btw :)

**Comment by Freakwill** [comment]
It is not a serious problem, It just behaves like function `sum`.
Good idea, btw ;)

**Comment by eswald** [comment]
I also ran into this.  It might be better to have the `caseless` and `useRegex` parameters be keyword-only, probably in a major release bump.  (Python 3 offers a more convenient syntax for that, so it could be done when legacy Python support is dropped.)  An even later release could then support the attempted usage, unless you want to support both at once via type checking and a deprecation warning.

**Comment by ptmcg** [comment]
The next release will emit a user warning at parser creation time if this error is detected.

**Comment by ptmcg** [comment]
New 2.4.1 release includes `__diag__.warn_on_multiple_string_args_to_oneof` to warn when this happens in your code..
