### ISSUE TITLE
pkg_resources._vendor.pyparsing.diagram raised: AttributeError: module 'railroad' has no attribute 'DiagramItem'

### ISSUE THREAD

**Issue by netmonitoring** [pyparsing/pyparsing#420]
PYInstaller version: 5.1
pyparsing version: 3.0.9
setuptools version: 62.6.0
wheel version: 0.37.1
pip version: 22.1.2
raiload version: 0.5.0
railroad-diagrams version: 1.1.1

Warning occurs creating python executable file:

> WARNING: Failed to collect submodules for 'pkg_resources._vendor.pyparsing.diagram' because importing 'pkg_resources._vendor.pyparsing.diagram' raised: AttributeError: module 'railroad' has no attribute 'DiagramItem'

Does this issue is known? How to fix it?

**Comment by ptmcg** [comment]
Did this clear up your issue?

**Comment by netmonitoring** [comment]
Yes, thank you for clarification.
