### ISSUE TITLE
`pyparsing.python_style_comment.suppress()` does not work with multi-line strings

### ISSUE THREAD

**Issue by Andi144** [pyparsing/pyparsing#421]
Consider this MWE:

```python
import pyparsing

code = '"""this is a\nmulti-line  # not an actual comment\nstring"""'

comment_filter = pyparsing.python_style_comment.suppress()
print(comment_filter.transform_string(code))
```

where `code` is a valid Python program that contains only a single multi-line string:

```python
"""this is a
multi-line  # not an actual comment
string"""
```

This string contains a `#` character, but since it is within the string, it should not be treated as a comment. `pyparsing` does so, however. Output of the above MWE:

```python
"""this is a
multi-line
string"""
```

where `# not an actual comment` has been incorrectly removed.

**Comment by ptmcg** [comment]
This is correct. python_style_comment does not contain any additional knowledge about the context in which it is being used, this is something you need to add in your grammar.

You can do this by using the `ignore()` method on any `ParserElement`:

```python
any_python_quoted_string = (
	pyparsing.QuotedString('"""', multiline=True)
	| pyparsing.QuotedString("'''", multiline=True)
	| pyparsing.QuotedString('"')
	| pyparsing.QuotedString("'")
)
comment_filter.ignore(any_python_quoted_string)
```

**Comment by Andi144** [comment]
Thanks for the fast reply! This does, of course, make sense. Apparently, I just read `python_style_comment` and wrongly thought that this works on all Python code. I think this issue can be closed, as it effectively is just a mistake on my side.
