### ISSUE TITLE
Operators should return `NotImplemented` rather than raise `TypeError`

### ISSUE THREAD

**Issue by djpohly** [pyparsing/pyparsing#424]
The overloaded operators for `ParserElement`s should [return `NotImplemented`](https://docs.python.org/3/library/constants.html#NotImplemented) rather than raising an exception, unless the intent is to prevent anyone from implementing other types which can be combined with `ParserElement`s.  (Even then, you can only stop it if you're the first operand.)  For a silly example:
```python
>>> class ThreeSir:
...   def __add__(self, other):
...     return 3
...   def __radd__(self, other):
...     return 3
...
>>> five = ThreeSir()
>>> "1 2" + five
3
>>> 1 + 2 + five
3
>>> Literal("three") + five
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/djpohly/src/pyparsing/pyparsing/core.py", line 1395, in __add__
    raise TypeError(
TypeError: Cannot combine element of type ThreeSir with ParserElement
>>> five + Literal("three")
3
```

**Comment by ptmcg** [comment]
This is nice! I had to look it up in the docs, all this time I've been raising TypeError!
