### ISSUE TITLE
booleansearchparser.py fails on Python 3.11 b03

### ISSUE THREAD

**Issue by ptmcg** [pyparsing/pyparsing#428]
The latest version of pyparsing fails when running the booleansearchparser.py example, with this exception:

```
C:\Python3_11\python.exe M:/dev/pyparsing/gh/pyparsing/examples/booleansearchparser.py
Traceback (most recent call last):
  File "M:\dev\pyparsing\gh\pyparsing\examples\booleansearchparser.py", line 451, in <module>
    main()
    ^^^^^^
  File "M:\dev\pyparsing\gh\pyparsing\examples\booleansearchparser.py", line 443, in main
    if ParserTest().Test():
       ^^^^^^^^^^^^^^^^^^^
  File "M:\dev\pyparsing\gh\pyparsing\examples\booleansearchparser.py", line 395, in Test
    if self.match(text, expr):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\dev\pyparsing\gh\pyparsing\examples\booleansearchparser.py", line 317, in match
    return self.Parse(expr)
           ^^^^^^^^^^^^^^^^
  File "M:\dev\pyparsing\gh\pyparsing\examples\booleansearchparser.py", line 264, in Parse
    return self.evaluate(self._parser(query)[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\dev\pyparsing\gh\pyparsing\examples\booleansearchparser.py", line 261, in evaluate
    return self._methods[argument.getName()](argument)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: None
```

If the `__slots__` attribute on ParseBaseException in exceptions.py is removed, this error goes away.

Occurs on both Windows and Ubuntu.

Python 3.10 does not have this problem.

**Comment by vegard** [comment]
Bisected to https://github.com/python/cpython/commit/b9ebde8db7e176e021103745cd012bae700828b5

**Comment by ptmcg** [comment]
Thanks for pinning this down - I've tried to repro on 3.11b3 with small parsers, but have not succeeded. Is this enough to open a ticket on CPython?

**Comment by ptmcg** [comment]
Thanks for pinning this down @vegard - I've tried to repro on 3.11b3 with small parsers, but have not succeeded. Is this enough to open a ticket on CPython?

**Comment by ptmcg** [comment]
Another related factor: if reading .pyc's from `__pycache__` directory, there is no error. But after clearing the cache directory and running new, the exception occurs.

**Comment by ptmcg** [comment]
Found the bug. Adding `__slots__` makes ParseResults more easily garbage-collected. In this one case, a nested ParseResults was passed without its parent, the parent got gc'ed, and a weakref parent pointer changed to None. Solution is to make the parent pointer a regular ref, not a weakref.
