### ISSUE TITLE
ParseResults.as_dict() of Dict(asdict=True) gives empty dictionary

### ISSUE THREAD

**Issue by grv87** [pyparsing/pyparsing#431]
When `Dict` was constructed with `asdict=True`, calling it's `ParseResults.as_dict()` gives empty dictionary.

Maybe I don't understand the wording of documentation. Docstring says:
> The optional ``asdict`` argument when set to True will return the
> parsed tokens as a Python dict instead of a pyparsing ParseResults

It confuses me. What should return Python `dict`? `parse_string` always returns `ParseResults`.

BTW, [online documentation](https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#id13) incorrectly names this arg as `aslist`:
> the Dict class … when constructed with `aslist=True`, will return an actual Python `dict` instead of a ParseResults

My test case:

```python
from pyparsing import *
s = """
A 1
B 2
"""
item01 = Group(Keyword("A") + pyparsing_common.integer)
item02 = Group(Keyword("B") + pyparsing_common.integer)
def parse_and_print(case_name, ast):
    print(case_name)
    r = ast.parse_string(s, parse_all=True)
    print(r.__class__)
    print(r.as_list())
    print(r.as_dict())
parse_and_print("dict", Dict(item01 + item02))
parse_and_print("dict_as_dict", Dict(item01 + item02, asdict=True))
```

Gives

```
# dict
# <class 'pyparsing.results.ParseResults'>
# [['A', 1], ['B', 2]]
# {'A': 1, 'B': 2}
# dict_as_dict
# <class 'pyparsing.results.ParseResults'>
# [{'A': 1, 'B': 2}]
# {}
```

Regardless of documentation, behavior suggests that setting `asdict=True` helps to avoid additional `as_dict` call, after `parse_string` or in parse action. This holds true:
```
Dict(item01 + item02).parse_string(s).as_dict() == Dict(item01 + item02, asdict=True).parse_string(s).as_list()[0]
```
But if that's the correct behavior, then additional casting (`as_dict` call) on something that is a dict already (Dict that has `asdict=True` set) should produce the same result. The last call should've given `{'A': 1, 'B': 2}`.

Context: I'd like to use a parser as standalone (for testing) and as a sub-parser in a longer expression. To reuse it in another expression, I'd like to set `asdict=True` to avoid custom parser action. And to test this parser as standalone, I'd like to make a simple call of `assertParseAndCheckDict` and to avoid wrapping expected dict in list.

**Comment by ptmcg** [comment]
I'm sorry for the confusion (and thanks for pointing the typo in the docs!).

Some of the confusion may be that `ParseResults` itself can look like a list, or like a dict if there are named results (or like an object with attributes also).

Normally, named results are created using `setResultsName`, or its () call equivalent. As you show in your test, the `Dict` class allows you to dynamically create named results using parsed values as the keys, and this will return a `ParseResults` with keys and values parsed directly from the input. Your code returns a `ParseResults` with keys "A" and "B". In this case, the `Dict` gives us a `ParseResults`, and so it does not need to be wrapped further in order for `parse_string` to return a `ParseResults`.

When you set `asdict=True`, then the `Dict` expression gives us a dict. For `parse_string` to return a `ParseResults`, it wraps that object in a `ParseResults`, and again as you found, that `ParseResults` 0'th item is the desired dict (and in your "This holds true:" code, ".as_list()" is unnecessary).

`ParseResults.as_dict()` implements the logic that, for all named results in it, it will build a dict with those names, and the associated named results as the respective values. In your second `parse_and_print` case, the `ParseResults` has no results names - it is a "list" of parsed items, the first of which happens to be a dict.

It is possible to create dicts as parsed items in a `ParseResults` in other ways, such as this:

```python
word = Word(alphanums)
word_pair = (word + word).add_parse_action(lambda tokens: {tokens[0]: tokens[1]})
parse_and_print("plain old word", word_pair[...])
```
With your input string, the results are:
```
[{'A': '1'}, {'B': '2'}]
```
That is, a sequence of two dicts. If you add this line to your `parse_and_print` function:
```
    print(type(r[0]), r[0])
```
You'll see that these are plain old dicts, just like the output from the `Dict` with `asdict=True`.

If you are returning a dict from a `Dict` expression with `asdict=True`, then you should call `assertParseAndCheckList`, validating against a list with a single value, your dict with keys "A" and "B":  `[{'A': 1, 'B': 2}]`.

**Comment by grv87** [comment]
> If you are returning a dict from a `Dict` expression with `asdict=True`, then you should call `assertParseAndCheckList`

This is really confusing.
But if it's by design, could you include it in the docs or the wiki, please?

**Comment by ptmcg** [comment]
Closing this issue, as I've updated the docs for the next release. Thanks for pointing out the need for clarification on this.
