### ISSUE TITLE
Broken link on docs---articles--blog-posts

### ISSUE THREAD

**Issue by m1lt0n** [pyparsing/pyparsing#438]
The link to my blog post (Pantelis Vratsalis) is now: https://m1lt0n.github.io/python/parsing/pyparsing/mini-query-language-with-python-and-pyparsing/

**Comment by ptmcg** [comment]
Corrected, thanks!

**Comment by ptmcg** [comment]
Sorry for the delay, pyparsing has taken a back seat to some personal and work issues these past couple of months, thanks for being patient.
