### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'pyparsing' (unknown location) python

### ISSUE THREAD

**Issue by gillian911911** [pyparsing/pyparsing#439]

**Comment by gillian911911** [comment]
File "D:\anaconda3\envs\torch12\lib\site-packages\matplotlib\fontconfig_pattern.py", line 15, in <module>
    from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
ImportError: cannot import name 'Literal' from 'pyparsing' (unknown location)

could you please provide some help? thanks

**Comment by ptmcg** [comment]
Literal has been in every version of pyparsing as far back as 0.9, so I suspect there is something in your PYTHONPATH  that is masking that module. Do you possibly have a pyparsing.py script somewhere in your development directories?

**Comment by ptmcg** [comment]
Closing this for now - please reopen if you have further notes on how to reproduce this issue.

Thanks for using pyparsing!
