### ISSUE TITLE
Enabling continuous fuzzing by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [pyparsing/pyparsing#441]
Hi,

I was wondering if you would like to integrate continuous fuzzing by way of OSS-Fuzz? Fuzzing is a way to automate test-case generation and can be used to find unexpected exceptions in Python. In this PR https://github.com/google/oss-fuzz/pull/8266 I did an initial integration into OSS-Fuzz and the [current fuzzer](https://github.com/google/oss-fuzz/pull/8266/files#diff-f120d759af570fd2d60cca85dd46ee774f4d699f639b71ffbb56e81bef76168d) creates a random parser and tries parsing random data. The fuzzing engine used by OSS-Fuzz is [Atheris](https://github.com/google/atheris).

If you would like to integrate, the only thing I need is a list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by ptmcg** [comment]
I have learned again and again that pyparsing has corner cases of corner cases, so a test generator sounds very interesting.  When you generate a random parser, how do you know what random inputs are supposed to be parseable, and what they are supposed to parse to?

Let's just start with my email, which is included in pyparsing's metadata as the author email. It will be interesting to see where this goes.

**Comment by DavidKorczynski** [comment]
I added the email, so far no issues found!
