### ISSUE TITLE
Clarify that `expr * ...` is also valid

### ISSUE THREAD

**Issue by anntzer** [pyparsing/pyparsing#445]
AFAICT, `__mul__` and `__getitem__` mostly share their implementation, and thus `expr * ...` is also a valid way of spelling `ZeroOrMore(expr)` (aka `expr[...]`); I also happen to find this spelling rather more intuitive.  But the documentation seems to suggest that Ellipsis is only valid for `__getitem__` (Ellipsis is only mentioned for `__getitem__` at https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#expression-operators, and not at https://pyparsing-docs.readthedocs.io/en/latest/pyparsing.html#pyparsing.ParserElement.__mul__); perhaps the docs could be slightly reworded to clarify the situation?

**Comment by ptmcg** [comment]
I just tried it, there's nothing wrong with this format. I probably ignored it because I feel like I would like to steer people away from the multiplication form and use the getitem form. But the two will definitely coexist for a while. I'll add a mention of `expr * ...` to the docs, thanks!

**Comment by anntzer** [comment]
Just out of curiosity, is there a reason you prefer indexing notation? I guess it mimics brace notation in regexes, but 1) even though I am familiar with it, it is probably less well known in the python world and 2) the usual semantics of indexing in python are so different that I still find that use a bit jarring (whereas overloading multiplication to mean repetition is present even on built-in types).

**Comment by ptmcg** [comment]
Good points. After adding the indexing notation, multiplying by ints or tuples just felt hacky to me. But in the sense of "explicit is better than implicit"  doing `expr * (1, 3)` is clearly doing multiplication by something with two values, easily inferred as min and max, vs `expr[1, 3]`, which is actually surreptitiously doing `expr[(1,3)]` and if ':' is used, it is as a sentinel. Do you think I should backport that sentinel aspect to the multiplication form as an optional third item of the tuple?  (Looking at the docs now, I see that I even removed the examples of multiplication by tuples - it is only mentioned in the paragraph as an option.

**Comment by anntzer** [comment]
I have never used stop_on, so I don't have any intuition there.
I guess "normal" Python semantics would have been that `expr[m:n]` mean the same as `expr[m] | expr[m+1] | ... | expr[n-1]` i.e. from m to n-1 repetitions, but I guess that ship has sailed a long time ago.  (But please also take that with a grain of salt, as I have no experience with designing DSLs for PEGs.)

**Comment by anntzer** [comment]
Closed by e6c7783, afaict.  Thanks :)
