### ISSUE TITLE
Problem parsing strings that are single quoted and ends with double single escaped quote character

### ISSUE THREAD

**Issue by lcarlier** [pyparsing/pyparsing#45]
Hi,
I'm trying to parse the following string in Python with pyparser.
This is part of a much more complicated use case and I've extracted the relevant part here.

```
>>> from pyparsing import QuotedString
>>> QUOTED_STRING = QuotedString("'", escChar=("''"), unquoteResults=False)
>>> stringToParse = "'A string that ''ends'' with double single quotes ''1'''"
>>> val = QUOTED_STRING.parseString(stringToParse).asList()
>>> print val[0]
'A string that ''ends'' with double single quotes ''1'
>>> import pyparsing
>>> print pyparsing.__version__
2.3.1
```
The problem here is that I'm expecting to get the string 
`'A string that ''ends'' with double single quotes ''1'''`
but val[0] equals the following in my case
`'A string that ''ends'' with double single quotes ''1'`

Is this a bug? or do I miss something here?
Kind regards,
Laurent

**Comment by lcarlier** [comment]
Hi,
I missed the escQuote paremeter

```
>>> from pyparsing import QuotedString
>>> QUOTED_STRING = QuotedString("'", escQuote=("''"), unquoteResults=False)
>>> stringToParse = "'A string that ''ends'' with double single quotes ''1'''"
>>> val = QUOTED_STRING.parseString(stringToParse).asList()
>>> print val[0]
```
I'm using it and the issue is solved.
Kind regards,
Laurent

**Comment by ptmcg** [comment]
Glad to see you were able to resolve your issue!
