### ISSUE TITLE
instring.expandtabs() called on None

### ISSUE THREAD

**Issue by WolfgangFahl** [pyparsing/pyparsing#452]
My CI tests fail on Windows and Ubuntu but not on MacOS:

pyparsing/core.py", line 1129, in parse_string
instring = instring.expandtabs()
AttributeError: 'NoneType' object has no attribute 'expandtabs'

**Comment by WolfgangFahl** [comment]
happens when trying to parse a None text - I'd expect to get an exception or warning earlier.

**Comment by ptmcg** [comment]
Why would you pass None to a method that takes a string? And I'm curious as to how this is not raising the same exception on MacOS.

I'm genuinely baffled with this question. When I learned Python, the sentiment was that the library developer and library user were "consenting adults", and the user would use the library in the way it was defined. I'm pretty sure you'll find that there is almost no type checking in pyparsing of the kind you seem to be expecting.

I have started adding type annotations to pyparsing's publicly facing methods. These should help you identify invalid usages of those methods in your code, either flagged by your IDE or by static type checkers such as mypy.

**Comment by WolfgangFahl** [comment]
@ptmcg  indeed i did not intend to send a None value it was a glitch in my testcases. It is just confusing to get an error message from somewhere in the middle of another library instead of an reaction that returns a None, an exception or anything else more robust. That's why i pointed it out here. See e.g. the https://en.wikipedia.org/wiki/Robustness_principle which didn't work in the cooperation of the libraries here because my part was  not conservative enough and yours not liberal enough.

**Comment by ptmcg** [comment]
Any idea why your tests on MacOS didn't have the same error?

**Comment by ptmcg** [comment]
I'm familiar with that principle, my thesis advisor referred to it as the Telegrapher's Principle (I may be misremembering this, google does not turn anything up by that name). In this case, perhaps my code is being too liberal.

Still, I am loath to start dropping in run-time type checks for strs to emit TypeErrors. It is easy to overly-restrict an interface in Python - screening for list when any collection type or generator expression will do, for instance. I _could_ add them in cases like `parse_string` (and `search_string`, `scan_string`, and `transform_string`), but I think that will then set an expectation that _all_ the public interfaces will do this kind of screening.

**Comment by WolfgangFahl** [comment]
If you close this issue people will still find a hint now when searching the internet which is a better situation then when i tried to find out what was wrong :-)

**Comment by ptmcg** [comment]
We all do our parts, thanks for using pyparsing!

**Comment by WolfgangFahl** [comment]
By the way the reason the problem didn't show up on MacOS was that the input was available on the computer i tried it out which is my personal laptop. The CI didn't even bother to test MacOS any more after it found a failure in another OS so it was my logical thinking error to assume that MacOS would work in the CI :-) It was the inavailability of any input at all sending None to the parser that caused the problem as discussed above. So the quality principle is "always check your assumptions - they might be wrong ..."
