### ISSUE TITLE
parseString  Cannot contain "True" ??

### ISSUE THREAD

**Issue by WheatMaThink** [pyparsing/pyparsing#467]
hi friend

pyparsing version :3.0.9 

Please help to see the output of the code

```python
import pyparsing as pp

name = 'SET'
action = pp.CaselessKeyword(name).setResultsName("action")
baseExpr = action + pp.CharsNotIn(name).setResultsName("other")

source = "set one:value;two:true;three:False;four:True;five:value"

result = baseExpr.parseString(source)

print(result)
['SET', ' one:value;two:true;three:False;four:']
```                        
four: Cannot contain "True" ?

**Comment by ptmcg** [comment]
The leading 'T' of 'True' is in 'SET', so the CharsNotIn expression will stop there.  Try changing to "true" instead of "True" to see the difference.

Why are you using CharsNotIn for that second expression.

**Comment by WheatMaThink** [comment]
@ptmcg 

Thank you, I've now understood!
