### ISSUE TITLE
"" as add_parse_action's result removes result name from ParseResults

### ISSUE THREAD

**Issue by niccokunzmann** [pyparsing/pyparsing#470]
It might be a use-case to remove the result name from the `ParseResults` in a parse action. However, it looks a bit like an inconsistency to me: `""` removes the named value but a filled string does not.

Tests:
```
import pyparsing as pp
import pytest


def assert_X_is_present(grammar, X):
    """Check that X is present and has a certain value."""
    parse_results = grammar.parse_string("a")
    print(parse_results, list(parse_results.items()))
    assert "X" in parse_results, f"value = {repr(X)}"
    assert parse_results["X"] == X

@pytest.mark.parametrize("value", 
    [
        "x",
        "",  # removes named value
        True,
        False,
        1,
        0,
        None, # consistent with test_no_parse_action 
        b"",
        b"a",
    ]
)
def test_with_parse_action(value):
    """Check which values are in the named result."""
    print("value =", repr(value))
    grammar = (pp.Suppress("a") + pp.ZeroOrMore("x")).add_parse_action(lambda p: value).set_results_name("X")
    assert_X_is_present(grammar, value)


def test_no_parse_action():
    """Do not add a parse result."""
    grammar = (pp.Suppress("a") + pp.ZeroOrMore("x")).set_results_name("X")
    assert_X_is_present(grammar, "")

```

These are the tests running:

<pre><font color="#FFFFFF"><b>py39 installed: attrs==22.2.0,black==23.1.0,cffi==1.15.0,click==8.1.3,coverage==6.5.0,cssselect==1.2.0,distlib==0.3.6,exceptiongroup==1.1.0,filelock==3.9.0,greenlet==0.4.13,hpy==0.0.3,iniconfig==2.0.0,inkex @ git+https://gitlab.com/inkscape/extensions@b47d2bc6b11595cd6ecbf4d16aa59d9f5e597141,lxml==4.9.2,mypy-extensions==1.0.0,numpy==1.24.2,packaging==23.0,pathspec==0.11.0,Pillow==9.4.0,platformdirs==3.0.0,pluggy==1.0.0,py==1.11.0,pycairo==1.23.0,pycparser==2.21,PyGObject==3.42.2,pyparsing==3.0.9,pypdf==3.5.0,pyserial==3.5,pytest==7.2.1,pytest-cov==3.0.0,readline==6.2.4.1,scour==0.37,six==1.16.0,tomli==2.0.1,tox==3.28.0,typing_extensions==4.5.0,virtualenv==20.19.0,zstandard==0.20.0</b></font>
<font color="#FFFFFF"><b>py39 run-test-pre: PYTHONHASHSEED=&apos;1228586876&apos;</b></font>
<font color="#FFFFFF"><b>py39 run-test: commands[0] | pytest tests/test_pyparsing.py</b></font>
<font color="#FFFFFF"><b>============================ test session starts =============================</b></font>
platform linux -- Python 3.9.12[pypy-7.3.9-final], pytest-7.2.1, pluggy-1.0.0
cachedir: .tox/py39/.pytest_cache
rootdir: /home/sabin/extension-ai, configfile: pyproject.toml
plugins: cov-3.0.0
<font color="#FFFFFF"><b>collected 10 items                                                           </b></font>

tests/test_pyparsing.py <font color="#44AA44">.</font><font color="#AA0000">F</font><font color="#44AA44">....</font><font color="#AA0000">F</font><font color="#44AA44">..</font><font color="#AA0000">F</font>

================================== FAILURES ==================================
<font color="#FF8787"><b>_________________________ test_with_parse_action[0] __________________________</b></font>

value = &apos;&apos;

    @pytest.mark.parametrize(&quot;value&quot;,
        [
            &quot;x&quot;,
            &quot;&quot;,  # removes named value
            True,
            False,
            1,
            0,
            None, # consistent with test_no_parse_action
            b&quot;&quot;,
            b&quot;a&quot;,
        ]
    )
    def test_with_parse_action(value):
        &quot;&quot;&quot;Check which values are in the named result.&quot;&quot;&quot;
        print(&quot;value =&quot;, repr(value))
        grammar = (pp.Suppress(&quot;a&quot;) + pp.ZeroOrMore(&quot;x&quot;)).add_parse_action(lambda p: value).set_results_name(&quot;X&quot;)
&gt;       assert_X_is_present(grammar, value)

<font color="#FF8787"><b>tests/test_pyparsing.py</b></font>:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

grammar = {Suppress:(&apos;a&apos;) [&apos;x&apos;]...}, X = &apos;&apos;

    def assert_X_is_present(grammar, X):
        &quot;&quot;&quot;Check that X is present and has a certain value.&quot;&quot;&quot;
        parse_results = grammar.parse_string(&quot;a&quot;)
        print(parse_results, list(parse_results.items()))
&gt;       assert &quot;X&quot; in parse_results, f&quot;value = {repr(X)}&quot;
<font color="#FF8787"><b>E       AssertionError: value = &apos;&apos;</b></font>
<font color="#FF8787"><b>E       assert &apos;X&apos; in ParseResults([&apos;&apos;], {})</b></font>

<font color="#FF8787"><b>tests/test_pyparsing.py</b></font>:10: AssertionError
---------------------------- Captured stdout call ----------------------------
value = &apos;&apos;
[&apos;&apos;] []
<font color="#FF8787"><b>________________________ test_with_parse_action[None] ________________________</b></font>

value = None

    @pytest.mark.parametrize(&quot;value&quot;,
        [
            &quot;x&quot;,
            &quot;&quot;,  # removes named value
            True,
            False,
            1,
            0,
            None, # consistent with test_no_parse_action
            b&quot;&quot;,
            b&quot;a&quot;,
        ]
    )
    def test_with_parse_action(value):
        &quot;&quot;&quot;Check which values are in the named result.&quot;&quot;&quot;
        print(&quot;value =&quot;, repr(value))
        grammar = (pp.Suppress(&quot;a&quot;) + pp.ZeroOrMore(&quot;x&quot;)).add_parse_action(lambda p: value).set_results_name(&quot;X&quot;)
&gt;       assert_X_is_present(grammar, value)

<font color="#FF8787"><b>tests/test_pyparsing.py</b></font>:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

grammar = {Suppress:(&apos;a&apos;) [&apos;x&apos;]...}, X = None

    def assert_X_is_present(grammar, X):
        &quot;&quot;&quot;Check that X is present and has a certain value.&quot;&quot;&quot;
        parse_results = grammar.parse_string(&quot;a&quot;)
        print(parse_results, list(parse_results.items()))
        assert &quot;X&quot; in parse_results, f&quot;value = {repr(X)}&quot;
&gt;       assert parse_results[&quot;X&quot;] == X
<font color="#FF8787"><b>E       assert ParseResults([], {}) == None</b></font>

<font color="#FF8787"><b>tests/test_pyparsing.py</b></font>:11: AssertionError
---------------------------- Captured stdout call ----------------------------
value = None
[] [(&apos;X&apos;, ParseResults([], {}))]
<font color="#FF8787"><b>____________________________ test_no_parse_action ____________________________</b></font>

    def test_no_parse_action():
        &quot;&quot;&quot;Do not add a parse result.&quot;&quot;&quot;
        grammar = (pp.Suppress(&quot;a&quot;) + pp.ZeroOrMore(&quot;x&quot;)).set_results_name(&quot;X&quot;)
&gt;       assert_X_is_present(grammar, &quot;&quot;)

<font color="#FF8787"><b>tests/test_pyparsing.py</b></font>:36: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

grammar = {Suppress:(&apos;a&apos;) [&apos;x&apos;]...}, X = &apos;&apos;

    def assert_X_is_present(grammar, X):
        &quot;&quot;&quot;Check that X is present and has a certain value.&quot;&quot;&quot;
        parse_results = grammar.parse_string(&quot;a&quot;)
        print(parse_results, list(parse_results.items()))
        assert &quot;X&quot; in parse_results, f&quot;value = {repr(X)}&quot;
&gt;       assert parse_results[&quot;X&quot;] == X
<font color="#FF8787"><b>E       AssertionError: assert ParseResults([], {}) == &apos;&apos;</b></font>

<font color="#FF8787"><b>tests/test_pyparsing.py</b></font>:11: AssertionError
---------------------------- Captured stdout call ----------------------------
[] [(&apos;X&apos;, ParseResults([], {}))]
<font color="#AA5500">============================== warnings summary ==============================</font>
&lt;frozen importlib._bootstrap&gt;:228
  &lt;frozen importlib._bootstrap&gt;:228: ImportWarning: can&apos;t resolve package from __spec__ or __package__, falling back on __name__ and __path__

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
<font color="#4CCCE6"><b>========================== short test summary info ===========================</b></font>
<font color="#AA0000">FAILED</font> tests/test_pyparsing.py::<font color="#FFFFFF"><b>test_with_parse_action[0]</b></font> - AssertionError: value = &apos;&apos;
<font color="#AA0000">FAILED</font> tests/test_pyparsing.py::<font color="#FFFFFF"><b>test_with_parse_action[None]</b></font> - assert ParseResults([], {}) == None
<font color="#AA0000">FAILED</font> tests/test_pyparsing.py::<font color="#FFFFFF"><b>test_no_parse_action</b></font> - AssertionError: assert ParseResults([], {}) == &apos;&apos;
<font color="#AA0000">=================== </font><font color="#FF8787"><b>3 failed</b></font>, <font color="#44AA44">7 passed</font>, <font color="#AA5500">1 warning</font><font color="#AA0000"> in 0.34s ===================</font>
<font color="#AA0000">ERROR: InvocationError for command /home/sabin/extension-ai/.tox/py39/bin/pytest tests/test_pyparsing.py (exited with code 1)</font>
__________________________________ summary ___________________________________
<font color="#AA0000">ERROR:   py39: commands failed</font>
</pre>

I wonder: It looks like an inconsistency but it could also be intentional. I thought, I will better get in contact before I start digging in too much. If this is a bug, I am happy to work on it.

**Comment by ptmcg** [comment]
Looking at this this afternoon.

**Comment by ptmcg** [comment]
`ParseResults` will not add a "nullish" value, like [], () or "". But we all know that "" is rarely an empty sequence like [] or () are, but very often a legitimate string value. If I remove "" from the list of null values that `ParseResults` drops on the floor, all of my unit tests still pass. This may be because this is a benign change, or because my unit tests are not very good. Since I am looking at dropping a2 release, this might be a decent time to try this change, before 3.1.0 becomes official.
