### ISSUE TITLE
Badly rendered railroad diagram

### ISSUE THREAD

**Issue by sammorley-short** [pyparsing/pyparsing#477]
I’m trying to generate a pyparsing grammar railroad diagram, as described [here](https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#generating-railroad-diagrams), but when I run the example script the render comes out wrong with all these black boxes.

Script:

```python
from pyparsing import Word, nums, alphas

street_address = Word(nums).set_name("house_number") + Word(alphas)[1, ...].set_name("street_name")
street_address.set_name("street_address")
street_address.create_diagram("street_address_diagram.html")
```

Render:

![Screenshot 2023-04-12 at 22 57 17](https://user-images.githubusercontent.com/20857520/231595573-a64771c2-1fd4-40f2-b3c2-f5e5ecc168f7.png)

(To install, I ran `pip install "pyparsing[diagrams]"`)

What am I doing wrong?

**Comment by ptmcg** [comment]
What versions of pyparsing and railroad-diagrams are you using?

**Comment by ptmcg** [comment]
I just started seeing this recently also, but thought it was an artifact of my using Unicode characters in my grammar.

It looks like a problem with the latest release of railroad-diagrams. When I reverted to version 2.0.4, the diagrams were properly rendered.

```pip install -U railroad-diagrams==2.0.4```

I'll follow up and submit a ticket to that project.
