### ISSUE TITLE
pyparsing.create_diagram("output.html") not compatible with railroad-diagrams 3.0

### ISSUE THREAD

**Issue by dmoore247** [pyparsing/pyparsing#484]
To get diagrams I `pip install railroad-diagram` which installed railroad 3.0.1 which does not work well. It produces black blotches.

<img width="616" alt="image" src="https://github.com/pyparsing/pyparsing/assets/1122251/fcf8c04a-f9a0-4cb0-a454-194b455fc7cb">

I'm on Python 3.8 and `pyparsing==3.0.9`

**Comment by dmoore247** [comment]
After much futzing around, found that the solution was to `pip install railroad-diagrams==2.0.4`

Leaving this for future me and community to find. Perhaps a setup dependency thing could stream line this as enhancement.

**Comment by ptmcg** [comment]
Thanks for reporting, this will be fixed in the next release - see Issue #477
