### ISSUE TITLE
Unused code in QuotedString

### ISSUE THREAD

**Issue by nijel** [pyparsing/pyparsing#488]
While investigating compatibility issues between Weblate and pyparsing 3.1.0, I've noticed the following code which is no longer used:

https://github.com/pyparsing/pyparsing/blob/c8b76646bf7f883b40951a08365522d286af4963/pyparsing/core.py#L3269

The usage of this attribute has been removed in https://github.com/pyparsing/pyparsing/commit/d46eb9e936d753d2836428e64cf1bb4d1f2b92f3.

**Comment by ptmcg** [comment]
I started looking at this code, and decided to give it a more thorough overhaul, including PEP8-ing the internal variables.

**Comment by ptmcg** [comment]
Fixed in 3.1.1
