### ISSUE TITLE
Different behaviour from `Word(string_of_chars)` and `OneOrMore(string_of_chars)`

### ISSUE THREAD

**Issue by rowlesmr** [pyparsing/pyparsing#495]
Initialising `Word`s in my grammar is by far the rate-limiting step in running my program (at the moment, at least), so I've been trying to work around it (as well as document what's going on to let you know).

To my mind `Word(string_of_chars)` should operate the same as `OneOrMore(string_of_chars)`, except that it doesn't (in at least this case).

```python
from pyparsing import (
    Word,
    OneOrMore,
)
if __name__ == "__main__":

    _allchars_ranges = [(0x0009,), (0x000A,), (0x000D,), (0x0020, 0x007E),
                        (0x00A0, 0xD7FF), (0xE000, 0xFDCF), (0xFDF0, 0xFFFD),
                        (0x10000, 0x1FFFD)]
        # , (0x20000, 0x2FFFD), (0x30000, 0x3FFFD),
        #                 (0x40000, 0x4FFFD), (0x50000, 0x5FFFD), (0x60000, 0x6FFFD),
        #                 (0x70000, 0x7FFFD), (0x80000, 0x8FFFD), (0x90000, 0x9FFFD),
        #                 (0xA0000, 0xAFFFD), (0xB0000, 0xBFFFD), (0xC0000, 0xCFFFD),
        #                 (0xD0000, 0xDFFFD), (0xE0000, 0xEFFFD), (0xF0000, 0xFFFFD),
        #                 (0x100000, 0x10FFFD)]
    allchars = []
    for rr in _allchars_ranges:
        allchars.extend(range(rr[0], rr[-1] + 1))
    allchars = "".join([chr(c) for c in allchars])

    print("Initialising 'works'.")
    works = Word(allchars)
    print("Initialising 'noworks'.")
    noworks = OneOrMore(allchars)

    s = "na💩me"  # chr(0x1f4a9)

    print("Parsing...")
    print(works.parse_string(s))
    #print(noworks.parse_string(s))  # uncomment to get a large error message.
```
edit: I cut down the number of code points to see the top of the error:

Traceback:
```python
Traceback (most recent call last):
  File "C:\Users\_______\AppData\Roaming\JetBrains\PyCharmCE2023.1\scratches\scratch_53.py", line 30, in <module>
    print(noworks.parse_string(s))  # uncomment to get a large error message.
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\_______\Documents\GitHub\pycifparse\venv\Lib\site-packages\pyparsing\core.py", line 1190, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected '\t\n\r !"#$%&\'()*+,-./0123456789:;<=>?@A  ... \U0001fffd', found 'na'  (at char 0), (line:1, col:1)
```

💩is chr(0x1f4a9), and is within the range above.

I'm running Python 3.11.4, Windows 10, `pip freeze`:
```
Jinja2==3.1.2
line-profiler==4.0.3
line-profiler-pycharm==1.1.0
MarkupSafe==2.1.3
pyparsing==3.1.0
railroad-diagrams==3.0.1
```

**Comment by ptmcg** [comment]
Note that "string_of_chars" is a str, not a pyparsing `ParserElement`. When most pyparsing classes are constructed with a str, that str gets converted to a `Literal`. So `OneOrMore(some_string)` gets constructed as `OneOrMore(Literal(some_string))`. You are seeing the difference between parsing a Word vs parsing a Literal. I am 100% sure your intention is _not_ to parse a `Literal(string_containing_1000000_chars)`.  

Fortunately, `Word` takes the input character string and creates a compact regex from them. You can save this regex, and then use it later to create a `Regex` object that should behave the same as the original `Word`.

```python
import pyparsing as pp
ppu = pp.unicode

# build a Word of all Unicode printables - this will take a few seconds
wd = pp.Word(pp.unicode.printables)

# get the generated regex string
print(wd.reString)
# '[!-\x84\x86-\x9f¡-??-\u1fff\u200b-?\u202a-\u202e‰-?\u2060-\u2fff?-\U0010ffff]+'

# use the regex to make Regex - much faster!
wd = pp.Regex(r'[!-\x84\x86-\x9f¡-??-\u1fff\u200b-?\u202a-\u202e‰-?\u2060-\u2fff?-\U0010ffff]+')
```

**Comment by rowlesmr** [comment]
Ta a lot for that. I could see that you were making a regex, but I couldn't quite follow what the code was doing.

> This is almost like compiling your Word object. I'm going to add this to the wiki page on Performance tips.

Yes! If I'm starting with a range of characters, it does seem a little roundabout to construct an enormous string just to deconstruct it back into ranges. I'm trying this out today.

**Comment by rowlesmr** [comment]
> So OneOrMore(some_string) gets constructed as OneOrMore(Literal(some_string)).

That could also explain my 10 Mb railroad file...

**Comment by rowlesmr** [comment]
> This is almost like compiling your Word object. I'm going to add this to the wiki page on Performance tips.

Yes! It took runtime from ~24 s to build the grammar and parse ~10 lines down to essentially instantaneous. 

I'm spending more time with this package!
