### ISSUE TITLE
pymicko example

### ISSUE THREAD

**Issue by zzarko** [pyparsing/pyparsing#514]
I haven't been using pyparsing for some time, but last week I got back to it again. I was curious to see if my example compiler pymicko still works with version 3, but found out that the example was excluded sometimes in version 3 life cycle due to licensing problem.

As I would like for that example to be included, if of course you still think that it is a good one, what can I do to make it compatible? Would adding another licence to it be OK from your end? Or changing the licence completely (I am not sure if I can do that now, but I think I can add another licence)?

**Comment by ptmcg** [comment]
This change was introduced as part of addressing Issue #440 (https://github.com/pyparsing/pyparsing/issues/440)

I'm not the best source for licensing legalities, but I do know that the MIT license that I chose for pyparsing is very open for use, even for commercial applications, with no constraints on the use of the library or requirement to publish source code.

If this is too "free" of a license for pymicko, then an alternative would be for you to publish pymicko separately to PyPI (the name is not currently taken by any other project) with whatever license you choose, and then I can add it to the "Who's Using Pyparsing" section in the wiki.

(There are a couple of other pyparsing examples that I plan to split out as separately installable packages - delta_time and invregex - not for licensing purposes, but for ease of separate installation. The Python docs give a good walkthrough on how to package up a Python project for publication to PyPI here: https://packaging.python.org/en/latest/tutorials/packaging-projects/) and this StackExchange answer links to a few projects that publish a package that contains just a single .py file: https://softwareengineering.stackexchange.com/questions/243044/single-python-file-distribution-module-or-package

**Comment by ptmcg** [comment]
Please reopen this issue if you find a way to add an MIT license to pymicko. Or if you release it separately, let me know and I'll include it in the pyparsing wiki list of projects that use pyparsing.
