### ISSUE TITLE
Character index (span data) of matched non-terminals/terminals

### ISSUE THREAD

**Issue by kgoba** [pyparsing/pyparsing#515]
I have still limited experience with `pyparsing`, but is it possible to access or somehow track start/end indices of parsed elements (also usually referred to as non-terminals and terminals in the CFG lingo) with regards to parsed string after or during parsing? I don't find any clues from the documentation nor even the source code itself.

**Comment by ptmcg** [comment]
You should be able to wrap the expression of interest in `Located`. Then the parsed results will include start and end location values. Those values will be offsets into the whole parsed input string - if you need to resolve the values to line and/or column number, use pyparsing's lineno and col methods.

**Comment by kgoba** [comment]
Thank you, that looks like exactly what I was looking for! I still have to give it a try, but I would consider this issue closed.
