### ISSUE TITLE
Should set_parse_action accept a class?

### ISSUE THREAD

**Issue by RoDuth** [pyparsing/pyparsing#516]
I have been adding type hints to an older project that has used pyparsing this way for some time now.   Where we have used a class mypy complains with:
`Argument 1 to "set_parse_action" of "ParserElement" has incompatible type "type[ClassName]"; exp...Callable[[ParseResults], Any] | Callable[[int, ParseResults], Any] | Callable[[str, int, ParseResults], Any]"`

We use a similar approach to what is described in [this article](https://dev.to/zchtodd/building-parsers-for-fun-and-profit-with-pyparsing-4l9e) (note the line stating 'The setParseAction method accepts any callable object, meaning you can pass functions or class objects') to generate sqlalchemy queries.

Minimalist example:
```python
from pyparsing import Word, alphas

class Hello:
    def __init__(self, tokens):
        self.name = tokens[0]

    def invoke(self, salutation):
        print(salutation, self.name)

statement = Word(alphas).set_parse_action(Hello)('statement')   # mypy complains

parsed = statement.parse_string('World').statement

parsed.invoke('Hello')

# Hello World
```
Is this accepted use?

**Comment by RoDuth** [comment]
Sorry, my mistake...  Seems I had incorrect type on `tokens`
e.g. this is fine:
```python
from pyparsing import Word, alphas, ParseResults

class Hello:
    def __init__(self, tokens: ParseResults):    # correct type
        self.name = tokens[0]

    def invoke(self, salutation):
        print(salutation, self.name)

statement = Word(alphas).set_parse_action(Hello)('statement')

parsed = statement.parse_string('World').statement

parsed.invoke('Hello')
```

**Comment by ptmcg** [comment]
Glad you sorted this out, and doubly glad that the type annotations are working for you.
