### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by nijel** [pyparsing/pyparsing#517]
Is Python 3.12 supported or are there some known issues? I see the CI tests are not executed with Python 3.12, so it might be useful to add.

I'm asking because our code using on pyparsing is failing on Python 3.12 (see https://github.com/translate/translate/issues/5071). It might be as well bug on our side, but before digging into that, I'd like to know whether it is expected to work or not.

**Comment by ptmcg** [comment]
My expectation is that pyparsing should be compatible with Python 3.12.

**Comment by nijel** [comment]
Yes, I will get to it later this week. I just wanted to make sure I'm not figuring out a known issue in case there is one :smile:.

**Comment by nijel** [comment]
Okay, our test failure turns out to be unrelated to pyparsing, I apologize for the confusion. Somehow a general bug was triggered only in code-path which is the only one using pyparsing, so I was looking for a problem here…
