### ISSUE TITLE
General code refactoring/denesting

### ISSUE THREAD

**Issue by InSyncWithFoo** [pyparsing/pyparsing#519]
Recently I started using pyparsing for a project of mine. While doing debugging I noticed that the code is so deeply nested and thus extremely hard to read.

Please consider refactoring the code. I will be submitting some small PRs, but I'm afraid that I won't be able to modify those places with undocumented arguments and such.

**Comment by ptmcg** [comment]
Released in 3.1.2 - thanks for the submission!
