### ISSUE TITLE
dictOf erroneously matches empty string

### ISSUE THREAD

**Issue by ptmcg** [pyparsing/pyparsing#53]
Because dictOf uses ZeroOrMore for its internal repetition, it is possible to for it to match the empty string, which causes problems when it is also part of a larger repetitive expression (loops forever).

Needs to be changed to use OneOrMore.

**Comment by ptmcg** [comment]
Released in 2.3.1

**Comment by calebmarchent** [comment]
Note: published documentation has not been updated?
https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#classes

> dictOf( key, value ) - convenience function for quickly declaring a dictionary pattern of Dict( ZeroOrMore( Group( key + value ) ) ).

though on the bright-side this allowed me to diagnose the issues I had with integrating 2.3.1.
