### ISSUE TITLE
IndentedBlock ignores indentation

### ISSUE THREAD

**Issue by veikman** [pyparsing/pyparsing#530]
An `IndentedBlock` seems to ignore the level of indentation of the lines that follow it, so that lines that are less indented than the block are parsed as elements of the block.

This may be a known defect but is not described by the documentation, nor by #369, nor fixed by the upgrade suggested in that issue. I’m running `pyparsing` 3.1.1. The following behaviour is the same in 3.0.9.

Sample script to reproduce the problem:

```python
import pyparsing as pp

branch = pp.Literal("branch") + pp.IndentedBlock(
    pp.OneOrMore(pp.Group(pp.Literal("leaf") + pp.Char(pp.identchars)))
)

data = """

branch
    leaf A
leaf B

"""

print(branch.search_string(data).dump())
```

I would expect that script to fail or ignore `leaf B` because `leaf B` is not indented. Instead, the script output shows that the two leaves are perceived to be siblings within one indented block:

```
[['branch', [['leaf', 'A'], ['leaf', 'B']]]]
[0]:
  ['branch', [['leaf', 'A'], ['leaf', 'B']]]
  [0]:
    branch
  [1]:
    [['leaf', 'A'], ['leaf', 'B']]
    [0]:
      ['leaf', 'A']
    [1]:
      ['leaf', 'B']
```

Adding an `empty` statement at the start of the block does not help. Varying the use of `Group` and `OneOrMore` does not help.

**Comment by ptmcg** [comment]
Thanks for your patience with this. Indented block handling has always been a challenge, in the face of pyparsing's "just skip over the whitespace" philosophy. And thanks for supplying a nice minimal reproducible example.

**Comment by Honza0297** [comment]
Hello, can I ask whether there is any progress?

**Comment by ptmcg** [comment]
`OneOrMore` is what is messing this up. `IndentedBlock` does that repetition for you - it has to so that it can detect the change in the leading whitespace.

See this working example:
```python
import pyparsing as pp

branch = pp.Literal("branch") + pp.IndentedBlock(
    #pp.OneOrMore(pp.Group(pp.Literal("leaf") + pp.Char(pp.identchars)))
    pp.Group(pp.Literal("leaf") + pp.Char(pp.identchars))
)

data = """

branch
    leaf A
    leaf Z
leaf B

"""

print(branch.search_string(data).dump())
```
prints:
```
[['branch', [['leaf', 'A'], ['leaf', 'Z']]]]
[0]:
  ['branch', [['leaf', 'A'], ['leaf', 'Z']]]
  [0]:
    branch
  [1]:
    [['leaf', 'A'], ['leaf', 'Z']]
    [0]:
      ['leaf', 'A']
    [1]:
      ['leaf', 'Z']
```

It's clear that I need to expand on the documentation for this feature.

**Comment by ptmcg** [comment]
If you wanted to make this recursive, you could make branch a Forward, and then have a branch be an alternative content to a leaf:

```python
import pyparsing as pp

branch = pp.Forward()
branch <<= pp.Literal("branch") + pp.IndentedBlock(
    pp.Group(pp.Literal("leaf") + pp.Char(pp.identchars)) | pp.Group(branch)
)

data = """

branch
    leaf A
    leaf Z
    branch
        leaf Q
leaf B

"""

print(branch.search_string(data).dump())
```

**Comment by Honza0297** [comment]
Thanks! `OneOrMore` in `IndentedBlock` was indeed the problem.
