### ISSUE TITLE
ignore one \n but do not ignore double \n

### ISSUE THREAD

**Issue by Freakwill** [pyparsing/pyparsing#531]
Let the parser ignore one \n, but not ignore double \n.

For example, parse `'a\nb\nc\n\nd\ne'`  to `['a\nb\nc', 'd\ne']`

**Comment by ptmcg** [comment]
Good to hear from you!

There are a couple of pieces needed for this to work. First, remove "\n" from the set of default whitespace characters. Second define your list item as a Combine of one or more Word(alphas) or a newline that is not followed by another newline. Then parse the whole thing as a delimited list, with two or more newlines as the delimiter.

``` python
import pyparsing as pp

text = """a\nb\nc\n\nd\ne"""
expected = ['a\nb\nc', 'd\ne']

# remove newlines from set of whitespace characters
pp.ParserElement.setDefaultWhitespaceChars(" ")

# define expressions for newlines
NL = pp.LineEnd()
single_newline = NL + ~pp.FollowedBy(NL)
two_or_more_newlines = NL * (2, ...)

# a single item is the concatenation of 1 or more (Word(alphas) or a newline not followed by another newline)
item = pp.Combine((pp.Word(pp.alphas) | single_newline)[1, ...])

# parse the input as a delimited list, with "\n\n" as the delimiter
result = pp.DelimitedList(item, delim=two_or_more_newlines).parse_string(text).asList()

print(result)
assert result == expected

```
