### ISSUE TITLE
Changes towards 3.2.0

### ISSUE THREAD

**Issue by InSyncWithFoo** [pyparsing/pyparsing#535]
According to [`CHANGES`](https://github.com/pyparsing/pyparsing/blob/2a1a8e8f4beee7fd120c3fdc1a48725b77e263c2/CHANGES#L5), these changes are the goals of the next minor version, 3.2.0:

* [ ] Usage of pre-PEP8 names should raise `DeprecationWarning`s.
* [ ] Remove support for Python 3.7 (reached EOL last June, 6 months ago) and 3.6 (reached EOL in December 2021, 2 years ago)

**Comment by ptmcg** [comment]
Thanks for the punch list - given how long these things take me to fit in around other life activities, I modified my plan slightly: removing 3.6, 3.7, _and_ 3.8, and deferring the PEP8 synonyms deprecation to 3.3.0. I now have a 3.2.0 branch, and have incorporated all these changes, 3.2.0a1 to be released Real Soon Now.

**Comment by ptmcg** [comment]
Changes incorporated in 3.2.0 release, thanks!

Closing.
