### ISSUE TITLE
How to resolve the conflict between OneOrMore and Keyword

### ISSUE THREAD

**Issue by Gu-f** [pyparsing/pyparsing#558]
```python
import pyparsing as pp

str_text = "get a b c from cup;"

content = pp.Word(pp.alphas)

content_pos = pp.OneOrMore(content).set_name("contents")

container = pp.Word(pp.alphas).set_name("container")
end_flag = ';'

get = pp.Keyword('get')
from_ = pp.Keyword('from')

pattern = get + content_pos + from_ + container + end_flag

print(pattern.parse_string(str_text))
```
I got an error `pyparsing.exceptions.ParseException: Expected Keyword 'from', found ';'  (at char 18), (line:1, col:19)`
`from` is matched by `content_pos`  
But I want `from` as a keyword to be matched by `from_`  
How should I fix it, thanks

**Comment by Gu-f** [comment]
I found the `stop_on`, it satisfies.
`content_pos = pp.OneOrMore(content, stop_on=from_).set_name("contents")`

**Comment by ptmcg** [comment]
Glad you were able to find this solution for yourself - stop_on is definitely the correct solution for this.

There is a note in the wiki on Common Pitfalls when Writing Parsers, and I also just wrote up [a blog post](https://thingspython.wordpress.com/2024/06/01/repetition-in-pyparsing-why-is-it-so-dumb/) that goes into more detail on just what is going on in pyparsing.
