### ISSUE TITLE
Version 3.1.4 broke on Python 3.6

### ISSUE THREAD

**Issue by ceshihao** [pyparsing/pyparsing#568]
Version 3.1.4 broke on Python 3.6
![image](https://github.com/user-attachments/assets/012e87e7-dc8f-4407-9635-5391d3838d0d)
But Pypi meta is not updated. It still requires Python >=3.6.8.
https://pypi.org/project/pyparsing/3.1.4/
![image](https://github.com/user-attachments/assets/43da5c1f-7f72-4a17-9cc6-4099c6c60dcb)

**Comment by ptmcg** [comment]
I'm sorry for the poor wording in this note. This problem was a regression in pyparsing 3.1.3 that was fixed in 3.1.4.  pyparsing 3.1.4 _is_ compatible with Python 3.6.

I'll clarify that this is fixing a bug that was introduced in pyparsing 3.1.3, and fixed in 3.1.4.

**Comment by ptmcg** [comment]
I've updated the CHANGES doc to make this a little clearer. Thanks for submitting this issue!
