### ISSUE TITLE
wikispaces is closing down

### ISSUE THREAD

**Issue by metaperl** [pyparsing/pyparsing#6]
[Wikispaces is closing down](http://blog.wikispaces.com/)  and PyParsing has a [wealth of information there](http://pyparsing.wikispaces.com).

**Comment by ptmcg** [comment]
I have exported the discussion board from the Wikispaces page, now I need to find a decent home for it.
Thanks for the heads-up.

**Comment by klahnakoski** [comment]
I suggest a `docs` subdirectory, and then it can be organized from there

**Comment by klahnakoski** [comment]
...which looks like you already have  :)

**Comment by ptmcg** [comment]
The directory is there, but the wikispaces content is yet to be populated.

**Comment by lowell80** [comment]
Any update on this?  I'm currently looking at different parsing options for python.

**Comment by ptmcg** [comment]
First pass at converting all the discussion files to Markdown. See the pyparsing/wikispaces-archive repo.

**Comment by ptmcg** [comment]
I'm closing this comment, the bulk of the discussion pages have been preserved in the pyparsing/wikispaces-archive repo, with minor edits and toc link fixes remaining.
