### ISSUE TITLE
Export arbitrary ParseElement as EBNF

### ISSUE THREAD

**Issue by cthoyt** [pyparsing/pyparsing#67]
I'm not really sure what the tractability of this issue is, so first I would ask: are grammars represented with PyParsing within the class of context free grammars?

If that's the case, it would be incredibly useful to export a grammar defined through the PyParsing DSL as an EBNF document. This would provide a programmatic specification in a standard format that other tools could use as well.

**Comment by klahnakoski** [comment]
@cthoyt Do you have a specific "other tool" in mind?  At the very least, I imagine each tool has its own subtitle variation of EBNF it accepts; focusing on just one to start will provide clarity.

**Comment by cthoyt** [comment]
I had [ANTLR](https://www.antlr.org/) in mind. I think now that I'm looking around I am really starting to appreciate the difficulties that variations in EBNF might cause, thanks for asking.

CC: @agenodrei

**Comment by cthoyt** [comment]
Thanks @klahnakoski and @ptmcg for the feedback. I'll build a toy implementation (if/when I have some free time from PhD life) and report back here!

**Comment by ptmcg** [comment]
I'm going to close this since it seems like this is more of a discussion thread now, instead of a specific issue per se. More general discussion and posts of your own work would be good material for the new pyparsing sub-reddit.
