### ISSUE TITLE
PyPI information is outdated

### ISSUE THREAD

**Issue by metaperl** [pyparsing/pyparsing#7]
For [the latest version of PyParsing](https://pypi.python.org/pypi/pyparsing/2.2.0) the PyPi entry:

1. The home page points to a wikispaces page but [wikispaces is closing down](https://github.com/pyparsing/pyparsing/issues/6)
1. The download link points to sourceforge when [a github link](https://github.com/pyparsing) may be more appropriate.

**Comment by hugovk** [comment]
Please see PR https://github.com/pyparsing/pyparsing/pull/15.
