### ISSUE TITLE
indentedBlock not clearing the indent stack when it partially matches, and then fails

### ISSUE THREAD

**Issue by TMiguelT** [pyparsing/pyparsing#74]
First of all, thanks for this amazingly powerful and expressive library. I'm so glad to have found it.

I want to parse a language that uses indentation semantically, and thus I am using the `indentedBlock` function. However, I want to use it in combination with `scanString()`, because not all text in my input string belongs to this language. 

However, in doing this I have noticed a bug in the `indentedBlock`. If you try to parse a string that *does* include an indented block, but *doesn't* completely parse, the indent stack will not be reverted to how it was, and thus it will fail to parse all correct statements.

To demonstrate this, I've made a simple test case: https://github.com/TMiguelT/PyparsingIndent/blob/master/indent.py. The comments explain that, if the `indentedBlock` expression matches, but then the rest of the parsing fails, then the parser will fail to match anything from then on.

**Comment by TMiguelT** [comment]
https://github.com/TMiguelT/PyparsingIndent/blob/95de92e8e68342e050db684ca354b16762fbdb4a/indent.py#L4-L50

**Comment by klahnakoski** [comment]
@TMiguelT may you turn this into a pull request? I use pyparsing, and tests like you wrote are important.  let me get back to you about where it belongs....

Thank you!

**Comment by klahnakoski** [comment]
It appears a stand-alone Python file in the examples directory seems to be the place tests go.

**Comment by TMiguelT** [comment]
I would only be comfortable making this a PR if I also fixed the bug in the same PR. I'll see if I can do that, though. 

Also, I don't think this is an example per se. I could probably make it into a new test in the unit tests file.

**Comment by ptmcg** [comment]
Thanks for sending this. I've reformatted your test case to fit into unitTests.py as:
```
class IndentedBlockResetTest(ParseTestCase):
    def runTest(self):
        import pyparsing as pp
        from textwrap import dedent

        def get_parser():
            """
            A valid statement is the word "block:", followed by an indent, followed by the letter A only
            """
            stack = [1]
            body = pp.indentedBlock(pp.Literal('A'), indentStack=stack, indent=True)
            block = 'block:' + body
            return block

        tests = [
            ("Match 1 block",
             """
             block:
                 A
             """, 1
            ),
            ("Match 0 block",
             """
             block:
                 B
             """, 0
             ),
            ("Match 1 block before fail",
             """
             block:
                 A
             block:
                 B
             """, 1
             ),
            ("Match 1 block after fail",
             """
             block:
                 B
             block:
                 A
             """, 1
             ),
        ]

        for msg, s, expected in tests:
            p = get_parser()
            r = p.searchString(dedent(s))
            r.pprint()
            self.assertEqual(len(r), expected, msg)
``` 
Curiously, `indentedBlock` already had a fix for this, which was commented out in version 1.5.3 (ca. 2010) based on reports from a user having performance issues with `indentedBlock` and deeply nested recursion. By restoring the commented-out code, this test passes. I'll see if I can find a way to accommodate both accuracy *and* speed.

(Hmmm, I've added some further subtests containing multiple A's, and then one with A and B, and this still breaks. So the simple lookahead doesn't really solve the problem. Still, you've given me a good set of mini-cases to work with.)

**Comment by ptmcg** [comment]
I just now saw your PR, and using a setFailAction to reset the stack is the best solution.

**Comment by TMiguelT** [comment]
Is my solution different to yours? How does it differ?

**Comment by ptmcg** [comment]
I adopted your solution of using a backup stack. I thought about having the fail action just pop the last value, but just resetting to the backup value is better.  I probably won't take your PR though, the code cleanup changes are too sweeping right now, as I grapple with 2.3.1 backward incompatibility bits. But frankly, I had completely forgotten about setFailAction, I use it so rarely. I also updated your test parser to handle nested blocks.

**Comment by ptmcg** [comment]
If you submit a new PR that just does the reset to a backup stack as part of a fail action, and your unit tests, I'll accept it (so you get GitHub credit as a contributor).

**Comment by TMiguelT** [comment]
Hmm? My PR only changes about 8 lines, and using a backup stack is basically all it does. Are you looking at an old version of it?

**Comment by ptmcg** [comment]
Ah! I was looking at individual changesets, not the overall PR changes. Why did you change ParseFatalException to ParseException? Otherwise, overall changes look okay. (Will accepting the PR fold in all the intermediate commits that you made?)

**Comment by TMiguelT** [comment]
Ah yes good point, I should probably change that back. Having said that, why is it invalid nesting an unrecoverable exception? There might be a case where you have `indentedBlock() ^ somethingElse()`, and making that a fatal exception stops the whole rule from matching.

**Comment by TMiguelT** [comment]
And yes, you can choose to squash the commits when you merge

**Comment by TMiguelT** [comment]
I'm happy to revert that particular change if you can merge this, though

**Comment by ptmcg** [comment]
Not an issue - the original purpose was to avoid burying exceptions that occur inside a nested line that would happen when backtracking. I'll sort out which way this should go, or add a conditional parameter to permit the user to choose which behavior they want. I'll sort out all these branches, releases, and PRs this weekend.

**Comment by TMiguelT** [comment]
Well if you're not sure if that particular change is going to stay, I can revert it, so you can merge straight away, and then separately work through that issue.
