### ISSUE TITLE
More intelligent or user-friendly exceptions

### ISSUE THREAD

**Issue by Freakwill** [pyparsing/pyparsing#76]
```python
import pyparsing as pp
a = pp.Literal('Hello') + pp.delimitedList(pp.pyparsing_common.identifier('subname'), '.')('Name')
a.parseString('Hello 123')
```

It will report
`pyparsing.ParseException: Expected identifier (at char 6), (line:1, col:7)`

I hope that it can point out the name of the expression `Name` and what I input, for example
`I expected "Name"(or "subname"), but got the numbers "123"`.

More ambitious idea is that it can report more than one errors, it can jump the current error to parse the next word.

Just a suggestion.

**Comment by ptmcg** [comment]
The latest version of pyparsing includes `ParseException.explain():`

```
>>> try:
...    a.parseString('Hello 123')
... except pp.ParseException as pe:
...    print(pp.ParseException.explain(pe))
...
Hello 123
      ^
ParseException: Expected identifier (at char 6), (line:1, col:7)
pyparsing.And - {"Hello" identifier [. identifier]...}
pyparsing.And - identifier [. identifier]...
pyparsing.Word - identifier

```
