### ISSUE TITLE
add tutorial

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyparsing/pyparsing#77]
add links to tutorial articles. examples exist but different from tutorials

**Comment by jthomperoo** [comment]
There's some docs here https://pyparsing-docs.readthedocs.io/en/latest/index.html which seem useful.

**Comment by ptmcg** [comment]
Please follow some of the notes I've left in the docstrings, starting with "help pypasring". About 1,000 lines of pyparsing's code are in-code docstrings with examples. There are also a few unofficial tutorials online, though they are a little out-of-date, and don't necessarily include the latest features.

I've opened up a sub-reddit [r/pyparsing](https://www.reddit.com/r/pyparsing/) that would be great for more discussions like this.
