### ISSUE TITLE
indentedBlock + scanString allows indentation that doesn't use whitespace

### ISSUE THREAD

**Issue by TMiguelT** [pyparsing/pyparsing#78]
I've written a test for pyparsing that demonstrates this issue:

```python
    def runTest(self):
        stack = [1]
        parser = pp.indentedBlock(pp.Literal('A'), indentStack=stack, indent=True)

        # Passes
        a = parser.searchString("""
            A
            A
            A
        """)
        self.assertEqual(len(a[0][0]), 3)

        # Also works, even though it shouldn't
        b = parser.searchString("""
        ____A
            A
            A
        """)
        self.assertEqual(len(b[0][0]), 3)
```

Basically, because `checkSubIndent` doesn't actually care about the characters used in indentation, it will allow this `____A` line, if it's the first line of a `scanString`, and it actually starts parsing at the `A`.

I'm thinking I should add some sort of check that the text used to indent each line is only whitespace?

**Comment by ptmcg** [comment]
I am concerned that you are orienting these changes around your use of searchString/scanString. Its possible that the checks you are considering belong not in indentedBlock but in the parser code that calls indentedBlock. Unlike other pyparsing constructs like Word or Literal, indentedBlock is fairly position and context sensitive, and so it is not surprising that using searchString or scanString with it has some issues like this.

I recently wrote a small indentedBlock snippet that used a precursor Empty() to initialize the indentStack to the correct column value. You may need some similar logic for this issue.

**Comment by TMiguelT** [comment]
You are correct in that I'm focusing on the `scanString` behaviour, but that's just how my use-case is. If you don't think this is a bug then I totally understand. I have already added a `lineStart()` rule just before the `indentedBlock()`, which solves this.

However, my point is more that `indentedBlock()` isn't implemented to check indented *whitespace*, it's only implemented to check character *position*, which seems a bit wrong, and this is exemplified by my example above, but I can see it causing trouble elsewhere.

**Comment by ptmcg** [comment]
I think it is very possible that an indented block could be preceded by an opening '{' on the same line, for example, so forcing leading whitespace would prevent such a parser from working.

For now I'm closing this as "Working as Designed".

**Comment by TMiguelT** [comment]
Fair enough!
