### ISSUE TITLE
How do you install pyparsing?

### ISSUE THREAD

**Issue by juandent** [pyparsing/pyparsing#79]
I am new to python. How do I install pyparsing?

**Comment by paulmcg-iio** [comment]
`pip install pyparsing` should be sufficient. You may want to do this using a virtual environment though, so that your system-wide Python environment stays "vanilla".

**Comment by paulmcg-iio** [comment]
You can also open a free account on pythonanywhere.com - pyparsing is pre-installed in that environment.
