### ISSUE TITLE
pyparsing for python code

### ISSUE THREAD

**Issue by bughunter99** [pyparsing/pyparsing#8]
Hi, I want to parse python code.
I want to make some script like python, and I wanted to find some code example to parse python.
Of course, this github contains simple examples, such as calc or sql.
But if possible, may I know whether there is parsing example for python code?

Thanks.

**Comment by ptmcg** [comment]
There is no pyparsing example for the complete Python language. But in the past I have written pyparsing scanners to scan for class declarations, method declarations, import statements, etc. depending on what I was looking for. For instance, I created a dependency graph of import statements across a large project by just creating a parser for the `import` statement, and then using that with `searchString` to find and parse all the `import` statements in the code. You could also carve off a subset of Python (say, just methods but not classes) and implement that. But you will find this to be a pretty complex task quickly, if your intention is to write a complete Python parser.

Good luck,
-- Paul
