### ISSUE TITLE
advantages of sexpdata vs pyparsing s-expressions

### ISSUE THREAD

**Issue by brando90** [pyparsing/pyparsing#86]
I just found that one can parse s-expressions using [pyparsing](https://github.com/pyparsing/pyparsing) using the example file [here](http://www.ccp4.ac.uk/dist/checkout/pyparsing-2.0.1/examples/sexpParser.py). But there is also [sexpdata](https://github.com/jd-boyd/sexpdata).

What are the advantages and disadvantages of using sexpdata vs pyparsing?

**Comment by ptmcg** [comment]
This will depend largely on the kind of S-expressions you will have to parse. You should try both and then determine for yourself. There are test cases included with both, so you should be able to run them for yourself. (I will note that there have been no commits on sexpdata in 5 years. As for pyparsing, its S-expression parser is not part of the actual package, but just included with the examples. But if you find issues with it, please report them so I can update the example accordingly.)

**Comment by brando90** [comment]
in five years compared to this one pyparsing that has been updated very recently (at least 3 months) when this comment was written.

Thanks.
