### ISSUE TITLE
Nested labels no longer work

### ISSUE THREAD

**Issue by jpsnyder** [pyparsing/pyparsing#90]
After updating from version 2.2.0, I have run into an issue where nested labels within a `listAllMatches` result name are no longer working. 

```python
import pyparsing as pp

variable = pp.Word('$', pp.alphanums)('name') + '[' + pp.pyparsing_common.integer('index') + ']'
variable_list = pp.delimitedList(variable('entries*'))

result = variable_list.parseString('$a[0], $b[2], $c[5]')
for entry in result.entries:
    print(entry.name, entry.index)
```

In version 2.2.0 I correctly get the following:
```
('$a', 0)
('$b', 2)
('$c', 5)
```

However, in both 2.3.0 and 2.4.0 I only get empty strings:
```
('', '')
('', '')
('', '')
```

Using `dump()` also confirms that the nested labels do not get filled in.

**Comment by ptmcg** [comment]
Results names were made more rigorous in the past few releases, which broke some existing code. The use of nested names is now more strict about requiring the nesting to be done using Groups. Try changing variable_list to:

    variable_list = pp.delimitedList(pp.Group(variable)('entries*'))

**Comment by jpsnyder** [comment]
Thanks! That looks to work.
