### ISSUE TITLE
Unable to debug my grammar

### ISSUE THREAD

**Issue by mcondarelli** [pyparsing/pyparsing#92]
Sorry to disturb, but I'm getting mad.

I must be doing something really stupid, but I'm unable to understand what.

I trimmed down my grammar to almost nothing:
```python
from pyparsing import *

ParserElement.setDefaultWhitespaceChars(' \t')

nl = Regex(r'\n(?!\n)').suppress()
ps = Regex(r'\n{2,}').suppress()
bl = Regex(r'\s*').suppress()

lbracket = Literal('[').suppress()
rbracket = Literal(']').suppress()
lbrace = Literal('{').suppress()
rbrace = Literal('}').suppress()

clazz = lbracket + ZeroOrMore(Word(alphas+'-')).setParseAction(' '.join) + rbracket
url = lbrace + Combine(OneOrMore(Word(alphanums+'-_.') | '/' | ':')) + rbrace

sep = Keyword('@sep') + Optional(clazz('class')) + Optional(url('url'))

book = OneOrMore(sep('sep') | nl)

# fragments ========================

@traceParseAction
def handle_clazz(toks):
    if len(toks) == 0:
        return None
    return ' '.join(toks)

@traceParseAction
def handle_url(toks):
    if len(toks) == 0:
        return None
    return ' '.join(toks)

# divisions ========================

@traceParseAction
def handle_sep(toks):
    return 'sep', {k: v for k, v in toks[1:]}

clazz.setParseAction(handle_clazz)
clazz.setDebug()
url.setParseAction(handle_url)
url.setDebug()

sep.setParseAction(handle_sep)
sep.setDebug()

frag = '''\

@sep[file]{OEBPS/Text/1.01-La_Missione.html}
@sep[the end]

'''

book.setDebug()
book.parseString(frag).pprint()
```
This seems to parse the whole fragment, but ParseActions are not called  and I do not see ParseResult names:
```
Match {{{"@sep" [{Suppress:("[") [W:(ABCD...)]... Suppress:("]")}] [{Suppress:("{") Combine:({{W:(ABCD...) | "/" | ":"}}...) Suppress:("}")}]} | Suppress:(Re:('\\n(?!\\n)'))}}... at loc 0(1,1)
Matched {{{"@sep" [{Suppress:("[") [W:(ABCD...)]... Suppress:("]")}] [{Suppress:("{") Combine:({{W:(ABCD...) | "/" | ":"}}...) Suppress:("}")}]} | Suppress:(Re:('\\n(?!\\n)'))}}... -> ['@sep', 'file', 'OEBPS/Text/1.01-La_Missione.html', '@sep', 'the end']
['@sep', 'file', 'OEBPS/Text/1.01-La_Missione.html', '@sep', 'the end']
```
What am I doing so wrong?

**Comment by ptmcg** [comment]
There are two things happening here, one fairly obvious, one fairly subtle.

The fairly obvious one is that you are using ".pprint()" to print out your results. The docs for pprint say that it displays the output "as a list", so you will never see the results names using this call. If you want to see the results names, use the `dump()` method:

    book_data = book.parseString(frag)
    print(book_data.dump())

But for this to work at all, you'll need to address the more subtle issue. And that is that defining a results name makes a *copy* of the given expression. So when you write:

    a = some expression
    larger_expression = a("name")

then later attaching a parse action to `a` will *not* be used when parsing `larger_expression`, because `larger_expression` references a *copy* of `a`, not the original `a`.

The solution is to attach the parse actions to `clazz` and `url` immediately after you define them, so that when they are used later in `sep`, the copies will have the same parse actions attached to them.

Sorry for your frustration, thanks for sticking with it!

**Comment by mcondarelli** [comment]
Thanks.
I will port to my full grammar.

in the meantime: is there a standard way to know if I'm in a nested production?
I mean:
`@speech[me]{Yesterday my boss said: @speech[boss]{Jump!} and I had to jump.}`

should be rendered something like:
`« Yesterday my boss said: “Jump” and I had to jump. »`
The two (nested) instances are rendered differently.
Can I know it at ParseAction time?

Thanks in Advance

**Comment by mcondarelli** [comment]
Thanks,
now it seems to work, even if I'm still struggling mostly because I'm missing some background information (e.g.: if I return a plain string in a Parse Action why I find it wrapped in a list at next production?)

I will close this issue, but I really would need some expert guidance and this is not the place for it; where (if anywhere) can I seek help? Is there some IRC channel, mailing-list, forum or whatever dedicated to Pyparsing? I already tried using StackOverflow, but I got no answers.

Thanks again!

**Comment by mcondarelli** [comment]
Sorry,
I'm still here :(

My grammar seems to work, but I have a problem I can't understand how to solve:
I need to produce HTML from a markup.
Normal convention holds:
- single NL emits a `<br/>`.
- multiple NL close a paragraph.
The latter is problematic because I need to place the the opening `<p>` in a place which is not unique (at start of several, possibly nested, productions) and, of course, I cannot open paragraph multiple times.

If I try to do everything in the Parse Actions I have problems in keeping track if an opening paragraph had been issued, because Parse Actions are called also lookahead attempts and I don't know if and when it actually is reduced.

I then tried inserting custom tokens in the stream (returning lists from Parse Actions) with the intention to filter them after parsing, but that has *other* problems:
- I have not been able to understand when certain named tokens are passed as strings or are wrapped in lists (often with a single element).
- adding markers seems to throw havoc in named parameters and I get my marker instead of the content (which is "somewhere else").

I attach the current (sorry) state of my project.
In particular I'm unable to understand why `Emitter.handle_speech` receives in `content` my added marker (`'@@openp@@'`) instead of `'discorso diretto'` or, better yet, I expected `['@@openp@@',  `'discorso diretto']`

What is the "right Way" to handle this kind of problems?

[snapshot.tar.gz](https://github.com/pyparsing/pyparsing/files/3180306/snapshot.tar.gz)

**Comment by mcondarelli** [comment]
Ok.
I found [this](https://sourceforge.net/p/pyparsing/mailman/message/28157062/) and I completely restructured my parser.
Now it (almost) works.

**Comment by ptmcg** [comment]
I have started a pyparsing subreddit for more threaded discussions and general help and advice. https://www.reddit.com/r/pyparsing/
