### ISSUE TITLE
Automatic Parse Tree generation

### ISSUE THREAD

**Issue by mcondarelli** [pyparsing/pyparsing#94]
I made a rather short (and not complete, but working) addition to PyParsing to have it generate a hierarchical Parse Tree instead of a stream of tokens.

I attach my current tentative patch and my current test program.
I am currently testing with my grammar (which is particularly troublesome), but, if there is interest, I can make a proper pull request and add some reworked grammar from the "examples" directory.

Main rationale is you add specific names to ParseElements you want to keep as nodes in the final tree and the code tries to eliminate all "uninteresting" nodes (this makes output more an AST than a simple Parse Tree)

Any comment wound be greatly appreciated,
Thanks.

Here is the patch:
```diff
diff --git a/pyparsing.py b/pyparsing.py
index 5b5897f..87332b8 100644
--- a/pyparsing.py
+++ b/pyparsing.py
@@ -1568,6 +1568,99 @@ class ParserElement(object):
         tokens = self.postParse( instring, loc, tokens )
 
         retTokens = ParseResults( tokens, self.resultsName, asList=self.saveAsList, modal=self.modalResults )
+
+        # MCon: start of insertion
+        if True:  # FIXME: should check if we actually want an AST
+            class ASTNode(object):  # TODO: move class definition in global space.
+                def __init__(self, toks, name, parent):
+                    self.name = name
+                    self.kind = parent.__class__.__name__
+                    self.parent = None
+                    self.container = None
+                    self.children = []
+                    for tok in toks:
+                        try:
+                            tok.parent = self
+                            self.children.append(tok)
+                        except AttributeError:
+                            self.children.append(str(tok))
+                    self.streamline()
+
+                def __repr__(self):
+                    t = self.name if self.name else '<' + self.kind + '>'
+                    t += ': ['
+                    for c in self.children:
+                        if isinstance(c, ASTNode):
+                            t += '<node> '
+                        else:
+                            t += repr(c)
+                    return t
+
+                __str__ = __repr__
+
+                # TODO: implement a sensible __str__() member.
+                # def __str__(self):
+                #     return ' '.join(str(self.children))
+
+                def __iter__(self):
+                    return iter(self.children)
+
+                def dump(self, indent='  ', prefix=''):
+                    s = self.name if self.name else '-anonymus-'
+                    print(prefix, s, '<' + self.kind + '>')
+                    for n in self.children:
+                        try:
+                            n.dump(indent, indent + prefix)
+                        except AttributeError:
+                            print(prefix + ' -', repr(n))
+
+                def streamline(self):
+                    """
+                    Remove "useless" unnamed AST nodes from hierarchy.
+                    - Start from leafs (depth first).
+                        - Leaf is a node with no children (but may have content)
+                    - Go up one node.
+                    - If leaf has no name:
+                        - Merge Leaf contents with parent contents.
+                        - Remove Leaf from children.
+                        - If/when all children are removed parent becomes a Leaf.
+                    - Never merge/remove named nodes.
+                    """
+                    li = []
+                    for c in self.children:
+                        try:
+                            c.streamline()
+                            if c.name is None:
+                                for n in c.children:
+                                    li.append(n)
+                            elif c.name == self.name:
+                                if self.kind in ['MatchFirst', 'Optional']:
+                                    for n in c.children:
+                                        li.append(n)
+                            else:
+                                li.append(c)
+                        except AttributeError:
+                            li.append(c)
+                    self.children = li
+
+                def walk(self, cmds):
+                    func = cmds.get(self.name, self.__repr__)
+                    toks = []
+                    for c in self.children:
+                        try:
+                            toks.append(c.walk(cmds))
+                        except AttributeError:
+                            toks.append(c)
+                    return func(toks)
+
+            if len(retTokens) > 0:
+                tokens = [ASTNode(retTokens, retTokens.getName(), self)]
+                retTokens = ParseResults(tokens,
+                                         self.resultsName,
+                                         asList=self.saveAsList and isinstance(tokens, (ParseResults, list)),
+                                         modal=self.modalResults)
+        # MCon: end of insertion
+
         if self.parseAction and (doActions or self.callDuringTry):
             if debugging:
                 try:
```
and this is my test program:
```python3
from pyparsing import *


# GRAMMAR =================================================

ParserElement.setDefaultWhitespaceChars(' \t')

nl = Regex(r'\n(?!\n)').suppress()
ps = Regex(r'\n{2,}').suppress()
bl = Regex(r'\s*').suppress()

lbracket = Literal('[').suppress()
rbracket = Literal(']').suppress()
lbrace = Literal('{').suppress()
rbrace = Literal('}').suppress()

clazz = lbracket + ZeroOrMore(Word(alphas+'-')) + rbracket
url = lbrace + Combine(OneOrMore(Word(alphanums+'-_.') | '/' | ':'))('url') + rbrace
title = lbrace + ZeroOrMore(Word(alphanums+'-_.'))('title') + rbrace
text = Regex(r'[^@}\n]+')
style = lbracket + ZeroOrMore((Word(alphas+'-') + ':' + Word(printables+' ', excludeChars=';') + ';') | nl) + rbracket

frag = Forward()

sep = Literal('@sep').suppress() + Optional(clazz('clazz')) + Optional(url)
img = Literal('@img').suppress() + Optional(clazz('clazz')) + url
div = Literal('@div').suppress() + clazz('clazz') + Optional(style('style')) + lbrace + frag + rbrace
span = Literal('@span').suppress() + clazz('clazz') + lbrace + frag + rbrace

part = Literal("@part").suppress() + Optional(clazz('clazz')) + title
chapter = Literal("@chapter").suppress() + Optional(clazz('clazz')) + title
scene = Literal("@scene").suppress() + Optional(clazz('clazz')) + title

speech = Literal("@speech").suppress() + Optional(clazz('clazz')) + lbrace + frag + rbrace
stress = Literal("@stress").suppress() + Optional(clazz('clazz')) + lbrace + frag + rbrace
standout = Literal("@standout").suppress() + Optional(clazz('clazz')) + lbrace + frag + rbrace
quot = Literal("@quot").suppress() + Optional(clazz('clazz')) + Optional(style('style')) + lbrace + OneOrMore(frag) + rbrace

fragn = OneOrMore(div('div') | img('img') | speech('speech') | stress('stress') | standout('standout') | span('span') | text)
fragl = fragn + nl
fragp = fragn + ps
frag <<= (bl + OneOrMore(fragp('fragp') | fragl('fragl') | fragn('fragn')))

book = OneOrMore(part('part') | chapter('chapter') | scene('scene') | sep('sep') | frag | quot('quot') | Suppress('\n'))('book')


# MAIN ====================================================


if __name__ == '__main__':

    frag = '''\
@chapter[chapter]{First Chapter}

@scene{scene1}

Non quiquia eius porro. @speech{Modi sit sit adipisci ut.} Dolor eius aliquam ut. @speech{Voluptatem velit numquam etincidunt.} 
Quisquam ipsum sed sed. Quiquia sed dolore porro quisquam. Sed eius magnam numquam neque dolore. Amet sed dolor dolor. 
Non adipisci porro voluptatem aliquam magnam porro.

Consectetur amet tempora ipsum. Amet adipisci ipsum labore quiquia quaerat neque. Numquam ut dolorem dolore. 
Quiquia quiquia etincidunt eius ut. Quisquam quiquia etincidunt ipsum eius neque. 
Etincidunt voluptatem velit tempora dolor dolore quiquia. Ut adipisci dolor est porro quiquia.

Aliquam quiquia aliquam porro. Porro tempora etincidunt sit. Quisquam consectetur dolore labore. 
Dolore ut sit labore sit quaerat. Amet consectetur amet eius porro modi ipsum est. 
Modi labore sit tempora velit labore modi etincidunt. Etincidunt dolor adipisci labore.

@speech[speech]{Labore non quisquam velit quiquia amet quiquia modi. Dolor voluptatem eius adipisci consectetur adipisci.}
Tempora sed eius ipsum quiquia ut consectetur. Tempora etincidunt ipsum quisquam porro modi quaerat. 
Aliquam numquam velit dolorem dolor tempora quisquam.

Ut sed porro labore dolorem sit dolorem dolor. Porro porro dolore magnam adipisci voluptatem quisquam tempora. 
Eius sed etincidunt etincidunt. Ut aliquam modi sit aliquam. Magnam modi aliquam dolorem quiquia sed quiquia quaerat. 
Quiquia quaerat amet velit est.

@scene{scene2}

Velit quisquam sed neque sed dolore. Consectetur modi quisquam non. Magnam dolore porro amet amet velit. 
Quisquam sed dolor dolorem dolore sit sit dolorem. Dolorem numquam aliquam magnam quaerat dolor numquam. 
Dolor voluptatem magnam ut modi velit sed. Magnam amet adipisci dolore consectetur eius consectetur. 
Neque quisquam voluptatem magnam magnam velit etincidunt. Consectetur neque sit voluptatem aliquam adipisci.

Numquam eius numquam magnam. Sed voluptatem est eius sed numquam. Ut quaerat dolorem dolorem neque numquam amet quaerat. 
Dolorem quisquam velit modi consectetur neque porro. Voluptatem est tempora ut sed sed ipsum. 
Sed voluptatem magnam non neque non. Ipsum velit quisquam est aliquam dolore amet sit. 
Numquam tempora modi quaerat sed labore numquam. Dolorem quaerat porro dolore amet quaerat ipsum est.

Consectetur quisquam voluptatem voluptatem ut aliquam velit amet. Sed est modi quaerat ut eius labore eius. 
Quisquam est dolorem consectetur non magnam. Neque dolor porro ipsum ut modi. Aliquam neque ut adipisci velit eius. 
Sit ipsum tempora etincidunt dolore ipsum quisquam neque. Eius eius ut voluptatem etincidunt dolor.

Magnam voluptatem est neque. Magnam voluptatem labore dolorem. Consectetur quisquam neque amet ut consectetur consectetur. 
Ipsum non adipisci sed labore. Modi non adipisci neque dolore. Modi porro quiquia ut aliquam. Quiquia non ut est amet. 
Dolore aliquam sed numquam tempora labore.

@chapter[chapter]{second chapter}


    Frase con embedded@standout{key}word.
    '''

    r = book.parseString(frag)
    print('=====================================================================')
    r[0].dump()
    print('=====================================================================')
    cmds = {
        'fragn': lambda li: ''.join(li),
        'fragl': lambda li: ''.join(li) + '\n',
        'fragp': lambda li: ''.join(li) + '\n\n',
        'clazz': lambda li: '[' + ' '.join(li) + ']',
        'style': lambda li: '[' + ' '.join(li) + ']',
        'title': lambda li: '{' + ' '.join(li) + '}',

        'div': lambda li: '@div' + ''.join(li[:-1]) + '{' + li[-1] + '}',
        'img': lambda li: '@img' + ''.join(li[:-1]) + '{' + li[-1] + '}',
        'speech': lambda li: '@speech' + ''.join(li[:-1]) + '{' + li[-1] + '}',
        'stress': lambda li: '@stress' + ''.join(li[:-1]) + '{' + li[-1] + '}',
        'standout': lambda li: '@standout' + ''.join(li[:-1]) + '{' + li[-1] + '}',
        'span': lambda li: '@span' + ''.join(li[:-1]) + '{' + li[-1] + '}',

        'part': lambda li: '@part' + ''.join(li) + '\n\n',
        'chapter': lambda li: '@chapter' + ''.join(li) + '\n\n',
        'scene': lambda li: '@pscene' + ''.join(li) + '\n\n',
        'sep': lambda li: '@sep' + ''.join(li) + '\n\n',
        'quot': lambda li: '@quot' + ''.join(li) + '\n\n',
        'book': lambda li: ''.join(li) + '\n\n',
    }
    print(r[0].walk(cmds))
    print('=====================================================================')
    cmds = {
        'fragn': lambda li: ''.join(li),
        'fragl': lambda li: ''.join(li) + '\n',
        'fragp': lambda li: ''.join(li) + '\n\n',
        'clazz': lambda li: ' class="' + ' '.join(li) + '"',
        'style': lambda li: ' style="' + ' '.join(li) + '"',
        'title': lambda li: '{' + ' '.join(li) + '}',

        'div': lambda li: '<div' + ''.join(li[:-1]) + '>' + li[-1] + '</div>',
        'img': lambda li: '@img' + ''.join(li[:-1]) + '{' + li[-1] + '}',
        'speech': lambda li: '<div' + ''.join(li[:-1]) + '>' + li[-1] + '</div>',
        'stress': lambda li: '<i' + ''.join(li[:-1]) + '>' + li[-1] + '</i>',
        'standout': lambda li: '<b' + ''.join(li[:-1]) + '>' + li[-1] + '</b>',
        'span': lambda li: '<span' + ''.join(li[:-1]) + '>' + li[-1] + '</span>',

        'part': lambda li: '<h1' + ''.join(li[:-1]) + '>' + li[-1] + '</h1>\n\n',
        'chapter': lambda li: '<h2' + ''.join(li[:-1]) + '>' + li[-1] + '</h2>\n\n',
        'scene': lambda li: '<h3' + ''.join(li[:-1]) + '>' + li[-1] + '</h3>\n\n',
        'sep': lambda li: '@sep' + ''.join(li) + '\n\n',
        'quot': lambda li: '<quotmark' + ''.join(li[:-1]) + '>' + li[-1] + '</quotmark>\n\n',
        'book': lambda li: '<body>\n' + ''.join(li) + '</body>\n\n',
    }
    print(r[0].walk(cmds))
    print('=====================================================================')
```

**Comment by ptmcg** [comment]
Thanks for submitting this!

Just to set your expectations, I think AST construction is very likely to be something that will be difficult to address generically, and so I am doubtful that it will be a fit in the core pyparsing code. If you look through the examples, there are several that use Python classes as parse actions so as to generate a structure that is more like an AST than a simple nested group of parsed strings. simpleBool.py is one that I often refer people to, which combines both AST classes and the infixNotation helper method.

That being said, I *will* look through your submitted code, it may serve as a better example than simpleBool.py that more directly illustrates the parser-direct-to-AST process, without conflating its use with the infixNotation method.

-- Paul

**Comment by mcondarelli** [comment]
Thanks Paul,
I have been through at least some of the examples.
I feel the proposed solution (to be refined, for sure!) could be made generic enough to handle the normal cases just by decorating `ParserElement` with specific information.
For my specific case (and for other "simple cases" like fourFn.py) reusing `name` attribute is enough.
It might be some further attribute is needed to handle finer control, but I doubt it.

IMHO Parse Actions could/should be used to modify the generated AST without the need to use a lot of boilerplate code to handle the default case.

Of course if You are implementing a straight interpreter (like fourFn) you do not actually need an AST in the first place and simply handling computations on-the-fly is enough, without need to build and then walk the AST; OTOH there are cases (like mine) where I want to generate different outputs (LaTeX, HTML, ePub and, possibly, DOCX) from the same input (markup). Doing this in the "usual way" would mean rewrite ParseActions and, essentially, duplicate the whole code, which is a maintenance nightmare.

The code, as submitted, has problems handling whitespace, but that is a fault of my grammar and, AFAICT, has nothing to do with AST generation.

Thanks for your comments.

Raegards
Mauro

**Comment by ptmcg** [comment]
Overloading the concept of results names still gives me pause. When I have considered parsers that need to build a specialized data structure, I've usually fallen back to using parse actions, and potentially some expression generator that automates some of the tedium of building per-expression parse actions that could be parameterized.

Looking at the many places where you use the `clazz` expression and give every location the same name "clazz" lead me to look at modifying your `clazz` definition in the first place. Initially, I left your mod in place, and just moved the "clazz" results name (and eventually *all* the results names) up to their declaring expressions, not where the expressions were being used. This is pretty much backwards to all my prior recommendations on how to use results names, and to me is another telltale that this use of results names is not so much for accessing tokens by name, but for defining an expression-specific structure (which is of course exactly what you want - every 'clazz' should give a 'clazz'-like AST node, every 'chapter' should give a 'chapter'-like AST node, etc.).

I then copied your ASTNode class out of pyparsing, disabled your mod by changing `if True:` to `if False:` (thanks for that!), and changed your grammar to use an AST() method that defines a custom parse action, attaches the name and the parse action to the expr, and returns the expr:

    def AST(expr, name):
        def pa(s, l, t):
            return ASTNode(t, name, expr)
        return expr(name).addParseAction(pa)
       
    # GRAMMAR =================================================

    ParserElement.setDefaultWhitespaceChars(' \t')

    nl = Regex(r'\n(?!\n)').suppress()
    ps = Regex(r'\n{2,}').suppress()
    bl = Regex(r'\s*').suppress()

    lbracket = Literal('[').suppress()
    rbracket = Literal(']').suppress()
    lbrace = Literal('{').suppress()
    rbrace = Literal('}').suppress()

    clazz = AST(lbracket + ZeroOrMore(Word(alphas+'-')) + rbracket, 'clazz')
    url = lbrace + AST(Combine(OneOrMore(Word(alphanums+'-_.') | '/' | ':')), 'url') + rbrace
    title = lbrace + AST(ZeroOrMore(Word(alphanums+'-_.')), 'title') + rbrace
    text = Regex(r'[^@}\n]+')
    style = AST(lbracket + ZeroOrMore((Word(alphas+'-') + ':' + Word(printables+' ', excludeChars=';') + ';') | nl) + rbracket, 'style')

    frag = Forward()

    sep = AST(Literal('@sep').suppress() + Optional(clazz) + Optional(url), 'sep')
    img = AST(Literal('@img').suppress() + Optional(clazz) + url, 'img')
    div = AST(Literal('@div').suppress() + clazz + Optional(style('style')) + lbrace + frag + rbrace, 'div')
    span = AST(Literal('@span').suppress() + clazz + lbrace + frag + rbrace, 'span')

    part = AST(Literal("@part").suppress() + Optional(clazz) + title, 'part')
    chapter = AST(Literal("@chapter").suppress() + Optional(clazz) + title, 'chapter')
    scene = AST(Literal("@scene").suppress() + Optional(clazz) + title, 'scene')

    speech = AST(Literal("@speech").suppress() + Optional(clazz) + lbrace + frag + rbrace, 'speech')
    stress = AST(Literal("@stress").suppress() + Optional(clazz) + lbrace + frag + rbrace, 'stress')
    standout = AST(Literal("@standout").suppress() + Optional(clazz) + lbrace + frag + rbrace, 'standout')
    quot = AST(Literal("@quot").suppress() + Optional(clazz) + Optional(style) + lbrace + OneOrMore(frag) + rbrace, 'quot')

    fragn = AST(OneOrMore(div | img | speech | stress | standout | span | text), 'fragn')
    fragl = AST(fragn + nl, 'fragl')
    fragp = AST(fragn + ps, 'fragp')
    frag <<= (bl + OneOrMore(fragp | fragl | fragn))

    book = AST(OneOrMore(part | chapter | scene | sep | frag | quot | Suppress('\n')), 'book')

At a rough glance the output looks much the same as your original.

I'm pretty sure this gives you largely what you want, without necessarily conflating results naming with AST nodifying - you have separate control over what gets a name and what gets an AST node.

-- Paul

**Comment by ptmcg** [comment]
And here is a more non-invasive way to do this kind of thing. Fortunately all your expression var names are the same as the AST node names. (I picked this up from Seo Sanghyeon, who wrote the EBNF parser example):

    ParserElement.setDefaultWhitespaceChars(' \t')

    nl = Regex(r'\n(?!\n)').suppress()
    ps = Regex(r'\n{2,}').suppress()
    bl = Regex(r'\s*').suppress()

    lbracket = Literal('[').suppress()
    rbracket = Literal(']').suppress()
    lbrace = Literal('{').suppress()
    rbrace = Literal('}').suppress()

    clazz = lbracket + ZeroOrMore(Word(alphas+'-')) + rbracket
    url = lbrace + Combine(OneOrMore(Word(alphanums+'-_.') | '/' | ':')) + rbrace
    title = lbrace + ZeroOrMore(Word(alphanums+'-_.')) + rbrace
    text = Regex(r'[^@}\n]+')
    style = lbracket + ZeroOrMore((Word(alphas+'-') + ':' + Word(printables+' ', excludeChars=';') + ';') | nl) + rbracket

    frag = Forward()

    sep = Literal('@sep').suppress() + Optional(clazz) + Optional(url)
    img = Literal('@img').suppress() + Optional(clazz) + url
    div = Literal('@div').suppress() + clazz + Optional(style('style')) + lbrace + frag + rbrace
    span = Literal('@span').suppress() + clazz + lbrace + frag + rbrace

    part = Literal("@part").suppress() + Optional(clazz) + title
    chapter = Literal("@chapter").suppress() + Optional(clazz) + title
    scene = Literal("@scene").suppress() + Optional(clazz) + title

    speech = Literal("@speech").suppress() + Optional(clazz) + lbrace + frag + rbrace
    stress = Literal("@stress").suppress() + Optional(clazz) + lbrace + frag + rbrace
    standout = Literal("@standout").suppress() + Optional(clazz) + lbrace + frag + rbrace
    quot = Literal("@quot").suppress() + Optional(clazz) + Optional(style) + lbrace + OneOrMore(frag) + rbrace

    fragn = OneOrMore(div | img | speech | stress | standout | span | text)
    fragl = fragn + nl
    fragp = fragn + ps
    frag <<= (bl + OneOrMore(fragp | fragl | fragn))

    book = OneOrMore(part | chapter | scene | sep | frag | quot | Suppress('\n'))

    def AST(expr, name):
        def pa(s, l, t):
            return ASTNode(t, name, expr)
        expr.addParseAction(pa)

    for varname in "clazz url title style sep img div span part chapter scene speech stress standout quot fragn fragl fragp book".split():
        v = vars()[varname]
        AST(v, varname)

**Comment by mcondarelli** [comment]
Thanks.
Insight here is very valuable.
