### ISSUE TITLE
transformString loses whitespace?

### ISSUE THREAD

**Issue by ardeego** [pyparsing/pyparsing#97]
Hi, I like to use tranformString to act as a preprocessor for some custom protocol buffer files.  I worked off of the proto_buffer example in the example folder in the repo and defined a slightly more complete grammar.  I am able to parse a whole custom file just fine and successfully can edit some options fields (tokens values) with new values in the file using setParseAction. But when it comes to outputting the file all the whitespace is gone. The macros example in the examples folder did not seem to have that issue (it is not using Groups tho). Am I missing something here or is this a bug? Any help is greatly appreciated. Thanks.

```
top_level_defn = Group(
            message_defn("messages")
            | enum_defn("enums") 
            | extend_defn("extends")
            | service_defn("services")
        )

parser = (
            Optional(Group(SYNTAX_ + EQ + quotedString + SEMI)("syntax_name")) 
            + Group(ZeroOrMore(
                Group(import_defn("import_file_names")
                    | package_defn("package_name")
                    | option_defn("file_options")
                    | top_level_defn("top_level")
                    | SEMI)
                )
            )
        )
```
Input:
```

syntax = "proto2";

import "custom_options.proto";

option (custom_file_options).test.enable = true;
option (custom_file_options).test.allow_subschemas = true;
option (custom_file_options).test.message.schema = MESSAGE_SCHEMA_DECIMAL;
option (custom_file_options).test.enum.schema = ENUM_SCHEMA_DECIMAL;

message Message {
  option (custom_message_options).test.schema = MESSAGE_SCHEMA_BINARY;
  enum test {
    option (custom_enum_options).test.schema = ENUM_SCHEMA_BINARY;
    reserved 5000 to max;
    A = $0 [(custom_enum_value_options).test.override=true];
    B = 1;
    C = 2;
    D = 10;
    reserved 'F';
  }
  optional int32 a = $1 [default=0, (custom_field_options).test.override=true];
  optional int32 b = 2; 
  optional float c = 3;
}
```
the output from transformString then looks like:
```
syntax"proto2"import"custom_options.proto"option(custom_file_options).test.enabletrueoption(custom_file_options).test.allow_subschemastrueoption(custom_file_options).test.message.schemaMESSAGE_SCHEMA_DECIMALoption(custom_file_options).test.enum.schemaENUM_SCHEMA_DECIMALmessageMessageoption(custom_message_options).test.schemaMESSAGE_SCHEMA_BINARYenumtestoption(custom_enum_options).test.schemaENUM_SCHEMA_BINARYreserved5000tomaxA$0(custom_enum_value_options).test.overridetrueB1C2D10reservedFoptionalint32a$1default0(custom_field_options).test.overridetrueoptionalint32b2optionalfloatc3
```

**Comment by ptmcg** [comment]
Generally, when you are using `transformString`, you aren't writing expressions that will parse the full file, just those bits that need to be transformed. If you have other parts to parse but need to leave unchanged, you can wrap those expressions in `originalTextFor`.

What part of this parser does the transform?

**Comment by ardeego** [comment]
Hi thanks so much for the quick response. Yeah, I digged a bit in the code a bit and found that it just expands with asList if it comes across a nested ParseResult. I guess I am using this the wrong way ;). The way I thought I could use this was to read the options switches at the beginning of the file and the modify some of the field/enum numbers after if they carry the $ prefix. I thought I could do it all in one pass and it would keep track of the syntax element and whitespace around. But I guess I could just parse the options out as single expressions then have the field/enum expressions be modified in a second pass individually. Thanks for your help.
